Repository SeldonIO/seldon-core, pull requests merged in 2019-08, with the labels that each got.

#755 correct ACK naming in doc and examples
  doc/source/examples/alibaba_ack_deep_mnist.nblink
  doc/source/examples/alibaba_aks_deep_mnist.nblink
  doc/source/examples/notebooks.rst
  examples/models/alibaba_ack_deep_mnist/.s2i/environment
  examples/models/alibaba_ack_deep_mnist/DeepMnist.py
  examples/models/alibaba_ack_deep_mnist/README.md
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist_files/alibaba_cloud_ack_deep_mnist_16_0.png
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist_files/alibaba_cloud_ack_deep_mnist_52_0.png
  examples/models/alibaba_ack_deep_mnist/create_model.py
  examples/models/alibaba_ack_deep_mnist/deep_mnist.json
  examples/models/alibaba_ack_deep_mnist/deep_mnist_deployment.yaml
  examples/models/alibaba_ack_deep_mnist/images/graf.jpg
  examples/models/alibaba_ack_deep_mnist/images/k8s-dashboard-1.jpg
  examples/models/alibaba_ack_deep_mnist/images/k8s-dashboard-2.jpg
  examples/models/alibaba_ack_deep_mnist/images/k8s-dashboard.jpg
  examples/models/alibaba_ack_deep_mnist/requirements.txt
  examples/models/alibaba_ack_deep_mnist/tiller-role-binding.yaml
Labels: size/S

#744 Fix some doc needed to make this work
  doc/source/python/python_wrapping_docker.md
Labels: size/XS

#759 single replica ambassadoar
  testing/scripts/k8s_utils.py
Labels: size/XS

#729 repoint at tfserving public bucket
  doc/source/servers/tensorflow.md
  examples/models/tfserving-mnist/mnist_tfserving_deployment.json.template
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
  examples/models/tfserving-mnist/tfserving-mnist/values.yaml
  integrations/tfserving/README.md
  notebooks/server_examples.ipynb
  servers/tfserving/samples/mnist_grpc.yaml
  servers/tfserving/samples/mnist_rest.yaml
Labels: size/S

#751 add the support for multipart/form-data in python service and engine
  engine/pom.xml
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  engine/src/main/java/io/seldon/engine/exception/APIException.java
  engine/src/main/java/io/seldon/engine/predictors/SimpleModelUnit.java
  engine/src/test/java/io/seldon/engine/api/rest/TestRestClientController.java
  examples/models/sklearn_iris_multipart_formdata/.s2i/environment
  examples/models/sklearn_iris_multipart_formdata/IrisClassifier.py
  examples/models/sklearn_iris_multipart_formdata/requirements.txt
  examples/models/sklearn_iris_multipart_formdata/sklearn_iris_multipart_formdata.ipynb
  examples/models/sklearn_iris_multipart_formdata/sklearn_iris_multipart_formdata_deployment.json
  examples/models/sklearn_iris_multipart_formdata/train_iris.py
  openapi/engine.oas3.json
  openapi/wrapper.oas3.json
  python/seldon_core/flask_utils.py
  python/seldon_core/openapi/seldon.json
  python/tests/resources/test.png
  python/tests/resources/test.txt
  python/tests/test_model_microservice.py
Labels: size/XXL

#763 Added metrics and fixed docs typos
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
Labels: size/XS

#778 Docs for svc orchestrator
  doc/source/graph/svcorch.md
  doc/source/index.rst
  notebooks/helm_examples.ipynb
Labels: size/L

#779 Update openapi and fix multipart check
  doc/source/developer/roadmap.md
  doc/source/workflow/serving.md
  openapi/Makefile
  openapi/README.md
  openapi/engine.oas3.json
  openapi/paths-ambassador.json
  openapi/swagger-ui-ambassador.png
  openapi/wrapper.oas3.json
  python/seldon_core/flask_utils.py
  python/seldon_core/openapi/seldon.json
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
Labels: size/L

#774 Added mlflow model server
  doc/source/examples/mlflow_server_ab_test_ambassador.nblink
  doc/source/examples/notebooks.rst
  doc/source/servers/mlflow.md
  doc/source/servers/overview.md
  doc/source/servers/sklearn.md
  examples/models/mlflow_server_ab_test_ambassador/README.md
  examples/models/mlflow_server_ab_test_ambassador/ab-test-mlflow-model-server-seldon-config.yaml
  examples/models/mlflow_server_ab_test_ambassador/images/grafana-mlflow.jpg
  examples/models/mlflow_server_ab_test_ambassador/images/mlflow-dashboard.png
  examples/models/mlflow_server_ab_test_ambassador/mlflow-model-server-seldon-config.yaml
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
  examples/models/mlflow_server_ab_test_ambassador/wine-quality.csv
  helm-charts/seldon-core-operator/templates/crd.yaml
  notebooks/server_examples.ipynb
  proto/seldon_deployment.proto
  servers/mlflowserver/Makefile
  servers/mlflowserver/environment_grpc
  servers/mlflowserver/environment_rest
  servers/mlflowserver/mlflowserver/MLFlowServer.py
  servers/mlflowserver/mlflowserver/requirements.txt
  servers/mlflowserver/samples/elasticnet_wine.yaml
  servers/mlflowserver/test/.gitignore
  servers/mlflowserver/test/contract.json
  servers/mlflowserver/test/mlflow_example.ipynb
  util/custom-resource-definitions/crd.tpl.json
Labels: size/XXL

#757 WIP: Allow predict for sklearn standalone server as wll as predict_proba
  doc/source/servers/sklearn.md
  servers/sklearnserver/samples/iris_predict.yaml
  servers/sklearnserver/sklearnserver/SKLearnServer.py
  servers/sklearnserver/test/sklearn_iris.ipynb
Labels: size/L

#786 update docs, prediction proto with jsonData field
  doc/source/reference/apis/prediction.md
Labels: size/XS

#782 crd changes for creds secret
  helm-charts/seldon-core-operator/templates/crd.yaml
  proto/seldon_deployment.proto
  util/custom-resource-definitions/crd.tpl.json
Labels: size/S

#788 having image means hashed deployment name
  notebooks/server_examples.ipynb
  testing/scripts/test_prepackaged_servers.py
Labels: size/S

#787 Document how to use envSecretRefName to customize S3-like object store
  doc/source/servers/overview.md
Labels: size/M

#789 Updated MLFlow server removed commented code
  servers/mlflowserver/mlflowserver/MLFlowServer.py
Labels: size/XS

#792 Added custom file for redhat
  engine/custom-images/Dockerfile-redhat
Labels: size/S

#797 Update kustomize and update helm abtest/mab names
  helm-charts/seldon-abtest/templates/ab_test_1pod.json
  helm-charts/seldon-abtest/templates/ab_test_2pods.json
  helm-charts/seldon-core-operator/templates/crd.yaml
  helm-charts/seldon-mab/templates/mab.json
  kustomize/seldon-core-operator/Makefile
  kustomize/seldon-core-operator/base/kustomization.yaml
  kustomize/seldon-core-operator/base/seldon-config-cm.yaml
  kustomize/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  kustomize/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
  kustomize/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  notebooks/helm_examples.ipynb
Labels: size/XXL

#775 WIP - Analytics deployment update
  helm-charts/seldon-core-analytics/files/grafana/configs/predictions-analytics-dashboard.json
Labels: size/L

#793 TFServing functionality with latest python image
  examples/models/tfserving-mnist/grpc_mnist_tfserving_deployment.json
  examples/models/tfserving-mnist/rest_mnist_tfserving_deployment.json
  integrations/tfserving/Makefile
  integrations/tfserving/TfServingProxy.py
  integrations/tfserving/test_tfserving_proxy
  integrations/tfserving/test_tfserving_proxy.py
Labels: size/L

#684 WIP: Update python wrapper to use gunicorn
  doc/source/python/python_component.md
  examples/models/deep_mnist/DeepMnist.py
  examples/models/deep_mnist/deep_mnist.ipynb
  examples/models/mean_classifier/Makefile
  examples/models/sklearn_iris/requirements.txt
  examples/models/sklearn_iris/sklearn_iris.ipynb
  notebooks/resources/model_svcorch_sep.json
  python/seldon_core/microservice.py
  python/seldon_core/user_model.py
  python/setup.py
Labels: size/XL

#800 loadtest not needed with kubeflow and svc name seems to have changed
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
Labels: size/XS

#805 Fix for CVE-2018-1000654 in openjdk:8u201-jre-alpine3
  engine/Dockerfile
Labels: size/XS

#799 Improve error handling
  python/seldon_core/seldon_methods.py
Labels: size/S

#812 Added MLFLOW_SERVER in CRD files
  doc/source/reference/seldon-deployment.md
  helm-charts/seldon-core-operator/templates/crd.yaml
  kustomize/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  util/custom-resource-definitions/crd.tpl.json
Labels: size/XS

#766 set puid in case it is received in request
  python/seldon_core/utils.py
  python/tests/test_model_microservice.py
Labels: size/S

#730 ensure latest request logger
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
Labels: size/XS

#813 add documentation for ambassador_id support
  doc/source/ingress/ambassador.md
Labels: size/S

#806 Removing proto functionality from REST /predict endpoint [#803]
  python/seldon_core/seldon_methods.py
  python/seldon_core/utils.py
  python/tests/test_utils.py
Labels: size/L

#815 Fix typo in doc
  doc/source/servers/overview.md
Labels: size/XS

#818 Update all servers to use 0.12-SNAPSHOT and update to 0.2
  servers/mlflowserver/Makefile
  servers/mlflowserver/mlflowserver/requirements.txt
  servers/sklearnserver/Makefile
  servers/xgboostserver/Makefile
Labels: size/S

#817 Fixing multidimensional arrays being flattened
  python/seldon_core/utils.py
  python/tests/test_utils.py
Labels: size/M

#823 Refactor dataframe contract helper script into package
  doc/source/python/api/seldon_core.proto.rst
  doc/source/python/api/seldon_core.rst
  python/seldon_core/serving_test_gen.py
Labels: size/L

#827 configurable secure argument for minio client
  python/seldon_core/storage.py
Labels: size/XS

#814 Helm upgrade 0.4.0
  helm-charts/seldon-core-operator/templates/crd.yaml
  kustomize/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  util/custom-resource-definitions/crd.tpl.json
Labels: size/S

#830 Update autoscale example for new deployment name convention
  examples/models/autoscaling/autoscaling_example.ipynb
Labels: size/L

#819 Requirements version alignment across setup.py and requirements.txt
  python/requirements.txt
Labels: size/XS

#832 jaeger extra tags
  python/seldon_core/microservice.py
Labels: size/XS

#835 Fix typo
  doc/source/workflow/README.md
Labels: size/XS

#839 Fix tensor return in python wrapper
  python/seldon_core/utils.py
Labels: size/XS

#840 Update sklearn server examples with debug and fix notebook example
  notebooks/server_examples.ipynb
  servers/sklearnserver/samples/iris.yaml
  servers/sklearnserver/samples/iris_predict.yaml
Labels: size/XXL

#842 Removed url for model server
  notebooks/server_examples.ipynb
Labels: size/XS
