Repository SeldonIO/seldon-core, pull requests merged in 2019-07, with the labels that each got.

#675 Added requirements and spacy Docker file for Kubeflow example
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/Dockerfile
  examples/kubeflow/requirements-dev.txt
Labels: size/XS

#629 Alibi deployment example - Anchor Tabular
  doc/source/examples/alibi_anchor_tabular.nblink
  doc/source/examples/notebooks.rst
  examples/explainers/alibi_anchor_tabular/README.md
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment.ipynb
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment_files/alibi_anchor_tabular_seldon_deployment_17_1.png
  examples/explainers/alibi_anchor_tabular/img/deploy-overview.jpg
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier-explainer/.s2i/environment
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier-explainer/Explainer.py
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier-explainer/loanclassifiermodel-explainer.yaml
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier-explainer/requirements.txt
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier/.s2i/environment
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier/Model.py
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier/loanclassifiermodel.yaml
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier/requirements.txt
  examples/explainers/alibi_anchor_tabular/requirements-dev.txt
Labels: size/XXL

#667 WIP: Ambassador canary update
  doc/source/examples/sk-predictor.png
  doc/source/examples/sk-predictor2.png
  doc/source/examples/tf-predictor.png
  doc/source/examples/tf-predictor2.png
  doc/source/ingress/ambassador.md
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/canary/canary.json
  examples/ambassador/canary/model.json
  examples/istio/canary_update/canary.ipynb
  examples/istio/canary_update/canary.png
  examples/istio/canary_update/promoted-canary.png
  examples/istio/canary_update/sk-predictor.png
  examples/istio/canary_update/sk-predictor2.png
  examples/istio/canary_update/tf-predictor.png
  examples/istio/canary_update/tf-predictor2.png
Labels: size/L

#650 grafana and req logging configuration to work behind istio ingress gateway
  examples/centralised-logging/README.md
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/kubeflow/README.md
  examples/centralised-logging/kubeflow/kibana-values.yaml
  examples/centralised-logging/kubeflow/knative-setup-existing-istio.sh
  examples/centralised-logging/kubeflow/seldon-analytics-kubeflow.yaml
  examples/centralised-logging/kubeflow/virtualservice-elasticsearch.yaml
  examples/centralised-logging/kubeflow/virtualservice-kibana.yaml
  examples/centralised-logging/request-logging/README.md
  examples/centralised-logging/request-logging/knative-setup-minikube.sh
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  helm-charts/seldon-core-analytics/templates/grafana-prom-virtualservice.yaml
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/L

#679 Added subsection in documentation with suggested path to follow with examples
  doc/source/workflow/README.md
Labels: size/M

#681 move seldon analytics port
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/kubeflow/seldon-analytics-kubeflow.yaml
Labels: size/S

#678 scikit learn iris model using jsondata example
  examples/models/sklearn_iris_jsondata/.s2i/environment
  examples/models/sklearn_iris_jsondata/IrisClassifier.py
  examples/models/sklearn_iris_jsondata/requirements.txt
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata_deployment.json
  examples/models/sklearn_iris_jsondata/train_iris.py
Labels: size/XL

#689 Model servers
  doc/source/examples/notebooks.rst
  doc/source/examples/server_examples.nblink
  doc/source/index.rst
  doc/source/python/api/seldon_core.rst
  doc/source/servers/overview.md
  doc/source/servers/sklearn.md
  doc/source/servers/tensorflow.md
  doc/source/servers/xgboost.md
  doc/source/workflow/README.md
  engine/src/main/java/io/seldon/engine/predictors/PredictorConfigBean.java
  helm-charts/seldon-core-operator/templates/crd.yaml
  integrations/tfserving/Makefile
  integrations/tfserving/TfServingProxy.py
  integrations/tfserving/environment_grpc
  integrations/tfserving/environment_rest
  notebooks/server_examples.ipynb
  proto/seldon_deployment.proto
  python/seldon_core/__init__.py
  python/seldon_core/storage.py
  python/setup.py
  servers/sklearnserver/Makefile
  servers/sklearnserver/environment_grpc
  servers/sklearnserver/environment_rest
  servers/sklearnserver/samples/iris.yaml
  servers/sklearnserver/samples/iris_custom.yaml
  servers/sklearnserver/sklearnserver/SKLearnServer.py
  servers/sklearnserver/sklearnserver/requirements.txt
  servers/sklearnserver/test/.gitignore
  servers/sklearnserver/test/contract.json
  servers/sklearnserver/test/sklearn_iris.ipynb
  servers/tfserving/samples/mnist_grpc.yaml
  servers/tfserving/samples/mnist_rest.yaml
  servers/xgboostserver/Makefile
  servers/xgboostserver/environment_grpc
  servers/xgboostserver/environment_rest
  servers/xgboostserver/samples/iris.yaml
  servers/xgboostserver/test/.gitignore
  servers/xgboostserver/test/contract.json
  servers/xgboostserver/test/xgboost_iris.ipynb
  servers/xgboostserver/xgboostserver/XGBoostServer.py
  servers/xgboostserver/xgboostserver/requirements.txt
  util/custom-resource-definitions/.gitignore
  util/custom-resource-definitions/crd.tpl.json
Labels: size/XXL

#691 make model servers first example in docs
  doc/source/index.rst
Labels: size/XS

#699 Added TFServing JSON Support
  examples/models/tfserving-mnist/mnist_tfserving_deployment.json.template
  examples/models/tfserving-mnist/tfserving-mnist/templates/mnist_tfserving_deployment.json
  integrations/tfserving/Makefile
  integrations/tfserving/TfServingProxy.py
Labels: size/M

#702 fix(text): wrong word
  doc/source/reference/helm.md
Labels: size/XS

#687 Alibaba Cloud Elastic Container Service (AKS) example
  doc/source/examples/alibaba_aks_deep_mnist.nblink
  doc/source/examples/notebooks.rst
  examples/models/alibaba_aks_deep_mnist/.s2i/environment
  examples/models/alibaba_aks_deep_mnist/DeepMnist.py
  examples/models/alibaba_aks_deep_mnist/README.md
  examples/models/alibaba_aks_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/alibaba_aks_deep_mnist/alibaba_cloud_ack_deep_mnist_files/alibaba_cloud_ack_deep_mnist_16_0.png
  examples/models/alibaba_aks_deep_mnist/alibaba_cloud_ack_deep_mnist_files/alibaba_cloud_ack_deep_mnist_52_0.png
  examples/models/alibaba_aks_deep_mnist/create_model.py
  examples/models/alibaba_aks_deep_mnist/deep_mnist.json
  examples/models/alibaba_aks_deep_mnist/deep_mnist_deployment.yaml
  examples/models/alibaba_aks_deep_mnist/images/graf.jpg
  examples/models/alibaba_aks_deep_mnist/images/k8s-dashboard-1.jpg
  examples/models/alibaba_aks_deep_mnist/images/k8s-dashboard-2.jpg
  examples/models/alibaba_aks_deep_mnist/images/k8s-dashboard.jpg
  examples/models/alibaba_aks_deep_mnist/requirements.txt
  examples/models/alibaba_aks_deep_mnist/tiller-role-binding.yaml
Labels: size/XXL

#709 SSL for Seldon Python Client
  doc/source/examples/alibaba_aks_deep_mnist.nblink
  doc/source/examples/seldon_client.nblink
  doc/source/index.rst
  doc/source/python/index.rst
  doc/source/python/seldon_client.md
  notebooks/helm_examples.ipynb
  notebooks/seldon_client.ipynb
  python/requirements.txt
  python/seldon_core/seldon_client.py
Labels: size/XL

#717 fix framework name to official one
  doc/source/wrappers/README.md
Labels: size/XS

#712 Update request logger
  seldon-request-logger/Makefile
  seldon-request-logger/app/app.py
  seldon-request-logger/requirements.txt
Labels: size/L

#720 Update kustomize
  kustomize/seldon-core-operator/Makefile
  kustomize/seldon-core-operator/base/Kube-descriptor.yaml
  kustomize/seldon-core-operator/base/seldon-core-operator-sa.yaml
  kustomize/seldon-core-operator/base/seldon-operator-controller-manager-service-svc.yaml
  kustomize/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  kustomize/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
  kustomize/seldon-core-operator/base/seldon-operator-manager-rolebinding-crb.yaml
  kustomize/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  kustomize/seldon-core-operator/base/webhook-server-service-svc.yaml
  kustomize/seldon-core-operator/overlays/reporting/Kube-descriptor.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-config-cm.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-clusterrole.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-crb.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-sa.yaml
Labels: size/L

#716 Added centralised logging to docs for #636
  doc/source/analytics/logging.md
  doc/source/index.rst
Labels: size/L

#690 WIP: explainers
  helm-charts/seldon-core-operator/templates/clusterrole.yaml
  helm-charts/seldon-core-operator/templates/configmap.yaml
  helm-charts/seldon-core-operator/templates/crd.yaml
  proto/seldon_deployment.proto
  testing/scripts/conftest.py
  util/custom-resource-definitions/.gitignore
  util/custom-resource-definitions/Makefile
  util/custom-resource-definitions/crd.tpl.json
  util/custom-resource-definitions/create-crd.py
Labels: size/XXL

#704 TFServing Enabled Text Response and Fixed JSON Parse
  integrations/tfserving/Makefile
  integrations/tfserving/TfServingProxy.py
Labels: size/M

#721 update request logger
  seldon-request-logger/app/app.py
  seldon-request-logger/app/test.sh
Labels: size/M

#726 option to set operator-wide default for request logging
  doc/source/graph/annotations.md
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
  helm-charts/seldon-core-operator/templates/statefulset.yaml
  helm-charts/seldon-core-operator/values.yaml
Labels: size/S

#728 added seldon colours to Theme_override & seldon logo
  doc/source/Seldon_White.png
  doc/source/_static/theme_overrides.css
  doc/source/conf.py
Labels: size/M

#732 endpoint /seldon.json not returning the file
  doc/source/python/python_component.md
  python/seldon_core/wrapper.py
  python/tests/test_model_microservice.py
Labels: size/S

#736 config for explainer
  helm-charts/seldon-core-operator/templates/crd.yaml
  util/custom-resource-definitions/crd.tpl.json
Labels: size/L

#737 Fix typo in docstring
  python/seldon_core/seldon_client.py
Labels: size/XS

#738 Clarify what is meant by id in router documentation
  doc/source/python/python_component.md
Labels: size/XS
