Repository SeldonIO/seldon-core, pull requests merged in 2019-05, with the labels that each got.

#517 update argocd and jenkins in cd demo and script for minikube
  examples/cicd-argocd/README.md
  examples/cicd-argocd/argocd/argocd-app-create
  examples/cicd-argocd/argocd/get-argocd-browser-login
  examples/cicd-argocd/argocd/get-argocd-cmd-line-login
  examples/cicd-argocd/argocd/get-argocd-server-url
  examples/cicd-argocd/argocd/port-forward-argocd
  examples/cicd-argocd/argocd/show-argocd-logs
  examples/cicd-argocd/docker-devbox-manifest-updater
  examples/cicd-argocd/jenkins/get-jenkins-browser-login
  examples/cicd-argocd/jenkins/get-jenkins-url
  examples/cicd-argocd/jenkins/start-jenkins
  examples/cicd-argocd/jenkins/values.yml
  examples/cicd-argocd/k8s-local-docker-registry/start-docker-private-registry
  examples/cicd-argocd/settings.sh.example
Labels: size/L

#538 add script to delete completed argo jobs
  examples/cicd-argocd/README.md
  examples/cicd-argocd/argo/wf-delete-completed
  examples/cicd-argocd/settings.sh.example
Labels: size/S

#537 Allow fully qualified class name to be used for the model serving image.
  python/seldon_core/microservice.py
  python/tests/model-template-app2/.s2i/environment
  python/tests/model-template-app2/mymodule/my_model.py
Labels: size/XS

#558 Update e2e tests s2i python image version
  python/setup.py
  testing/scripts/test_s2i_python.py
Labels: size/XS

#547 update jackson-databind 2.8.11.2 -> 2.9.8 for cve
  api-frontend/pom.xml
  engine/pom.xml
Labels: size/S

#555 option for docker build without s2i
  doc/source/python/README.md
  doc/source/python/index.rst
  doc/source/python/python_component.md
  doc/source/python/python_wrapping_docker.md
  doc/source/python/python_wrapping_s2i.md
  doc/source/wrappers/README.md
Labels: size/L

#561 reword explanation of ambassador
  doc/source/graph/ambassador.md
Labels: size/XS

#539 redis now a statefulset as using redis helm chart
  examples/cicd-argocd/watch-rollout-status
Labels: size/XS

#567 option for R builds with plain docker
  doc/source/R/README.md
  doc/source/R/r_wrapping_docker.md
Labels: size/L

#570 fix typo
  doc/source/R/r_wrapping_docker.md
Labels: size/XS

#571 Fix example deployment yaml
  doc/source/graph/inference-graph.md
Labels: size/XS

#573 updated openvino version to 2019.1 in python_openvino model wrapper
  wrappers/s2i/python_openvino/Dockerfile_openvino_base
  wrappers/s2i/python_openvino/Makefile
  wrappers/s2i/python_openvino/README.md
Labels: size/M

#574 updated openvino mode ensemble to 0.2 version
  examples/models/openvino_imagenet_ensemble/README.md
  examples/models/openvino_imagenet_ensemble/resources/model/Makefile
  examples/models/openvino_imagenet_ensemble/seldon_ov_predict_ensemble.json
Labels: size/L

#575 Update TF version for security
  components/outlier-detection/vae/requirements.txt
Labels: size/XS

#577 Remove request limits from operator
  helm-charts/seldon-core-operator/templates/controller.yaml
Labels: size/XS

#578 Example using Seldon for text classification with SpaCy tokenizer
  examples/models/sklearn_spacy_text/RedditClassifier.py
  examples/models/sklearn_spacy_text/__init__.py
  examples/models/sklearn_spacy_text/ml_utils.py
  examples/models/sklearn_spacy_text/reddit_clf.json
  examples/models/sklearn_spacy_text/requirements.txt
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
Labels: size/XXL

#582 Added missed s2i folder to Scikitlearn SpaCy Text Example
  doc/examples/models/sk_mnist/sklearn_spacy_text.nblink
  examples/models/sklearn_spacy_text/.s2i/environment
Labels: size/XS

#581 AWS Elastic Kubernetes/Container Service Deep Mnist Example
  doc/source/examples/aws_eks_deep_mnist.nblink
  examples/models/aws_eks_deep_mnist/.s2i/environment
  examples/models/aws_eks_deep_mnist/DeepMnist.py
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/create_model.py
  examples/models/aws_eks_deep_mnist/deep_mnist.json
  examples/models/aws_eks_deep_mnist/requirements.txt
  examples/models/aws_eks_deep_mnist/tiller-role-binding.yaml
Labels: size/XXL

#541 Updating grafana to v6.1.6 in seldon core analytics
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  seldon-core/seldon-core-analytics/json/analytics.json
Labels: size/XS

#587 Added missing link to Jupyter notebook
  doc/source/examples/notebooks.rst
  doc/source/examples/sklearn_spacy_text_classifier_example.nblink
Labels: size/XS

#592 Fix Jupyter Notebook Headers
  examples/models/aws_eks_deep_mnist/README.md
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist_files/aws_eks_deep_mnist_11_0.png
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist_files/aws_eks_deep_mnist_63_0.png
  examples/models/sklearn_spacy_text/README.md
  examples/models/sklearn_spacy_text/requirements.txt
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example_files/sklearn_spacy_text_classifier_example_4_1.png
Labels: size/XXL

#594 Python release update
  doc/source/python/python_wrapping_s2i.md
  doc/source/reference/images.md
  examples/combiners/mnist_combiner/mnist_combiner.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/deep_mnist/deep_mnist.ipynb
  examples/models/keras_mnist/keras_mnist.ipynb
  examples/models/mlflow_model/mlflow.ipynb
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/skmnist.ipynb
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_fbs/sklearn_iris.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/template_model_bindata/modelWithBindata.ipynb
  examples/models/template_model_with_feedback/modelWithFeedback.ipynb
  examples/models/template_model_with_metrics/modelWithMetrics.ipynb
  integrations/sagemaker/Makefile
  integrations/tfserving/Makefile
  python/Makefile
  python/seldon_core/version.py
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/update_python_version.sh
Labels: size/XXL

#568 Update Python builder image
  python-builder/Dockerfile
  python-builder/Makefile
Labels: size/XS

#599 take latest ambassador image
  components/outlier-detection/isolation-forest/isolation_forest.ipynb
  components/outlier-detection/mahalanobis/outlier_mahalanobis.ipynb
  components/outlier-detection/seq2seq-lstm/seq2seq_lstm.ipynb
  components/outlier-detection/vae/outlier_vae.ipynb
  components/routers/case_study/credit_card_default.ipynb
  doc/source/workflow/install.md
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/cicd-argocd/seldon-core/start-seldon-core
  examples/combiners/mnist_combiner/mnist_combiner.ipynb
  examples/istio/canary_update/canary.ipynb
  examples/models/autoscaling/autoscaling_example.ipynb
  examples/models/aws_eks_deep_mnist/README.md
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/deep_mnist/deep_mnist.ipynb
  examples/models/h2o_mojo/h2o_model.ipynb
  examples/models/keras_mnist/keras_mnist.ipynb
  examples/models/mean_classifier_with_custom_endpoints/mean_classifier_with_custom_endpoints.ipynb
  examples/models/mlflow_model/mlflow.ipynb
  examples/models/nodejs_mnist/nodejs_mnist.ipynb
  examples/models/nodejs_tensorflow/nodejs_tensorflow.ipynb
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/onnx_resnet50/onnx_resnet50.ipynb
  examples/models/openvino/openvino-squeezenet.ipynb
  examples/models/openvino_imagenet_ensemble/openvino_imagenet_ensemble.ipynb
  examples/models/r_iris/r_iris.ipynb
  examples/models/r_mnist/r_mnist.ipynb
  examples/models/sagemaker/sagemaker_seldon_scikit_iris_example.ipynb
  examples/models/sk_mnist/skmnist.ipynb
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_spacy_text/README.md
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/template_model_bindata/modelWithBindata.ipynb
  examples/models/template_model_tracing/tracing.ipynb
  examples/models/template_model_with_feedback/modelWithFeedback.ipynb
  examples/models/template_model_with_metrics/modelWithMetrics.ipynb
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
  examples/wrappers/go/SeldonGoModel.ipynb
  notebooks/helm_examples.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/timeouts.ipynb
  testing/notebooks/helm_tests.ipynb
  testing/scripts/k8s_utils.py
  testing/scripts/test_helm_charts_clusterwide.py
Labels: size/L

#601 option to not set engine user
  helm-charts/seldon-core-operator/templates/controller.yaml
  helm-charts/seldon-core-operator/values.yaml
Labels: size/XS

#589 Kubeflow Seldon e2e NLP ML pipeline using re-usable components
  .gitignore
  doc/source/examples/kubeflow_seldon_e2e_pipeline.nblink
  doc/source/examples/notebooks.rst
  examples/kubeflow/README.md
  examples/kubeflow/deploy_pipeline/pvc-access.yaml
  examples/kubeflow/deploy_pipeline/seldon_production_pipeline.yaml
  examples/kubeflow/img/completed-pipeline-deploy.jpg
  examples/kubeflow/img/k-pipeline-dashboard.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-full.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-ml-pipelines-deploy.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-ml-pipelines-training.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-ml-pipelines-zoom.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-ml-pipelines.jpg
  examples/kubeflow/img/kubeflow-seldon-nlp-reusable-components.jpg
  examples/kubeflow/img/pipeline-only-run.jpg
  examples/kubeflow/img/pipeline-view.jpg
  examples/kubeflow/img/running-pipeline.jpg
  examples/kubeflow/img/seldon-analytics.jpg
  examples/kubeflow/img/upload-pipeline.jpg
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/kubeflow/pipeline/pipeline_steps/clean_text/.s2i/environment
  examples/kubeflow/pipeline/pipeline_steps/clean_text/Transformer.py
  examples/kubeflow/pipeline/pipeline_steps/clean_text/__init__.py
  examples/kubeflow/pipeline/pipeline_steps/clean_text/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/clean_text/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/clean_text/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/Dockerfile
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/__init__.py
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/.s2i/environment
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/Transformer.py
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/__init__.py
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/.s2i/environment
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/Transformer.py
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/__init__.py
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/.s2i/environment
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/Transformer.py
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/__init__.py
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/requirements.txt
  examples/kubeflow/pipeline/pipeline_tests/__init__.py
  examples/kubeflow/pipeline/pipeline_tests/test_pipeline.py
  examples/kubeflow/requirements-dev.txt
  examples/kubeflow/train_pipeline/nlp_pipeline.py
Labels: size/XXL

#595 Update SeldonMessage with jsonData
  proto/prediction.proto
  python/seldon_core/proto/prediction.proto
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
  python/seldon_core/utils.py
  python/tests/test_combiner_microservice.py
  python/tests/test_utils.py
  util/loadtester/scripts/proto/prediction.proto
Labels: size/L

#603 ambassador v1 api
  doc/source/graph/ambassador.md
  examples/ambassador/custom/model_custom_ambassador.json
Labels: size/XS

#588 WIP: Integrate with Istio Ingress
  doc/source/examples/istio_examples.nblink
  doc/source/examples/notebooks.rst
  doc/source/index.rst
  doc/source/ingress/ambassador.md
  doc/source/ingress/istio.md
  doc/source/ingress/seldon.md
  doc/source/python/python_module.md
  doc/source/workflow/install.md
  examples/istio/canary_update/canary.ipynb
  examples/istio/canary_update/canary.png
  examples/istio/canary_update/dashboard.png
  examples/istio/canary_update/dashboard2.png
  examples/istio/canary_update/mnist_v2.json
  examples/istio/canary_update/promoted-canary.png
  examples/istio/canary_update/utils.py
  helm-charts/seldon-core-controller/values.yaml
  helm-charts/seldon-core-loadtesting/Chart.yaml
  helm-charts/seldon-core-loadtesting/templates/locust-slave.yaml
  helm-charts/seldon-core-loadtesting/values.yaml
  helm-charts/seldon-core-operator/templates/controller.yaml
  helm-charts/seldon-core-operator/values.yaml
  notebooks/istio_example.ipynb
  notebooks/resources/seldon-gateway.yaml
  proto/seldon_deployment.proto
  python/seldon_core/api_tester.py
  python/seldon_core/seldon_client.py
  python/tests/test_seldon_client.py
  util/loadtester/Makefile
  util/loadtester/scripts/mnist_rest_locust.py
  util/loadtester/scripts/predict_rest_locust.py
Labels: size/XXL

#609 update jackson libs to version 2.9.9
  api-frontend/pom.xml
  engine/pom.xml
Labels: size/S
