Repository SeldonIO/seldon-core, pull requests merged in 2019-06, with the labels that each got.

#611 Update python wrappers to include 3.7
  wrappers/s2i/python/build_scripts/build_all.sh
  wrappers/s2i/python/build_scripts/build_all_local.sh
  wrappers/s2i/python/build_scripts/build_python3.7.sh
  wrappers/s2i/python/build_scripts/push_all.sh
Labels: size/XS

#615 Require python 3.6 or above for python module
  python/setup.py
Labels: size/XS

#617 node exporter configurable port
  helm-charts/seldon-core-analytics/templates/node-exporter-daemonset.json
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/S

#620 run python builder container using non-root user
  Makefile
Labels: size/XS

#624 Registry Image Tags and RBAC control for Operator Helm Chart
  helm-charts/seldon-core-operator/templates/controller.yaml
  helm-charts/seldon-core-operator/templates/spartakus-config-map.json
  helm-charts/seldon-core-operator/templates/spartakus-config-map.yaml
  helm-charts/seldon-core-operator/templates/spartakus-rbac.json
  helm-charts/seldon-core-operator/templates/spartakus-rbac.yaml
  helm-charts/seldon-core-operator/templates/spartakus-volunteer-deployment.json
  helm-charts/seldon-core-operator/templates/spartakus-volunteer-deployment.yaml
  helm-charts/seldon-core-operator/values.yaml
Labels: size/L

#627 generate service account
  helm-charts/seldon-core-operator/templates/_helpers.tpl
  helm-charts/seldon-core-operator/templates/clusterrole.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding.yaml
  helm-charts/seldon-core-operator/templates/controller.yaml
  helm-charts/seldon-core-operator/templates/secret.yaml
  helm-charts/seldon-core-operator/templates/service.yaml
  helm-charts/seldon-core-operator/templates/serviceaccount.yaml
  helm-charts/seldon-core-operator/templates/spartakus-config-map.yaml
  helm-charts/seldon-core-operator/templates/spartakus-rbac.yaml
  helm-charts/seldon-core-operator/templates/statefulset.yaml
  helm-charts/seldon-core-operator/values.yaml
Labels: size/XL

#628 points on why seldon
  readme.md
Labels: size/XS

#606 Update e2e tests
  testing/scripts/conftest.py
  testing/scripts/go_utils.py
  testing/scripts/k8s_utils.py
  testing/scripts/seldon_utils.py
  testing/scripts/test_dev.ipynb
  testing/scripts/test_helm_charts_clusterwide.py
Labels: size/L

#631 Update tracing example and fix api-tester grpc for ambassador
  examples/models/template_model_tracing/tracing.ipynb
  python/seldon_core/api_tester.py
Labels: size/L

#616 EFK with transform for tabular data
  doc/source/graph/annotations.md
  doc/source/graph/distributed-tracing.md
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  engine/src/main/java/io/seldon/engine/service/PredictionService.java
  engine/src/main/resources/application.properties
  engine/src/test/java/io/seldon/engine/pb/TestJsonParse.java
  engine/src/test/resources/application.properties
  examples/centralised-logging/README.md
  examples/centralised-logging/elastic-minikube.yaml
  examples/centralised-logging/fluentd-values.yaml
  examples/centralised-logging/full-setup.sh
  examples/centralised-logging/kibana-custom-search.png
  examples/centralised-logging/request-logging/README.md
  examples/centralised-logging/request-logging/knative-setup.sh
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
  examples/centralised-logging/request-logging/trigger.yaml
  helm-charts/seldon-mab/templates/mab.json
  helm-charts/seldon-mab/values.yaml
  helm-charts/seldon-od-model/templates/model.json
  helm-charts/seldon-od-model/values.yaml
  helm-charts/seldon-od-transformer/templates/model.json
  helm-charts/seldon-od-transformer/values.yaml
  helm-charts/seldon-openvino/templates/openvino_deployment.json
  helm-charts/seldon-openvino/values.yaml
  helm-charts/seldon-single-model/templates/model.json
  helm-charts/seldon-single-model/values.yaml
  readme.md
  seldon-request-logger/Dockerfile
  seldon-request-logger/Makefile
  seldon-request-logger/README.md
  seldon-request-logger/app/app.py
  seldon-request-logger/requirements.txt
Labels: size/XL

#638 Gpu tensorflow example
  doc/source/examples/gpu_tensorflow_deep_mnist.nblink
  doc/source/examples/notebooks.rst
  examples/models/gpu_tensorflow_deep_mnist/.s2i/environment
  examples/models/gpu_tensorflow_deep_mnist/DeepMnist.py
  examples/models/gpu_tensorflow_deep_mnist/Makefile
  examples/models/gpu_tensorflow_deep_mnist/README.md
  examples/models/gpu_tensorflow_deep_mnist/contract.json
  examples/models/gpu_tensorflow_deep_mnist/create_model.py
  examples/models/gpu_tensorflow_deep_mnist/deep_mnist_gpu.json
  examples/models/gpu_tensorflow_deep_mnist/gpu_tensorflow_deep_mnist.ipynb
  examples/models/gpu_tensorflow_deep_mnist/requirements.txt
  examples/models/gpu_tensorflow_deep_mnist/tiller-role-binding.yaml
  wrappers/s2i/python-gpu/python-gpu/Dockerfile
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/assemble
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/run
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/save-artifacts
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/usage
Labels: size/XXL

#649 Update loadtest notebook
  notebooks/benchmark_simple_model.ipynb
Labels: size/XL

#634 Remove ksonnet
  seldon-core/registry.yaml
  seldon-core/seldon-core-analytics/README.md
  seldon-core/seldon-core-analytics/analytics.libsonnet
  seldon-core/seldon-core-analytics/json/README.md
  seldon-core/seldon-core-analytics/json/analytics.json
  seldon-core/seldon-core-analytics/parts.yaml
  seldon-core/seldon-core-analytics/prototypes/analytics.jsonnet
  seldon-core/seldon-core/README.md
  seldon-core/seldon-core/core.libsonnet
  seldon-core/seldon-core/crd.libsonnet
  seldon-core/seldon-core/json/README.md
  seldon-core/seldon-core/json/hpa-validation.json
  seldon-core/seldon-core/json/object-meta-validation.json
  seldon-core/seldon-core/json/pod-spec-validation.json
  seldon-core/seldon-core/json/pod-template-spec-validation.json
  seldon-core/seldon-core/json/template_0.1.json
  seldon-core/seldon-core/json/template_0.2_cluster_wide.json
  seldon-core/seldon-core/json/template_0.2_single_namespace.json
  seldon-core/seldon-core/parts.yaml
  seldon-core/seldon-core/prototypes/abtest-v1alpha1.jsonnet
  seldon-core/seldon-core/prototypes/abtest-v1alpha2.jsonnet
  seldon-core/seldon-core/prototypes/core.jsonnet
  seldon-core/seldon-core/prototypes/mab-v1alpha1.jsonnet
  seldon-core/seldon-core/prototypes/mab-v1alpha2.jsonnet
  seldon-core/seldon-core/prototypes/outlier-detector-v1alpha1.jsonnet
  seldon-core/seldon-core/prototypes/outlier-detector-v1alpha2.jsonnet
  seldon-core/seldon-core/prototypes/serve-simple-v1alpha1.jsonnet
  seldon-core/seldon-core/prototypes/serve-simple-v1alpha2.jsonnet
Labels: size/XXL

#657 add prow info
  doc/source/developer/readme.md
Labels: size/XS

#661 [Docs] Fix formatting of s2i docs page
  doc/source/wrappers/s2i.md
Labels: size/XS

#651 Allow User Defined Exceptions
  doc/source/python/python_component.md
  python/seldon_core/wrapper.py
  python/tests/test_application_exception_microservice.py
Labels: size/L

#662 Change operator service selector
  helm-charts/seldon-core-operator/templates/service.yaml
  helm-charts/seldon-core-operator/templates/statefulset.yaml
Labels: size/S

#664 remove cluster-manager from jenkins build
  Jenkinsfile
Labels: size/S
