Repository SeldonIO/seldon-core, pull requests merged in 2019-04, with the labels that each got.

#480 make ambassador a dependency
  .gitignore
  components/outlier-detection/isolation-forest/isolation_forest.ipynb
  components/outlier-detection/mahalanobis/outlier_mahalanobis.ipynb
  components/outlier-detection/seq2seq-lstm/seq2seq_lstm.ipynb
  components/outlier-detection/vae/outlier_vae.ipynb
  components/routers/case_study/credit_card_default.ipynb
  doc/source/reference/helm.md
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/cicd-argocd/seldon-core/port-forard-ambassador
  examples/cicd-argocd/seldon-core/start-seldon-core
  examples/combiners/mnist_combiner/mnist_combiner.ipynb
  examples/istio/canary_update/canary.ipynb
  examples/istio/canary_update/setup_port_forwards.sh
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/openvino/openvino-squeezenet.ipynb
  examples/models/openvino_imagenet_ensemble/openvino_imagenet_ensemble.ipynb
  examples/models/template_model_bindata/modelWithBindata.ipynb
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
  helm-charts/seldon-core/charts/ambassador-2.0.1.tgz
  helm-charts/seldon-core/requirements.yaml
  helm-charts/seldon-core/templates/ambassador.yaml
  helm-charts/seldon-core/templates/rbac.yaml
  helm-charts/seldon-core/values.yaml
  notebooks/helm_examples.ipynb
  notebooks/ksonnet_examples.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/resources/ambassador-rbac.yaml
  notebooks/timeouts.ipynb
  seldon-core/seldon-core/json/README.md
  seldon-core/seldon-core/json/template_0.2_cluster_wide.json
  seldon-core/seldon-core/json/template_0.2_single_namespace.json
  start-seldon-core-private-repo
  testing/notebooks/helm_cluster_wide_tests.ipynb
  testing/notebooks/helm_single_namespace_tests.ipynb
  testing/notebooks/ksonnet_cluster_wide_tests.ipynb
  testing/notebooks/ksonnet_single_namespace_tests.ipynb
  testing/scripts/Makefile
  testing/scripts/k8s_utils.py
  testing/scripts/seldon_utils.py
  util/ksonnet/Makefile
Labels: size/L

#483 ignore pickle files
  .gitignore
Labels: size/XS

#488 Updates for various Python and Operator fixes
  .gitignore
  api-frontend/src/main/java/io/seldon/apife/deployments/DeploymentStore.java
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentStatusUpdateImpl.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/SeldonDeploymentStatusUpdateTest.java
  cluster-manager/src/test/resources/model_failed.json
  python/.coverage
  python/seldon_core/microservice.py
  python/tests/test_microservice.py
Labels: size/L

#493 Spelling
  doc/source/workflow/serving.md
Labels: size/XS

#492 ambassador v1 api
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/AmbassadorConfigTest.java
  doc/source/graph/ambassador.md
  doc/source/workflow/troubleshooting.md
  examples/ambassador/custom/model_custom_ambassador.json
  helm-charts/seldon-core/values.yaml
  testing/scripts/k8s_utils.py
  testing/scripts/seldon_utils.py
Labels: size/M

#496 Add missing additionProperties to openAPI specs for CRDS
  helm-charts/seldon-core-crd/templates/_hpa-spec-validation.tpl
  helm-charts/seldon-core-crd/templates/_object-meta-validation.tpl
  helm-charts/seldon-core-crd/templates/_pod-spec-validation.tpl
  seldon-core/seldon-core/json/hpa-validation.json
  seldon-core/seldon-core/json/object-meta-validation.json
  seldon-core/seldon-core/json/pod-spec-validation.json
  util/custom-resource-definitions/expand-validation.py
Labels: size/L

#485 484 metrics port
  api-frontend/src/main/resources/application.properties
  cluster-manager/src/main/java/io/seldon/clustermanager/ClusterManagerProperites.java
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java
  cluster-manager/src/main/resources/application.properties
  cluster-manager/src/test/java/io/seldon/clustermanager/AppTest.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/End2EndBase.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/End2EndSeparateEngineTest.java
  cluster-manager/src/test/resources/application.properties
  engine/src/main/resources/application.properties
  helm-charts/seldon-core/templates/apife-deployment.yaml
  helm-charts/seldon-core/templates/cluster-manager-deployment.yaml
  helm-charts/seldon-core/values.yaml
Labels: size/M

#500 Fix HPA Nullpointer
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/KubeCRDHandler.java
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/KubeCRDHandlerImpl.java
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeletionHandler.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/SeldonDeletionHandlerTest.java
Labels: size/S

#501 downgrade ambassador due to grpc unreliability
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/AmbassadorConfigTest.java
  doc/source/graph/ambassador.md
  examples/ambassador/custom/model_custom_ambassador.json
  helm-charts/seldon-core/values.yaml
  testing/scripts/seldon_utils.py
  testing/scripts/test_bad_graphs.py
Labels: size/M

#502 Allow class_names as method or attribute (deprecated) in Python module
  python/seldon_core/user_model.py
  python/tests/test_user_model.py
Labels: size/M

#503 Allow submodules to be imported in python module
  python/seldon_core/microservice.py
  python/tests/model-template-app2/.s2i/environment
  python/tests/model-template-app2/mymodule/MyModel.py
  python/tests/model-template-app2/mymodule/__init.py__
  python/tests/test_microservice.py
Labels: size/M

#509 default ambassador to singleNamespace
  components/outlier-detection/isolation-forest/isolation_forest.ipynb
  components/outlier-detection/mahalanobis/outlier_mahalanobis.ipynb
  components/outlier-detection/seq2seq-lstm/seq2seq_lstm.ipynb
  components/outlier-detection/vae/outlier_vae.ipynb
  components/routers/case_study/credit_card_default.ipynb
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/cicd-argocd/seldon-core/start-seldon-core
  examples/combiners/mnist_combiner/mnist_combiner.ipynb
  examples/istio/canary_update/canary.ipynb
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
  helm-charts/seldon-core/charts/ambassador-2.0.1.tgz
  helm-charts/seldon-core/charts/ambassador-2.1.0.tgz
  helm-charts/seldon-core/requirements.yaml
  helm-charts/seldon-core/values.yaml
  notebooks/helm_examples.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/timeouts.ipynb
  seldon-core/seldon-core/json/README.md
  start-seldon-core-private-repo
  testing/notebooks/helm_single_namespace_tests.ipynb
  testing/scripts/k8s_utils.py
  util/ksonnet/Makefile
Labels: size/M

#510 downgrade ambassador
  cluster-manager/README.txt
  helm-charts/seldon-core/values.yaml
  testing/scripts/test_bad_graphs.py
Labels: size/S

#513 Remove v1alpha3 and revert to v1alpha2
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentWatcher.java
  cluster-manager/src/main/resources/crd.json
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/SeldonDeploymentStatusUpdateTest.java
  cluster-manager/src/test/resources/model_failed.json
  helm-charts/seldon-core-crd/templates/seldon-deployment-crd.json
  seldon-core/seldon-core/crd.libsonnet
Labels: size/M

#516 Service Orchestrator Name Fix
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonNameCreator.java
  cluster-manager/src/test/java/io/seldon/clustermanager/k8s/End2EndSeparateEngineTest.java
  testing/scripts/test_rolling_updates.py
Labels: size/M

#520 seldpon_grpc_endpoint -> seldon_grpc_endpoint
  python/seldon_core/seldon_client.py
Labels: size/S

#446 Update redis
  helm-charts/seldon-core/values.yaml
Labels: Helm

#521 use stable redis helm chart
  helm-charts/seldon-core/charts/redis-6.4.5.tgz
  helm-charts/seldon-core/requirements.yaml
  helm-charts/seldon-core/templates/apife-deployment.yaml
  helm-charts/seldon-core/templates/cluster-manager-deployment.yaml
  helm-charts/seldon-core/templates/redis-deployment.yaml
  helm-charts/seldon-core/values.yaml
  helm-charts/seldon-core/values.yaml.example
Labels: size/M

#524 permission and timeout changes after trying on an openshift4 cluster
  cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  helm-charts/seldon-core/values.yaml
Labels: size/S

#530 option to use anonymous auth grafana
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/S

#531 Update component code coverage and dependencies docs
  api-frontend/Makefile
  cluster-manager/Makefile
  doc/source/index.rst
  doc/source/reference/apife-deps.rst
  doc/source/reference/apife-jacoco.rst
  doc/source/reference/apife.rst
  doc/source/reference/engine-deps.rst
  doc/source/reference/engine-jacoco.rst
  doc/source/reference/engine.rst
  engine/Makefile
Labels: size/M

#532 Revert "option to use anonymous auth grafana"
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/S

#534 Anonymous grafana
  helm-charts/seldon-core-analytics/templates/grafana-prom-import-dashboards-job.json
Labels: size/S
