Repository SeldonIO/seldon-core, pull requests merged in 2019-10, with the labels that each got.

#896 Fix typos
  notebooks/explainer_examples.ipynb
  notebooks/server_examples.ipynb
Labels: approved, size/XS

#895 Replace sed flag incompatible with macOS
  proto/k8s/Makefile
Labels: approved, size/XS

#898 Fix title of custom ambassador notebook, fix prerequistes typo
  doc/source/examples/notebooks.rst
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/istio/canary_update/canary.ipynb
  examples/models/autoscaling/autoscaling_example.ipynb
  notebooks/helm_examples.ipynb
  notebooks/istio_example.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/timeouts.ipynb
  testing/notebooks/helm_tests.ipynb
Labels: approved, ok-to-test, size/S

#900 fix so both permissive and strict mTLS will work
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/XS

#904 Update self-signed certificates for webhook for Operator
  helm-charts/seldon-core-operator/values.yaml
  operator/config/cert/mutating.yaml
  operator/config/cert/secret.yaml
  operator/config/cert/validating.yaml
  operator/generate-keys.sh
Labels: approved, size/S

#918 deployment not statefulset now
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/models/aws_eks_deep_mnist/README.md
  examples/models/azure_aks_deep_mnist/README.md
  examples/models/gpu_tensorflow_deep_mnist/README.md
  notebooks/explainer_examples.ipynb
Labels: approved, size/L

#920 some fixes to the centralised-logging install
  examples/centralised-logging/full-setup-existing-kubeflow.sh
Labels: approved, size/S

#923 operator rename - this one does need changing
  examples/centralised-logging/full-setup.sh
Labels: size/XS

#924 allow upgrade and install on dependencies
  examples/centralised-logging/full-setup-existing-kubeflow.sh
Labels: approved, size/S

#925 Add --max-requests and --max-requests jitter parameters for python wrapper
  python/seldon_core/microservice.py
Labels: approved, ok-to-test, size/S

#903 Update Java dependencies
  engine/pom.xml
  engine/src/main/java/io/seldon/engine/App.java
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  engine/src/main/java/io/seldon/engine/config/AppConfig.java
  engine/src/main/java/io/seldon/engine/config/CustomizationBean.java
  engine/src/main/java/io/seldon/engine/config/TomcatConfig.java
  engine/src/main/java/io/seldon/engine/grpc/GrpcChannelHandler.java
  engine/src/main/java/io/seldon/engine/grpc/SeldonGrpcServer.java
  engine/src/main/java/io/seldon/engine/metrics/MetricsConfig.java
  engine/src/main/java/io/seldon/engine/metrics/SeldonRestTemplateExchangeTagsProvider.java
  engine/src/main/java/io/seldon/engine/predictors/PredictiveUnitBean.java
  engine/src/main/resources/application.properties
  engine/src/test/java/io/seldon/engine/api/rest/TestRandomABTest.java
  engine/src/test/java/io/seldon/engine/api/rest/TestRestClientController.java
  engine/src/test/java/io/seldon/engine/api/rest/TestRestClientControllerExternalGraphs.java
  engine/src/test/java/io/seldon/engine/config/TestConfig.java
  engine/src/test/resources/application.properties
Labels: approved, size/L

#938 remove redis rollout watch
  examples/cicd-argocd/watch-rollout-status
Labels: approved, size/XS

#928 storage: Allow downloading a single s3 object
  python/seldon_core/storage.py
Labels: approved, ok-to-test, size/XS

#930 gcp private bucket docs
  doc/source/servers/overview.md
  operator/README.md
Labels: approved, size/M

#932 microservice: Fix get annotations format
  python/seldon_core/microservice.py
  python/tests/test_microservice.py
Labels: approved, ok-to-test, size/M

#940 Vol mount issue fix
  operator/api/v1alpha2/seldondeployment_webhook.go
Labels: approved, size/S

#944 bad json should be 400 not 500
  OWNERS
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  engine/src/main/java/io/seldon/engine/exception/APIException.java
Labels: approved, size/XS

#941 Add more test cases for load_annotations..
  python/tests/test_microservice.py
Labels: approved, lgtm, ok-to-test, size/XS

#953 Allow custom predictor service name
  doc/source/graph/annotations.md
  doc/source/graph/custom_svc_name.md
  operator/api/v1alpha2/seldondeployment_types.go
Labels: approved, size/M

#946 Fixed bug in SSL Seldon Client and added functionality in GRPC
  python/seldon_core/seldon_client.py
Labels: approved, size/M

#958 Self-signed certificates for Helm chart install of Operator
  doc/source/workflow/install.md
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-manager-css-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-manager-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-manager-sas-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-proxy-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/mutatingwebhookconfiguration_seldon-mutating-webhook-configuration.yaml
  helm-charts/seldon-core-operator/templates/rolebinding_seldon-leader-election-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/rolebinding_seldon-manager-cm-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/secret_seldon-webhook-server-cert.yaml
  helm-charts/seldon-core-operator/templates/validatingwebhookconfiguration_seldon-validating-webhook-configuration.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-core-operator/values-self-signed-cert.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/helm/split_resources.py
Labels: approved, size/L

#969 Add defaults to initcontainers
  operator/controllers/seldondeployment_controller.go
Labels: size/S

#976 Fix tracing
  engine/pom.xml
Labels: approved, size/XS

#978 Added adrian to reviewers in OWNERS file
  OWNERS
Labels: approved, size/XS

#942 Extra python dependencies
  .gitignore
  jenkins-x.yml
  python/Makefile
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
  python/seldon_core/proto/tensorflow/core/framework/__init__.py
  python/seldon_core/proto/tensorflow/core/framework/resource_handle.proto
  python/seldon_core/proto/tensorflow/core/framework/resource_handle_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor.proto
  python/seldon_core/proto/tensorflow/core/framework/tensor_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_shape.proto
  python/seldon_core/proto/tensorflow/core/framework/tensor_shape_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/types.proto
  python/seldon_core/proto/tensorflow/core/framework/types_pb2.py
  python/seldon_core/tf_helper.py
  python/seldon_core/utils.py
  python/setup.py
  python/tests/test_application_exception_microservice.py
  python/tests/test_model_microservice.py
  python/tests/test_utils.py
  python/tests/utils.py
Labels: approved, lgtm, size/XXL

#966 Add exception catching for grpc calls in engine
  engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java
  testing/scripts/README.md
Labels: size/L

#962 Remove kustomize folder
  kustomize/seldon-core-operator/Makefile
  kustomize/seldon-core-operator/README.md
  kustomize/seldon-core-operator/base/Kube-descriptor.yaml
  kustomize/seldon-core-operator/base/kustomization.yaml
  kustomize/seldon-core-operator/base/seldon-config-cm.yaml
  kustomize/seldon-core-operator/base/seldon-core-operator-sa.yaml
  kustomize/seldon-core-operator/base/seldon-operator-controller-manager-service-svc.yaml
  kustomize/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
  kustomize/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
  kustomize/seldon-core-operator/base/seldon-operator-manager-rolebinding-crb.yaml
  kustomize/seldon-core-operator/base/seldon-operator-webhook-server-secret-secret.yaml
  kustomize/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
  kustomize/seldon-core-operator/base/webhook-server-service-svc.yaml
  kustomize/seldon-core-operator/overlays/reporting/Kube-descriptor.yaml
  kustomize/seldon-core-operator/overlays/reporting/kustomization.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-config-cm.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-clusterrole.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-crb.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-deploy.yaml
  kustomize/seldon-core-operator/overlays/reporting/seldon-spartakus-volunteer-sa.yaml
  kustomize/seldon-core-operator/reporting_kustomize.yaml
Labels: approved, size/XXL

#971 Update watch-rollout-status for Argo CICD demo
  examples/cicd-argocd/watch-rollout-status
Labels: approved, ok-to-test, size/XS

#980 Added black formatter to seldon_core and testing folders
  python/seldon_core/__init__.py
  python/seldon_core/api_tester.py
  python/seldon_core/flask_utils.py
  python/seldon_core/metrics.py
  python/seldon_core/microservice.py
  python/seldon_core/microservice_tester.py
  python/seldon_core/persistence.py
  python/seldon_core/seldon_client.py
  python/seldon_core/seldon_methods.py
  python/seldon_core/serving_test_gen.py
  python/seldon_core/storage.py
  python/seldon_core/tf_helper.py
  python/seldon_core/user_model.py
  python/seldon_core/utils.py
  python/seldon_core/version.py
  python/seldon_core/wrapper.py
  python/setup.py
  python/tests/model-template-app/MyModel.py
  python/tests/model-template-app2/mymodule/my_model.py
  python/tests/test_api_tester.py
  python/tests/test_application_exception_microservice.py
  python/tests/test_combiner_microservice.py
  python/tests/test_metrics.py
  python/tests/test_microservice.py
  python/tests/test_microservice_tester.py
  python/tests/test_model_microservice.py
  python/tests/test_router_microservice.py
  python/tests/test_seldon_client.py
  python/tests/test_transformer_microservice.py
  python/tests/test_user_model.py
  python/tests/test_utils.py
  python/tests/utils.py
  testing/docker/fixed-model/ModelV1.py
  testing/docker/fixed-model/ModelV2.py
  testing/s2i/python/combiner/MyCombiner.py
  testing/s2i/python/model/MyModel.py
  testing/s2i/python/router/MyRouter.py
  testing/s2i/python/transformer/MyTransformer.py
  testing/scripts/conftest.py
  testing/scripts/k8s_utils.py
  testing/scripts/s2i_utils.py
  testing/scripts/seldon_utils.py
  testing/scripts/test_bad_graphs.py
  testing/scripts/test_helm_charts_clusterwide.py
  testing/scripts/test_prepackaged_servers.py
  testing/scripts/test_rolling_updates.py
  testing/scripts/test_s2i_python.py
Labels: approved, size/XXL

#983 Further Java updates
  engine/pom.xml
  engine/src/license/THIRD-PARTY.properties
  engine/src/main/java/io/seldon/engine/grpc/GrpcChannelHandler.java
  engine/src/main/java/io/seldon/engine/grpc/SeldonGrpcServer.java
  engine/src/main/java/io/seldon/engine/predictors/AverageCombinerUnit.java
  engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java
  engine/src/test/java/io/seldon/engine/api/rest/TestRandomABTest.java
  engine/src/test/java/io/seldon/engine/api/rest/TestRestClientControllerExternalGraphs.java
  engine/src/test/java/io/seldon/engine/config/TestConfig.java
Labels: approved, size/M

#985 Fix image explainer
  doc/source/graph/annotations.md
  doc/source/graph/model_engine_java_opts.md
  notebooks/explainer_examples.ipynb
  notebooks/resources/imagenet_explainer_grpc.yaml
  notebooks/resources/model_engine_java_opts.json
Labels: approved, size/L

#989 Set Http Status Code in REST Predict
  python/seldon_core/wrapper.py
  python/tests/test_model_microservice.py
Labels: approved, ok-to-test, size/M

#988 Update Python dependencies
  python/requirements.txt
  python/seldon_core/microservice.py
  python/setup.py
Labels: approved, size/S

#992 Misc 0.5 Issues
  doc/source/python/api/seldon_core.rst
  doc/source/reference/helm.md
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/templates/service_seldon-webhook-service.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
  python/seldon_core/wrapper.py
Labels: size/M

#993 Decode binData before sending it to Predict function
  python/seldon_core/flask_utils.py
  python/seldon_core/utils.py
  python/tests/test_model_microservice.py
Labels: ok-to-test, size/S

#1000 Fixed test by moving bytes conversion to utils
  python/seldon_core/flask_utils.py
  python/seldon_core/utils.py
  python/tests/test_combiner_microservice.py
Labels: approved, size/XS

#1006 Update spartakus to use apps/v1
  helm-charts/seldon-core-operator/templates/deployment_seldon-spartakus-volunteer.yaml
  operator/config/spartakus/spartakus-volunteer-deployment.yaml
Labels: approved, size/S

#1001 cicd demo fixes
  examples/cicd-argocd/jenkins/show-jenkins-logs
  examples/cicd-argocd/jenkins/start-jenkins
  examples/cicd-argocd/jenkins/values.yml
  examples/cicd-argocd/seldon-core/do-rest-request-LOCALHOST.py
  examples/cicd-argocd/seldon-core/port-forard-ambassador
  examples/cicd-argocd/seldon-core/port-forard-api-server
  examples/cicd-argocd/seldon-core/start-seldon-core
  examples/cicd-argocd/seldon-core/stop-seldon-core
  examples/cicd-argocd/watch-rollout-status
Labels: approved, size/M

#1010 Customized error raised in Python model needs be passed back to client
  .gitignore
  engine/src/main/java/io/seldon/engine/ExceptionControllerAdvice.java
  engine/src/main/java/io/seldon/engine/exception/APIException.java
  engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java
  engine/src/test/java/io/seldon/engine/ExceptionControllerAdviceTest.java
Labels: approved, ok-to-test, size/L

#1003 Update transitive dependencies
  engine/pom.xml
Labels: approved, lgtm, size/M

#1015 Added documentation on how to support Models with multiple input types in python wrapper
  doc/source/python/python_component.md
Labels: size/S

#1008 Move from logback to log4j2
  engine/pom.xml
Labels: size/S

#1022 Removed the hash as it was crashing the command when the pipeline was ran
  jenkins-x.yml
Labels: approved, size/XS
