Repository SeldonIO/seldon-core, pull requests merged in 2019-11, with the labels that each got.

#1019 Make GCS optional
  jenkins-x.yml
  python/Makefile
  python/seldon_core/imports_helper.py
  python/seldon_core/proto/tensorflow/core/framework/__init__.py
  python/seldon_core/storage.py
  python/seldon_core/tf_helper.py
  python/seldon_core/utils.py
  python/setup.py
  python/tests/test_model_microservice.py
  python/tests/test_s3_storage.py
  python/tests/test_storage.py
  python/tests/test_utils.py
  python/tests/utils.py
Labels: approved, ok-to-test, size/L

#1035 Updated precommit hook to align to the lint checker
  .pre-commit-config.yaml
  python/seldon_core/utils.py
  python/seldon_core/version.py
Labels: approved, size/XS

#1039 Add missing files to MANIFEST.in
  python/MANIFEST.in
Labels: approved, lgtm, size/XS

#1034 Evaluating and fixing intermittent test failing in e2e integration tests
  testing/scripts/seldon_utils.py
Labels: approved, size/XS

#1044 Fix dependabot config
  .dependabot/config.yml
Labels: approved, lgtm, size/XS

#1030 Allow modification of flask app configs
  doc/source/python/python_wrapping_docker.md
  python/seldon_core/wrapper.py
Labels: approved, lgtm, ok-to-test, size/S

#1068 Reduce some dependabot noise
  .dependabot/config.yml
Labels: approved, lgtm, size/XS

#1011 Updated GPU wrapper to uninstall TF without GPU
  wrappers/s2i/python-gpu/python-gpu/Dockerfile
Labels: approved, lgtm, size/XS

#1036 Seldon Components Usage Examples
  doc/source/examples/.input_transformer_spam.nblink.swp
  doc/source/examples/combiner_spam_model.nblink
  doc/source/examples/notebooks.rst
  doc/source/examples/transformer_spam_model.nblink
  examples/.DS_Store
  examples/combiners/.DS_Store
  examples/combiners/spam_clf_combiner/.gitignore
  examples/combiners/spam_clf_combiner/Combiner/.s2i/environment
  examples/combiners/spam_clf_combiner/Combiner/Combiner.py
  examples/combiners/spam_clf_combiner/Combiner/README.md
  examples/combiners/spam_clf_combiner/README.md
  examples/combiners/spam_clf_combiner/Translator/.s2i/environment
  examples/combiners/spam_clf_combiner/Translator/README.md
  examples/combiners/spam_clf_combiner/Translator/Translator.py
  examples/combiners/spam_clf_combiner/Translator/requirements.txt
  examples/combiners/spam_clf_combiner/deploy.yaml
  examples/combiners/spam_clf_combiner/graph_explained.png
  examples/combiners/spam_clf_combiner/keras-spam-classifier/.s2i/environment
  examples/combiners/spam_clf_combiner/keras-spam-classifier/KerasSpamClassifier.py
  examples/combiners/spam_clf_combiner/keras-spam-classifier/README.md
  examples/combiners/spam_clf_combiner/keras-spam-classifier/requirements.txt
  examples/combiners/spam_clf_combiner/seldon_inference_graph.png
  examples/combiners/spam_clf_combiner/skl-spam-classifier/.s2i/environment
  examples/combiners/spam_clf_combiner/skl-spam-classifier/README.md
  examples/combiners/spam_clf_combiner/skl-spam-classifier/SpamClassifier.py
  examples/combiners/spam_clf_combiner/skl-spam-classifier/requirements.txt
  examples/combiners/spam_clf_combiner/spam-classification.ipynb
  examples/input_tranformer/.gitignore
  examples/input_tranformer/README.md
  examples/input_tranformer/Spam Classification.ipynb
  examples/input_tranformer/Spam-Classifier/.s2i/environment
  examples/input_tranformer/Spam-Classifier/README.md
  examples/input_tranformer/Spam-Classifier/SpamClassifier.py
  examples/input_tranformer/Spam-Classifier/requirements.txt
  examples/input_tranformer/Translator/.s2i/environment
  examples/input_tranformer/Translator/README.md
  examples/input_tranformer/Translator/Translator.py
  examples/input_tranformer/Translator/requirements.txt
  examples/input_tranformer/deploy.yaml
  examples/input_tranformer/graph_explained.png
  examples/input_tranformer/seldon_inference_graph.png
  examples/input_tranformer/spam-classification.ipynb
Labels: approved, lgtm, ok-to-test, size/XXL

#1069 Temporary fix for kubernetes OpenAPISchema Issue
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/volumes.json
Labels: size/XL

#1077 Fix integration tests
  python/Makefile
  python/seldon_core/imports_helper.py
  python/seldon_core/version.py
  testing/scripts/dev_requirements.txt
Labels: approved, lgtm, ok-to-test, size/S

#1046 Update to explainers for Seldon Core
  examples/explainers/imagenet/imagenet_explainer.yaml
  notebooks/explainer_examples.ipynb
  notebooks/resources/imagenet_explainer.yaml
  notebooks/resources/imagenet_explainer_grpc.yaml
  notebooks/resources/income_explainer.yaml
  notebooks/resources/moviesentiment_explainer.yaml
  operator/api/v1alpha2/seldondeployment_types.go
  operator/controllers/seldondeployment_explainers.go
  python/seldon_core/seldon_client.py
Labels: approved, lgtm, size/XL

#1080 add update of operator version to release script
  release.py
Labels: approved, lgtm, size/L

#1093 986 build and push images
  ci_build_and_push_images.sh
  jenkins-x.yml
Labels: approved, size/L

#1101 Add GA Doc
  doc/source/index.rst
  doc/source/python/api/seldon_core.rst
Labels: approved, size/S

#1097 Remove old crd generation scripts
  util/custom-resource-definitions/.gitignore
  util/custom-resource-definitions/Makefile
  util/custom-resource-definitions/README.md
  util/custom-resource-definitions/crd.tpl.json
  util/custom-resource-definitions/create-crd.py
  util/custom-resource-definitions/expand-validation.py
Labels: approved, lgtm, size/XL

#1098 Avoid int-to-float conversions
  doc/source/graph/svcorch.md
  doc/source/python/python_component.md
  engine/pom.xml
  engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java
  engine/src/main/java/io/seldon/engine/pb/JsonFormat.java
  engine/src/main/java/io/seldon/engine/pb/ProtoBufUtils.java
  engine/src/main/java/io/seldon/engine/predictors/EnginePredictor.java
  engine/src/test/java/io/seldon/engine/pb/TestJsonFormat.java
  engine/src/test/java/io/seldon/engine/pb/TestPredictionProto.java
  engine/src/test/java/io/seldon/engine/pb/TestProtoBufUtils.java
Labels: approved, lgtm, size/L

#1107 don't use service that we chose not to create
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/XS

#1112 make initializer configurable via configmap
  helm-charts/seldon-core-operator/templates/configmap_seldon-config.yaml
  operator/config/manager/configmap.yaml
  operator/controllers/model_initializer_injector.go
Labels: approved, size/M

#1123 add mnt pvc path to container
  operator/controllers/model_initializer_injector.go
Labels: approved, size/S

#1126 Fix typo and make text a bit clearer
  doc/source/workflow/install.md
Labels: approved, lgtm, ok-to-test, size/XS

#1127 custom_metrics.md : Fix typo, make text clearer, fix JSON
  doc/source/analytics/custom_metrics.md
Labels: approved, lgtm, ok-to-test, size/S

#1132 Add integration test to verify non200 response handling
  testing/resources/s2i_python_model_non200.json
  testing/s2i/python/model/MyModelNon200Response.py
  testing/s2i/python/model/environment_rest_non200
  testing/scripts/test_s2i_python.py
Labels: approved, lgtm, ok-to-test, size/M

#1131 Python reference typo instead of java
  doc/source/java/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1074 Integrating Python GPU Wrapper into build scripts
  wrappers/s2i/python-gpu/python-gpu/Makefile
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/assemble
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/run
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/save-artifacts
  wrappers/s2i/python-gpu/python-gpu/s2i/bin/usage
  wrappers/s2i/python/Dockerfile.gpu.tmpl
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/build_scripts/build_all.sh
  wrappers/s2i/python/build_scripts/build_python_gpu.sh
  wrappers/s2i/python/build_scripts/push_all.sh
  wrappers/s2i/python/build_scripts/push_python_gpu.sh
Labels: approved, lgtm, size/L

#1130 Fix typo in logging.error
  engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1158 Fixing wrong types in Seldon Core user methods #1144
  python/seldon_core/user_model.py
Labels: approved, size/S

#1161 Adding overrides to remove step that creates tag for Jenkins X pipeline
  jenkins-x.yml
Labels: approved, size/S

#1163 fix master e2e tests
  .gitignore
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-sas-role.yaml
  operator/README.md
  operator/api/v1alpha2/seldondeployment_webhook.go
  operator/config/rbac/role_sas.yaml
  operator/controllers/seldondeployment_prepackaged_servers.go
  testing/scripts/README.md
Labels: approved, ok-to-test, size/M
