Repository SeldonIO/seldon-core, pull requests merged in 2019-09, with the labels that each got.

#843 Testing jx PR process
  jenkins-x.yml
  python/requirements.txt
  python/seldon_core/utils.py
  python/tests/test_model_microservice.py
  python/tests/test_utils.py
Labels: approved, size/M

#846 Added openshift to documentation
  doc/source/workflow/install.md
Labels: approved, size/XS

#853 ensure script checks for errors
  examples/centralised-logging/full-setup-existing-kubeflow.sh
Labels: approved, size/XS

#856 add branch release-0.4 to travis builds
  .travis.yml
Labels: approved, size/XS

#847 Standardisation of rest apis
  python/seldon_core/seldon_methods.py
  python/seldon_core/utils.py
  python/seldon_core/wrapper.py
  python/tests/test_combiner_microservice.py
  python/tests/test_model_microservice.py
  python/tests/test_router_microservice.py
  python/tests/test_transformer_microservice.py
Labels: approved, size/L

#855 Fix status code handling
  python/seldon_core/wrapper.py
  python/tests/test_model_microservice.py
Labels: approved, ok-to-test, size/S

#865 xgboost server version added in docs
  doc/source/servers/xgboost.md
Labels: approved, size/XS

#863 upgrade knative version
  examples/centralised-logging/kubeflow/knative-setup-existing-istio.sh
Labels: size/S

#866 Changed typo in redhat dockerfile
  engine/custom-images/Dockerfile-redhat
Labels: approved, size/XS

#867 Add initial Makefile for GPU Python Image
  wrappers/s2i/python-gpu/python-gpu/Dockerfile
  wrappers/s2i/python-gpu/python-gpu/Makefile
Labels: approved, size/S

#870 check for knative before installing
  examples/centralised-logging/full-setup-existing-kubeflow.sh
Labels: size/XS

#872 Updates to seldon request logging
  seldon-request-logger/app/app.py
Labels: approved, size/M

#873 Versioning seldon request logger and support for decoding binary strings
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
  seldon-request-logger/app/app.py
Labels: approved, size/S

#875 remove some empty lines
  readme.md
Labels: approved, size/XS

#879 Fix top nav bar colour and typo in README
  doc/source/_static/theme_overrides.css
  doc/source/graph/inference-graph.md
  doc/source/python/python_component.md
  doc/source/python/python_module.md
  doc/source/python/seldon_client.md
  doc/source/servers/overview.md
  doc/source/workflow/README.md
  doc/source/workflow/api-testing.md
  doc/source/workflow/troubleshooting.md
  readme.md
Labels: approved, ok-to-test, size/M

#881 Move image to doc source
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment.ipynb
Labels: approved, ok-to-test, size/XS

#886 Updating request-response logging structure
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
  seldon-request-logger/app/app.py
Labels: size/S
