Repository SeldonIO/seldon-core, pull requests merged in 2019-12, with the labels that each got.

#1160 Updated s2i Dockerfiles to build using requirements.txt
  wrappers/s2i/python-conda/Dockerfile
  wrappers/s2i/python-conda/requirements.txt
  wrappers/s2i/python/Dockerfile.gpu.tmpl
  wrappers/s2i/python/Dockerfile.tmpl
  wrappers/s2i/python/requirements.txt
  wrappers/s2i/python/requirements_gpu.txt
Labels: approved, size/S

#1159 #1153 Update install docs to Helm v3
  doc/source/workflow/install.md
Labels: approved, lgtm, size/S

#1184 note on pvc
  doc/source/servers/overview.md
Labels: approved, lgtm, size/XS

#1172 build operator image when running e2e locally
  testing/scripts/Makefile
  testing/scripts/kind_test_setup.sh
Labels: approved, ok-to-test, size/XS

#1185 note on configuring prepack server images
  doc/source/servers/overview.md
Labels: approved, lgtm, size/XS

#1175 Option to return proto OR dict for SeldonClient methods
  doc/source/python/seldon_client.md
  python/seldon_core/seldon_client.py
  python/tests/test_seldon_client.py
Labels: approved, size/L

#1192 Splitting request logger data for text types
  seldon-request-logger/app/app.py
  seldon-request-logger/app/test.sh
Labels: approved, lgtm, size/S

#1195 add sachin to owners
  OWNERS
Labels: approved, size/XS

#1193 update logger version
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
Labels: approved, lgtm, size/XS

#1201 Add PR build message to integration tests run
  jenkins-x-integration.yml
Labels: size/XS

#1182 Adding AWS Marketplace Install page to docs site
  doc/source/index.rst
  doc/source/reference/aws-mp-install.md
  doc/source/workflow/install.md
Labels: approved, size/M

#1202 Revert "1141 Create operator clientset"
  operator/api/v1alpha2/zz_generated.deepcopy.go
  operator/client/clientset/versioned/clientset.go
  operator/client/clientset/versioned/doc.go
  operator/client/clientset/versioned/fake/clientset_generated.go
  operator/client/clientset/versioned/fake/doc.go
  operator/client/clientset/versioned/fake/register.go
  operator/client/clientset/versioned/scheme/doc.go
  operator/client/clientset/versioned/scheme/register.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/fake_v1alpha2_client.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/generated_expansion.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/v1alpha2_client.go
  operator/go.mod
  operator/go.sum
  operator/hack/tools/tools.go
  operator/hack/update-codegen.sh
Labels: size/XL

#1186 1138 helm3 integration tests
  core-builder/Dockerfile
  core-builder/Makefile
  jenkins-x-integration.yml
  operator/go.mod
  operator/go.sum
  testing/scripts/Makefile
  testing/scripts/README.md
  testing/scripts/test_helm_charts_clusterwide.py
Labels: approved, lgtm, size/M

#1218 remove bits commited by mistake
  examples/SeldonDeployment-income-classifier.json
  examples/SeldonDeployment-loanclassifier.json
  examples/loan_classifier.yaml
  examples/s3example.yaml
  examples/simple_serving_images/canaryingandexplainers.txt
  examples/simple_serving_images/explainer.json
  examples/simple_serving_images/explainer.yaml
  examples/simple_serving_images/oldstylemodel.json
  examples/simple_serving_images/servingimagesexample.yaml
  examples/simple_serving_images/sklearniris.yaml
  examples/simple_serving_images/tfservingwithimage.yaml
  examples/simple_shadow.yaml
  examples/tripadvisorproblem.yaml
  examples/usercontainerissue.yaml
Labels: approved, ok-to-test, size/XL

#1220 move go wrapper to incubating
  incubating/wrappers/s2i/go/Dockerfile
  incubating/wrappers/s2i/go/Makefile
  incubating/wrappers/s2i/go/README.md
  incubating/wrappers/s2i/go/SeldonGoModel.ipynb
  incubating/wrappers/s2i/go/contract.json
  incubating/wrappers/s2i/go/generate_tensorflow_proto.sh
  incubating/wrappers/s2i/go/pkg/api/prediction.pb.go
  incubating/wrappers/s2i/go/resources/deployment_example.json
  incubating/wrappers/s2i/go/server.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/example/example.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/example/example_parser_configuration.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/example/feature.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/allocation_description.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/api_def.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/attr_value.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/cost_graph.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/device_attributes.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/function.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/graph.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/graph_transfer_info.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/iterator.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/kernel_def.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/log_memory.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/node_def.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/op_def.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/reader_base.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/remote_fused_graph_execute_info.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/resource_handle.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/step_stats.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/summary.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_description.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_slice.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/variable.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/versions.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/lib/core/error_codes.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/meta_graph.pb.go
  incubating/wrappers/s2i/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/saver.pb.go
Labels: approved, size/XS

#1221 Clientset for seldon operator
  operator/.gitignore
  operator/Makefile
  operator/api/v1alpha2/seldondeployment_types.go
  operator/client/clientset/versioned/clientset.go
  operator/client/clientset/versioned/doc.go
  operator/client/clientset/versioned/fake/clientset_generated.go
  operator/client/clientset/versioned/fake/doc.go
  operator/client/clientset/versioned/fake/register.go
  operator/client/clientset/versioned/scheme/doc.go
  operator/client/clientset/versioned/scheme/register.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/fake_seldondeployment.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/fake_v1alpha2_client.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/generated_expansion.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/seldondeployment.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/v1alpha2_client.go
  operator/client/informers/externalversions/core/interface.go
  operator/client/informers/externalversions/core/v1alpha2/interface.go
  operator/client/informers/externalversions/core/v1alpha2/seldondeployment.go
  operator/client/informers/externalversions/factory.go
  operator/client/informers/externalversions/generic.go
  operator/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  operator/client/listers/core/v1alpha2/expansion_generated.go
  operator/client/listers/core/v1alpha2/seldondeployment.go
  operator/go.mod
  operator/go.sum
  operator/hack/tools/README.md
  operator/hack/tools/go.mod
  operator/hack/tools/go.sum
  operator/hack/tools/tools.go
  operator/hack/update-codegen.sh
Labels: approved, lgtm, size/XXL

#1096 Allow meta tags to be provided in seldon_client
  python/seldon_core/seldon_client.py
  python/tests/test_seldon_client.py
Labels: approved, lgtm, size/M

#1227 Changed secondary unit port and provided an option to modify it
  incubating/wrappers/s2i/java/s2i/bin/run
Labels: approved, lgtm, size/M

#1228 Update centralised logging to work with k8s 1.16 and Helm 3
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
  helm-charts/seldon-core-analytics/templates/alertmanager-deployment.json
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  helm-charts/seldon-core-analytics/templates/node-exporter-daemonset.json
  helm-charts/seldon-core-analytics/templates/prometheus-deployment.json
Labels: approved, lgtm, size/M

#1231 Core builder update to 0.8
  Jenkinsfile
  Makefile
  core-builder/Dockerfile
  core-builder/Makefile
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x.yml
  release
  testing/scripts/kind_test_all.sh
Labels: approved, size/M

#1214 Fix defaulting by api-server differences
  operator/api/v1alpha2/seldondeployment_webhook.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: approved, lgtm, ok-to-test, size/L

#1240 Revert "Clientset for seldon operator"
  operator/.gitignore
  operator/Makefile
  operator/api/v1alpha2/seldondeployment_types.go
  operator/client/clientset/versioned/clientset.go
  operator/client/clientset/versioned/doc.go
  operator/client/clientset/versioned/fake/clientset_generated.go
  operator/client/clientset/versioned/fake/doc.go
  operator/client/clientset/versioned/fake/register.go
  operator/client/clientset/versioned/scheme/doc.go
  operator/client/clientset/versioned/scheme/register.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/doc.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/fake_seldondeployment.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/fake/fake_v1alpha2_client.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/generated_expansion.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/seldondeployment.go
  operator/client/clientset/versioned/typed/v1alpha2/internalversion/v1alpha2_client.go
  operator/client/informers/externalversions/core/interface.go
  operator/client/informers/externalversions/core/v1alpha2/interface.go
  operator/client/informers/externalversions/core/v1alpha2/seldondeployment.go
  operator/client/informers/externalversions/factory.go
  operator/client/informers/externalversions/generic.go
  operator/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  operator/client/listers/core/v1alpha2/expansion_generated.go
  operator/client/listers/core/v1alpha2/seldondeployment.go
  operator/go.mod
  operator/go.sum
  operator/hack/tools/README.md
  operator/hack/tools/go.mod
  operator/hack/tools/go.sum
  operator/hack/tools/tools.go
  operator/hack/update-codegen.sh
Labels: approved, size/XXL

#1244 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S

#1251 enforce tensorflow<2.0 in Tensorflow MNIST Model example
  examples/models/deep_mnist/deep_mnist.ipynb
  examples/models/deep_mnist/requirements.txt
Labels: approved, lgtm, ok-to-test, size/XS

#1252 Added rafal to OWNERS file
  OWNERS
Labels: approved, size/XS

#1253 Fix deployment ready bug
  operator/Makefile
  operator/controllers/seldondeployment_controller.go
  operator/go.mod
  operator/go.sum
Labels: size/M

#1255 remove duplication of seldon_core_setup.ipynb notebook, closes #1232
  examples/seldon_core_setup.ipynb
  notebooks/seldon_core_setup.ipynb
Labels: approved, lgtm, ok-to-test, size/L

#1229 Add versions v1 and v1alpha3 to CRD
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-single-model/templates/model.json
  helm-charts/seldon-single-model/values.yaml
  operator/PROJECT
  operator/api/v1/groupversion_info.go
  operator/api/v1/seldondeployment_types.go
  operator/api/v1/seldondeployment_webhook.go
  operator/api/v1/zz_generated.deepcopy.go
  operator/api/v1alpha3/groupversion_info.go
  operator/api/v1alpha3/seldondeployment_types.go
  operator/api/v1alpha3/seldondeployment_webhook.go
  operator/api/v1alpha3/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/webhook/manifests.yaml
  operator/controllers/ambassador.go
  operator/controllers/ambassador_test.go
  operator/controllers/controller_utils.go
  operator/controllers/noengine_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
  operator/controllers/suite_test.go
  operator/main.go
  operator/utils/utils.go
  testing/resources/graph7.json
  testing/resources/graph8.json
  testing/scripts/test_api_version.py
  testing/scripts/test_rolling_updates.py
Labels: approved, size/XXL

#1166 change annotation location
  doc/source/graph/annotations.md
Labels: approved, lgtm, ok-to-test, size/S

#1254 Specify seldon namespace in Tensorflow MNIST Model example
  examples/models/deep_mnist/deep_mnist.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#1259 Updated AWS Install to Helm 3
  doc/source/reference/aws-mp-install.md
Labels: approved, lgtm, size/M

#1267 Update MLflow notebook
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
Labels: approved, lgtm, size/M

#1266 fix "income classifier and Alibi anchor explainer" example
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment.ipynb
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier-explainer/requirements.txt
  examples/explainers/alibi_anchor_tabular/pipeline/pipeline_steps/loanclassifier/requirements.txt
  examples/explainers/alibi_anchor_tabular/requirements-dev.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#1280 Update Ambassador docs
  doc/source/reference/aws-mp-install.md
  doc/source/workflow/install.md
Labels: size/M

#1279 Added dependencies for pytest to avoid second level dependency breaking updates
  .gitignore
  python/requirements-dev.txt
  testing/scripts/Makefile
  testing/scripts/dev_requirements.txt
Labels: approved, size/S

#1264 Update JDK to 11.0.5 and remove curl
  engine/Dockerfile
  engine/Dockerfile.mvn
Labels: approved, size/XS

#1292 fix shadow idx issue
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/XS

#1296 Clean up duplicated code for types and webhooks
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/apis/machinelearning/v1/seldondeployment_webhook.go
  operator/apis/machinelearning/v1alpha2/seldondeployment_types.go
  operator/apis/machinelearning/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning/v1alpha2/zz_generated.deepcopy.go
  operator/apis/machinelearning/v1alpha3/seldondeployment_types.go
  operator/apis/machinelearning/v1alpha3/seldondeployment_webhook.go
  operator/apis/machinelearning/v1alpha3/zz_generated.deepcopy.go
  operator/controllers/seldondeployment_controller.go
Labels: approved, lgtm, size/XXL

#1287 update "income classifier and Alibi anchor explainer" to use "fetch_adult"
  examples/explainers/alibi_anchor_tabular/alibi_anchor_tabular_seldon_deployment.ipynb
Labels: approved, lgtm, ok-to-test, size/S

#1305 Add logger to graph types
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/apis/machinelearning/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd/patches/graph_children.yaml
Labels: approved, lgtm, size/L

#1300 Make seldon-core-operator work with helm2
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/helm/split_resources.py
Labels: approved, lgtm, size/S
