Repository SeldonIO/seldon-core, pull requests merged in 2020-12, with the labels that each got.

#2724 remove legacy Python2 components
  python/seldon_core/seldon_client.py
  python/seldon_core/user_model.py
  python/seldon_core/wrapper.py
  python/tests/resources/model-template-app/MyModel.py
  python/tests/resources/model-template-app2/mymodule/my_model.py
  python/tests/test_api_tester.py
  python/tests/test_combiner_microservice.py
  python/tests/test_metrics.py
  python/tests/test_microservice_tester.py
  python/tests/test_model_microservice.py
  python/tests/test_router_microservice.py
  python/tests/test_seldon_client.py
  python/tests/test_transformer_microservice.py
  python/tests/test_utils.py
Labels: size/M

#2725 add `--no-cache-dir` inside s2i wrappers
  wrappers/s2i/python/s2i/bin/assemble
Labels: approved, ok-to-test, size/XS

#2731 Release 1.5.0 Highlights
  doc/source/examples/keda.nblink
  doc/source/examples/notebooks.rst
  doc/source/python/api/seldon_core.rst
  doc/source/reference/release-1.5.0.md
  doc/source/reference/release-highlights.rst
Labels: approved, size/M

#2732 Update OWNERS
  OWNERS
Labels: size/XS

#2733 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS

#2709 Add security context to seldon-controller-manager deployment
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: approved, ok-to-test, size/XS

#2740 Updated charts and example model
  helm-charts/seldon-core-operator/values.yaml
  operator/config/samples/model.json
Labels: size/S

#2742 Updated helm chart docs
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-mab/README.md
  helm-charts/seldon-single-model/README.md
Labels: size/M

#2743 Update licenses
  executor/licenses/additional_license_info.csv
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  operator/licenses/additional_license_info.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
Labels: approved, size/XXL

#2752 Revert "Add security context to seldon-controller-manager deployment"
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: size/XS

#2753 Update Timeouts Notebook
  doc/source/examples/notebooks.rst
  doc/source/examples/timeouts.nblink
  examples/models/mean_classifier/MeanClassifier.py
  notebooks/resources/model_long_timeouts.json
  notebooks/resources/model_short_timeouts.json
  notebooks/timeouts.ipynb
Labels: size/XL

#2746 Update image make minio client compatible with ssl cert mismatch and add delete step
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/values.yaml
Labels: needs-ok-to-test, size/S

#2738 add python wrapper developer notes
  doc/source/python/developer_notes.md
  doc/source/python/index.rst
Labels: size/M

#2768 Added workaround for alibi explainer image build
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/alibiexplainer/proto/tensorflow/core/framework/types.proto
Labels: approved, size/XS

#2782 do not act on resources that have deletion timestamp set
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  operator/controllers/seldondeployment_controller.go
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/XL

#2700 WIP: Updating OpenAPI schema schema
  openapi/engine.oas3.json
Labels: do-not-merge/work-in-progress, size/L

#2809 Helm chart repo fix for integration tests
  examples/feedback/metrics-server/README.ipynb
  examples/keda/keda_prom_auto_scale.ipynb
  notebooks/resources/model_seldon_grpc.yaml
  notebooks/resources/model_seldon_rest.yaml
  testing/scripts/Makefile
Labels: approved, size/S

#2807 Fix send_feedback response wrongly wrapped as ndarray
  python/seldon_core/seldon_methods.py
Labels: approved, ok-to-test, size/XS
