Repository SeldonIO/seldon-core, pull requests merged in 2020-06, with the labels that each got.

#1848 Optionally allow manager to create CRD
  doc/source/reference/upgrading.md
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-webhook-role.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-webhook-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/configmap_seldon-config.yaml
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/templates/service_seldon-webhook-service.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/Dockerfile
  operator/Dockerfile.redhat
  operator/config/lite/patch_manager_env.yaml
  operator/config/lite/role_webhook.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
  operator/utils/k8s/crd.go
  operator/utils/k8s/crd_test.go
  operator/utils/k8s/initializer.go
  operator/utils/k8s/testdata/crd.yaml
  operator/utils/k8s/webhook_test.go
Labels: approved, size/XXL

#1908 fix the loop length from parmeters count
  incubating/wrappers/s2i/R/microservice.R
Labels: approved, needs-ok-to-test, size/XS

#1913 Updating auth example to use new seldon core operator
  examples/auth/README.md
  examples/auth/seldon-gateway.yaml
Labels: approved, size/S

#1909 Added checks to only build components in tests if have been modified
  testing/scripts/kind_test_all.sh
Labels: approved, size/M

#1906 Clean up and document charts
  .helmdocsignore
  doc/source/charts/seldon-core-operator.rst
  doc/source/charts/seldon-openvino.rst
  doc/source/charts/seldon-single-model.rst
  doc/source/graph/helm_charts.md
  helm-charts/Makefile
  helm-charts/README.md
  helm-charts/README.md.tpl
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-openvino/Chart.yaml
  helm-charts/seldon-openvino/README.md
  helm-charts/seldon-single-model/Chart.yaml
  helm-charts/seldon-single-model/README.md
  helm-charts/seldon-single-model/templates/model.json
  helm-charts/seldon-single-model/templates/seldondeployment.json
  helm-charts/seldon-single-model/values.yaml
Labels: approved, size/XL

#1915 Batch Processor Component
  doc/source/examples/argo_workflows_batch.nblink
  doc/source/examples/assets/kubeflow-pipeline.jpg
  doc/source/examples/assets/seldon-kubeflow-batch.gif
  doc/source/examples/kubeflow_pipelines_batch.nblink
  doc/source/examples/notebooks.rst
  doc/source/images/batch-processor.jpg
  doc/source/images/batch-workflow-manager-integration.jpg
  doc/source/images/batch-workflow-managers.jpg
  doc/source/images/stream-processing-knative.jpg
  doc/source/index.rst
  doc/source/python/api/seldon_core.rst
  doc/source/servers/batch.md
  doc/source/streaming/knative_eventing.md
  examples/batch/argo-workflows-batch/.gitignore
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/Chart.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/README.md
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/values.yaml
  examples/batch/kubeflow-pipelines-batch/.gitignore
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/batch/kubeflow-pipelines-batch/README.md
  examples/batch/kubeflow-pipelines-batch/assets/kubeflow-pipeline.jpg
  examples/batch/kubeflow-pipelines-batch/assets/seldon-batch-pipeline.py
  examples/batch/kubeflow-pipelines-batch/assets/seldon-batch-pipeline.py.tar.gz
  examples/batch/kubeflow-pipelines-batch/assets/seldon-kubeflow-batch.gif
  python/seldon_core/batch_processor.py
  python/setup.py
  testing/.gitignore
  testing/scripts/test_batch_processor.py
Labels: approved, size/XXL

#1930 Fix example in top level readme
  README.md
Labels: approved, lgtm, size/S

#1935 fix spacy example
  examples/models/sklearn_spacy_text/.gitignore
  examples/models/sklearn_spacy_text/Dockerfile
  examples/models/sklearn_spacy_text/ml_utils.py
  examples/models/sklearn_spacy_text/requirements.txt
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
Labels: approved, size/L

#1939 feat(blogs): Add a new blog post in Chinese
  doc/source/tutorials/blogs.rst
Labels: needs-ok-to-test, size/XS

#1940 Fix notebooks test
  examples/centralised-logging/README.md
  examples/centralised-logging/full-kind-setup.sh
  notebooks/helm_examples.ipynb
  notebooks/istio_example.ipynb
Labels: size/M

#1957 fixing minor typo on istio docs
  doc/source/ingress/istio.md
Labels: approved, ok-to-test, size/XS

#1959 Update cloudevents library to 1.2.0
  executor/go.mod
  executor/go.sum
Labels: approved, lgtm, size/S

#1956 Changed OpenAPI file permissions within image
  executor/Dockerfile
  executor/Dockerfile.redhat
  executor/Makefile
Labels: approved, size/S

#1920 updated histogram buckets
  executor/api/metric/client.go
  executor/api/metric/constants.go
  executor/api/metric/server.go
Labels: approved, ok-to-test, size/XS

#1954 Update licenses
  executor/licenses/README.md
  executor/licenses/additional_license_info.csv
  executor/licenses/dep.txt
  executor/licenses/dep_repo.manual.csv
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/licenses/README.md
  operator/licenses/additional_license_info.csv
  operator/licenses/dep.txt
  operator/licenses/dep_repo.manual.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
  python/licenses/license.txt
  python/licenses/license_info.csv
Labels: approved, size/XXL

#1900 Fix content-type behaviour in executor
  executor/api/client/client.go
  executor/api/grpc/seldon/client.go
  executor/api/grpc/tensorflow/client.go
  executor/api/grpc/tensorflow/server_test.go
  executor/api/rest/client.go
  executor/api/rest/server.go
  executor/api/rest/tensorflow.go
  executor/api/test/seldonmessage_test_client.go
  executor/samples/local/graph/Makefile
  executor/samples/local/graph/Model.py
  executor/samples/local/graph/README.md
  executor/samples/local/graph/Transformer.py
  executor/samples/local/graph/input.json
  executor/samples/local/graph/model_rest.yaml
Labels: approved, size/L

#1967 Fix annotations and labels in Helm chart
  helm-charts/seldon-single-model/templates/seldondeployment.json
Labels: approved, lgtm, size/XS

#1950 Fixes for tests
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/custom/model_custom_ambassador.json
  examples/istio/canary_update/canary.ipynb
  examples/models/custom_metrics/customMetrics.ipynb
  examples/models/custom_metrics/get-metrics.sh
  examples/models/metadata/graph-metadata/combiner.yaml
  examples/models/metadata/graph-metadata/input-transformer.yaml
  examples/models/metadata/graph-metadata/output-transformer.yaml
  examples/models/metadata/graph-metadata/router.yaml
  examples/models/metadata/graph-metadata/single.yaml
  examples/models/metadata/graph-metadata/two-levels.yaml
  examples/models/metadata/graph_metadata.ipynb
  examples/models/metrics/metrics.ipynb
  notebooks/convert.tpl
  notebooks/istio_example.ipynb
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_batch_processor.py
  testing/scripts/test_notebooks.py
  testing/scripts/test_rolling_updates.py
Labels: size/XL

#1971 Update upgrading docs
  doc/source/reference/upgrading.md
Labels: size/XS

#1978 Updating master for v1.2.1-rc
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/combiners/spam_clf_combiner/spam-classification.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/input_tranformer/spam-classification.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/L

#1979 Updating master for v1.2.1-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/combiners/spam_clf_combiner/spam-classification.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/input_tranformer/spam-classification.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/L

#1984 Add executor to dependabot
  .dependabot/config.yml
Labels: approved, lgtm, size/S

#2002 Update requirements.txt and readme file for KerasSpamClassifier
  examples/combiners/spam_clf_combiner/keras-spam-classifier/README.md
  examples/combiners/spam_clf_combiner/keras-spam-classifier/requirements.txt
Labels: approved, needs-ok-to-test, size/XS

#1981 Switch on executor enabled for service ports
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/S

#1996 Redhat v1.2.0
  CHANGELOG.md
  doc/source/reference/images.md
  operator/seldon-operator/Makefile
  operator/seldon-operator/bundle/certified/1.2.0/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/bundle/certified/1.2.0/seldon-operator.v1.2.0.clusterserviceversion.yaml
  operator/seldon-operator/bundle/certified/seldon-operator.package.yaml
  operator/seldon-operator/deploy/cluster_role.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.0/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.0/seldon-operator.v1.2.0.clusterserviceversion.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/seldon-operator.package.yaml
  operator/seldon-operator/deploy/operator.yaml
  operator/seldon-operator/deploy/role.yaml
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
  python/seldon_core/proto/tensorflow/core/framework/resource_handle_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_shape_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/types_pb2.py
Labels: approved, size/XXL

#2050 fix notebook server_examples to not fail on MLFlow server
  notebooks/server_examples.ipynb
Labels: size/S

#2019 volume mount names upgrade fix
  examples/centralised-logging/seldon-request-logger-k8s.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/controllers/seldondeployment_engine.go
  testing/scripts/seldon_e2e_utils.py
Labels: size/S

#2010 Use correct YAML package
  examples/pachyderm/iris-trainer/requirements.txt
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/requirements.txt
  python/setup.py
Labels: approved, do-not-merge/hold, lgtm, size/L

#2052 upgrading to 1.2.1
  doc/source/reference/upgrading.md
Labels: size/XS
