Repository SeldonIO/seldon-core, pull requests merged in 2020-09, with the labels that each got.

#2341 re-add ContentType to combiner payload
  executor/api/rest/utils.go
Labels: size/XS

#2344 Remove test dependencies from setup.py
  python/setup.cfg
  python/setup.py
Labels: approved, size/XS

#2359 Timeseries-algorithm-2
  examples/models/statsmodels/statsmodels.ipynb
Labels: needs-ok-to-test, size/S

#2363 Add TreeShap explainer
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/alibiexplainer/explainer.py
  components/alibi-explain-server/alibiexplainer/parser.py
  components/alibi-explain-server/alibiexplainer/tree_shap.py
  components/alibi-explain-server/setup.py
  components/alibi-explain-server/tests/test_tree_shap.py
  notebooks/explainer_examples.ipynb
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
Labels: approved, size/L

#2178 assaf-java-s2i-update
  incubating/wrappers/s2i/java/Dockerfile.build
  incubating/wrappers/s2i/java/Dockerfile.runtime
  incubating/wrappers/s2i/java/bin/build.sh
Labels: approved, needs-ok-to-test, size/L

#2369 Spelling update
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#2366 2258 update kubeflow example to v1.0.0 of kubeflow (and standalone kubeflow pipelines)
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/batch/kubeflow-pipelines-batch/README.md
  examples/kubeflow/README.md
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/kubeflow/pipeline/pipeline_steps/clean_text/Transformer.py
  examples/kubeflow/pipeline/pipeline_steps/clean_text/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/clean_text/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/data_downloader/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/lr_text_classifier/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/Dockerfile
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/pipeline_step.py
  examples/kubeflow/pipeline/pipeline_steps/spacy_tokenize/requirements.txt
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/build_image.sh
  examples/kubeflow/pipeline/pipeline_steps/tfidf_vectorizer/requirements.txt
  examples/kubeflow/requirements-dev.txt
  examples/kubeflow/train_pipeline/nlp_pipeline.py
  examples/kubeflow/train_pipeline/nlp_pipeline.py.tar.gz
Labels: size/XXL

#2377 Another Inreference -> inference change
  doc/source/index.rst
Labels: needs-ok-to-test, size/XS

#2380 Update k8s version check and add force override to helm
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/helm/split_resources.py
Labels: approved, size/M

#2368 Fix failed status on conflict
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/S

#2280 Expose more boolean Flask Configurations via `FLASK_` prefix
  doc/source/python/python_wrapping_docker.md
  python/seldon_core/wrapper.py
Labels: approved, ok-to-test, size/M

#2384 Update docs concerning default image user id
  doc/source/graph/inference-graph.md
Labels: approved, size/M

#2381 Add Alibi notebook references to explainers notebook
  notebooks/explainer_examples.ipynb
Labels: approved, size/M

#2402 slower scrape
  helm-charts/seldon-core-analytics/files/prometheus/prometheus-config.yaml
  helm-charts/seldon-core-analytics/values.yaml
Labels: approved, size/M

#2337 add FILTER_METRICS_ACCESS_LOGS flag that allows to silence metrics ac…
  python/seldon_core/microservice.py
Labels: approved, size/S

#2409 improve integration tests stability
  testing/scripts/Makefile
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/S

#2323 Update distributed-tracing.md
  doc/source/graph/distributed-tracing.md
  examples/models/tracing/tracing.ipynb
Labels: approved, ok-to-test, size/XS

#2308 correct file extention to match files
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-rules-configmap.yaml
Labels: approved, ok-to-test, size/XS

#2412 Update MLflow in MLFLOW_SERVER
  .gitignore
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
  servers/mlflowserver/mlflowserver/MLFlowServer.py
  servers/mlflowserver/mlflowserver/requirements.txt
Labels: approved, size/M

#2365 Revert multiplexing in the Executor
  executor/cmd/executor/main.go
  executor/go.sum
  executor/samples/local/logger/Makefile
  executor/samples/local/metrics/Makefile
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_engine_test.go
  operator/go.sum
  testing/resources/metadata_modelmetadata_grpc.yaml
Labels: approved, size/L

#2432 Fix failing TestPrepack.test_text_alibi_explainer test
  components/alibi-explain-server/alibiexplainer/__main__.py
  testing/resources/movies-text-explainer.yaml
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/M

#2399 Updated pinned versions of prepackaged servers
  components/routers/case_study/models/xgb_model/requirements.txt
  doc/source/servers/sklearn.md
  doc/source/servers/xgboost.md
  servers/sklearnserver/sklearnserver/requirements.txt
Labels: size/S

#2435 Update seldon-single-model
  helm-charts/seldon-single-model/templates/seldondeployment.json
  helm-charts/seldon-single-model/values.yaml
Labels: size/S

#2190 Add release notes template
  release-notes/Makefile
  release-notes/release-notes-1.2.2-dev.md
  release-notes/release-notes.gotmpl
Labels: size/M

#2413 Dettach duplicated signal handler from workers
  python/seldon_core/app.py
  python/seldon_core/microservice.py
Labels: approved, size/M

#2449 Fix image Jenkinx X build failures
  jenkins-x.yml
Labels: approved, size/S

#2415 Add -2 as option for route abort
  doc/source/analytics/routers.md
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
Labels: size/S

#2414 Disallow 2 shadows
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
Labels: size/M

#2345 Allow terminationGracePeriodSeconds to be overridden
  notebooks/resources/model_terminationgraceperiod.yaml
  operator/controllers/seldondeployment_controller.go
Labels: size/S

#2343 Remove tf binary from args when creating image for tfserving
  notebooks/server_examples.ipynb
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: approved, do-not-merge/hold, size/XL

#2456 Removed broken links
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
Labels: approved, size/XS

#2457 Ensure updated pygments installed
  doc/requirements_docs.txt
Labels: size/XS

#2448 Add SSL listener back in after removal by multiplexing reversion
  executor/cmd/executor/main.go
  executor/go.mod
Labels: approved, size/M

#2376 allow extra custom field in model metadata
  doc/source/reference/apis/metadata.md
  examples/models/metadata/example-grpc.yaml
  examples/models/metadata/metadata.ipynb
  examples/models/metadata/metadata_grpc.ipynb
  examples/models/metadata/model-metadata/environ-metadata.yaml
  examples/models/metadata/model-metadata/init-metadata.yaml
  examples/models/metadata/models/generic-node/Makefile
  examples/models/metadata/models/init-metadata/Makefile
  examples/models/metadata/models/init-metadata/Model.py
  executor/Makefile
  executor/api/grpc/seldon/client.go
  executor/api/grpc/seldon/proto/prediction.pb.go
  executor/api/grpc/seldon/server.go
  executor/api/payload/model_metadata.go
  executor/predictor/metadata_test.go
  executor/proto/prediction.proto
  proto/prediction.proto
  python/seldon_core/metadata.py
  python/seldon_core/proto/prediction.proto
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
  python/seldon_core/proto/prediction_pb2_grpc.py
  python/seldon_core/proto/tensorflow/core/framework/resource_handle_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_shape_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/types_pb2.py
  python/tests/test_metadata.py
  python/tests/test_model_microservice.py
  testing/resources/metadata_manifestmetadata_rest.yaml
  testing/s2i/python-features/metadata/ModelMetadata.py
  testing/scripts/test_seldon_metadata.py
Labels: size/XXL

#2373 change to 1.3.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/statsmodels/statsmodels.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  release.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/L

#2470 document wrapper CLI and environ flags
  doc/source/python/python_server.md
Labels: approved, size/S

#2023 V2 Dataplane in Executor/Operator + Triton Server
  doc/source/examples/digit.png
  doc/source/examples/notebooks.rst
  doc/source/examples/nvidia_mnist.nblink
  doc/source/examples/tensorrt.nblink
  doc/source/graph/protocols.md
  doc/source/index.rst
  doc/source/python/api/seldon_core.proto.rst
  doc/source/python/api/seldon_core.rst
  doc/source/servers/triton.md
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/nvidia-mnist/.s2i/environment
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/MnistTransformer.py
  examples/models/nvidia-mnist/fetch-model.sh
  examples/models/nvidia-mnist/nvidia-mnist/Chart.yaml
  examples/models/nvidia-mnist/nvidia-mnist/templates/mnist_nvidia_deployment.json
  examples/models/nvidia-mnist/nvidia-mnist/values.yaml
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/nvidia-mnist/tensorrt_mnist/config.pbtxt
  examples/models/nvidia-mnist/tensorrt_mnist/mnist_labels.txt
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/tensorrt/.gitignore
  examples/models/tensorrt/digit.png
  examples/models/tensorrt/requirements.txt
  examples/models/tensorrt/triton_tensorrt.ipynb
  executor/.gitignore
  executor/Makefile
  executor/api/constants.go
  executor/api/grpc/kfserving/client.go
  executor/api/grpc/kfserving/inference/grpc_service.pb.go
  executor/api/grpc/kfserving/inference/grpc_service.proto
  executor/api/grpc/kfserving/inference/model_config.pb.go
  executor/api/grpc/kfserving/inference/model_config.proto
  executor/api/grpc/kfserving/server.go
  executor/api/grpc/tensorflow/client.go
  executor/api/rest/client.go
  executor/api/rest/kfserving.go
  executor/api/rest/server.go
  executor/cmd/executor/main.go
  executor/go.sum
  executor/samples/local/graph/Makefile
  executor/samples/local/kfserving/.gitignore
  executor/samples/local/kfserving/Makefile
  executor/samples/local/kfserving/model_rest.yaml
  executor/samples/local/metadata/Makefile
  executor/samples/local/tracing/Makefile
  helm-charts/seldon-core-operator/values.yaml
  notebooks/protocol_examples.ipynb
  notebooks/resources/.gitignore
  operator/apis/machinelearning.seldon.io/v1/prepack.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
  operator/config/manager/configmap.yaml
  operator/constants/constants.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
  operator/controllers/suite_test.go
  servers/triton/samples/README.md
  servers/triton/samples/simple.yaml
Labels: size/XXL

#2472 revert change to retention period - leave default and let user override
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/XS

#2482 Add mesa GL to Dockerfile for Alibi Detect Server
  components/alibi-detect-server/Dockerfile
Labels: size/XS

#2496 Update licenses
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/M

#2478 print tfproxy exit value in ci_build_and_push_images script
  ci_build_and_push_images.sh
Labels: approved, size/XS

#2500 Add new Python licenses
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: approved, size/XXL

#2487 Update sklearn_spacy_text_classifier_example.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
Labels: approved, ok-to-test, size/XS

#2501 Added Kafka Protocol Example with Sklearn Spacy NLP
  doc/source/examples/kafka_spacy_sklearn.nblink
  doc/source/examples/notebooks.rst
  examples/kafka/sklearn_spacy/.gitignore
  examples/kafka/sklearn_spacy/README.ipynb
  examples/kafka/sklearn_spacy/kafka-cluster-config.yaml
  examples/kafka/sklearn_spacy/sdep_reddit_kafka.yaml
  examples/kafka/sklearn_spacy/topics.yaml
  examples/models/sklearn_spacy_text/README.md
  examples/models/sklearn_spacy_text/requirements.txt
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example_files/sklearn_spacy_text_classifier_example_5_1.png
Labels: approved, ok-to-test, size/XXL
