Repository SeldonIO/seldon-core, pull requests merged in 2020-02, with the labels that each got.

#1377 Add operator tests to Jenkins X
  jenkins-x.yml
Labels: approved, lgtm, size/S

#1382 Import Java wrapper
  .gitignore
  incubating/wrappers/java/Makefile
  incubating/wrappers/java/README.md
  incubating/wrappers/java/pom.xml
  incubating/wrappers/java/src/main/config/application.properties
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/App.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/CombinerRestController.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/ModelRestController.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/RouterRestController.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/SeldonPredictionService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/TransformerRestController.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/config/AnnotationsConfig.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/config/AppConfig.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/config/CustomizationBean.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/exception/APIException.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/CombinerService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/GenericService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/ModelService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/OutputTransformerService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/RouterService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/SeldonGrpcServer.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/SeldonGrpcServerInitializer.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/grpc/TransformerService.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/pb/ProtoBufUtils.java
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/utils/H2OUtils.java
  incubating/wrappers/java/src/main/proto/.keep
  incubating/wrappers/java/src/main/resources/application.properties
  incubating/wrappers/java/src/test/java/io/seldon/wrapper/api/RestControllerTest.java
  incubating/wrappers/java/src/test/java/io/seldon/wrapper/api/TestPredictionService.java
  incubating/wrappers/java/src/test/java/io/seldon/wrapper/grpc/GrpcServiceTest.java
  incubating/wrappers/java/src/test/java/io/seldon/wrapper/util/TestUtils.java
  incubating/wrappers/java/src/test/resources/application.properties
  incubating/wrappers/java/src/test/resources/feedback.json
  incubating/wrappers/java/src/test/resources/request.json
Labels: approved, lgtm, size/XXL

#1368 Update Storage.py and initialiser image
  python/seldon_core/storage.py
  python/seldon_core/utils.py
  python/tests/test_azure_storage.py
  python/tests/test_storage.py
  python/tests/test_utils.py
Labels: approved, lgtm, size/L

#1407 added knobs in operator helm chart to control manager resources
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#1415 Update Helm
  core-builder/Makefile
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x.yml
  testing/scripts/Makefile
  testing/scripts/conftest.py
  testing/scripts/dev_requirements.txt
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_rolling_updates.py
Labels: approved, lgtm, size/M

#1379 Add licenses to Python images
  python/Makefile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/requirements-dev.txt
  python/setup.cfg
  wrappers/s2i/python/Dockerfile.gpu.tmpl
  wrappers/s2i/python/Dockerfile.tmpl
  wrappers/s2i/python/Makefile
Labels: approved, size/XXL

#1425 Update seldon-core-s2i-python2 -> seldon-core-s2i-python3. Closes #593.
  doc/source/tutorials/openshift_s2i.md
  wrappers/s2i/python/s2i/bin/assemble
  wrappers/s2i/python/s2i/bin/usage
  wrappers/s2i/python/test_fbs/run_test_python2
Labels: approved, lgtm, size/S

#1422 Allow inputs in chain tensorflow protocol
  executor/api/rest/tensorflow.go
Labels: size/XS

#1428 Update resources to larger defaults for operator
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
Labels: approved, lgtm, size/S

#1414 Kubeflow manifest changes
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: approved, lgtm, size/M

#1369 new request logging
  .gitignore
  doc/source/analytics/analytics.md
  examples/centralised-logging/README.md
  examples/centralised-logging/elastic-kind.yaml
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
  examples/centralised-logging/kind_config.yaml
  examples/centralised-logging/kubeflow/knative-setup-existing-istio.sh
  examples/centralised-logging/kubeflow/seldon-analytics-kubeflow.yaml
  examples/centralised-logging/request-logging/README.md
  examples/centralised-logging/request-logging/full-kind-setup.sh
  examples/centralised-logging/request-logging/install_istio.sh
  examples/centralised-logging/request-logging/install_knative.sh
  examples/centralised-logging/request-logging/knative-setup-minikube.sh
  examples/centralised-logging/request-logging/seldon-request-logger-k8s.yaml
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
  examples/centralised-logging/request-logging/trigger.yaml
  executor/logger/dispatcher.go
  executor/logger/worker.go
  executor/main.go
  executor/predictor/predictor_process_test.go
  executor/samples/local/logger/Makefile
  helm-charts/seldon-single-model/templates/model.json
  helm-charts/seldon-single-model/values.yaml
  seldon-request-logger/Makefile
  seldon-request-logger/README.md
  seldon-request-logger/app/app.py
  seldon-request-logger/app/test.sh
  seldon-request-logger/requirements.txt
Labels: approved, lgtm, size/XXL

#1433 Don't specify version in Tox
  python/setup.cfg
Labels: approved, size/XS

#1365 allow route method to use metadata, closes #591
  python/seldon_core/seldon_methods.py
  python/seldon_core/user_model.py
  python/setup.cfg
  python/tests/test_router_microservice.py
Labels: approved, size/M

#1424 Replace print with logging.info in python/tests. Closes #1372
  python/tests/conftest.py
  python/tests/test_api_tester.py
  python/tests/test_application_exception_microservice.py
  python/tests/test_combiner_microservice.py
  python/tests/test_microservice.py
  python/tests/test_microservice_tester.py
  python/tests/test_model_microservice.py
  python/tests/test_router_microservice.py
  python/tests/test_seldon_client.py
  python/tests/test_transformer_microservice.py
  python/tests/test_utils.py
Labels: approved, size/L

#1342 Use print() function in both Python 2 and Python 3
  examples/models/h2o_example/H2OModel.py
  examples/models/sigmoid_predictor/SigmoidPredictor.py
  kafka/tests/src/read_predictions.py
  util/loadtester/scripts/predict_rest_locust.py
Labels: approved, ok-to-test, size/M

#1442 Undefined name: 'r' --> 'response'
  util/loadtester/scripts/mnist_grpc_locust.py
Labels: approved, lgtm, ok-to-test, size/XS

#1426 Check there is no downtime during operator updates
  testing/scripts/conftest.py
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_operator_updates.py
  testing/scripts/test_rolling_updates.py
Labels: approved, lgtm, size/L

#1406 Executor annotation support
  doc/source/graph/annotations.md
  doc/source/graph/model_rest_grpc_settings.md
  executor/Makefile
  executor/api/grpc/client.go
  executor/api/grpc/seldon/client.go
  executor/api/grpc/seldon/client_test.go
  executor/api/grpc/seldon/test/test_server.go
  executor/api/grpc/server.go
  executor/api/grpc/server_test.go
  executor/api/grpc/tensorflow/client.go
  executor/api/rest/client.go
  executor/api/rest/client_test.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/k8s/annotation.go
  executor/k8s/annotation_test.go
  executor/main.go
Labels: approved, size/L

#1441 Undefined name: import boto3 for lines 49 and 54
  examples/models/openvino_imagenet_ensemble/resources/model/Prediction.py
Labels: approved, ok-to-test, size/XS

#1457 improve reliability of req logging under high load
  seldon-request-logger/app/app.py
Labels: approved, size/S

#1443 Use flake8 to find syntax errors and undefined names
  jenkins-x-lint.yml
  python/Makefile
  python/requirements-dev.txt
  python/setup.cfg
Labels: approved, ok-to-test, size/S

#1445 Executor trace b3 propagate
  executor/api/tracing/trace.go
  executor/api/tracing/trace_test.go
  executor/main.go
Labels: approved, ok-to-test, size/L

#1459 Add k8s folder to executor build
  executor/Dockerfile
  executor/go.mod
  executor/logger/worker.go
Labels: approved, size/XS

#1468 fix release script for executor
  release.py
Labels: approved, size/S

#1470 fix seldon-core-operator image version
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
Labels: approved, size/XS

#1464 Integration tests tracing
  testing/resources/ambassador_values.yaml
  testing/resources/graph-tracing.json
  testing/resources/jaeger.yaml
  testing/resources/kind_config.yaml
  testing/scripts/Makefile
  testing/scripts/dev_requirements.txt
  testing/scripts/jaeger_utils.py
  testing/scripts/kind_config.yaml
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_tracing.py
Labels: approved, lgtm, size/L

#1473 Remove benchmark notebook
  examples/centralised-logging/README.md
  helm-charts/seldon-core-analytics/Chart.lock
  helm-charts/seldon-core-analytics/charts/prometheus-9.7.3.tgz
  helm-charts/seldon-core-analytics/charts/prometheus-9.7.4.tgz
  notebooks/benchmark_simple_model.ipynb
Labels: approved, lgtm, size/XL

#1486 update release wrapper and script to use maven repo as local user
  release
  release.py
Labels: approved, size/S

#1489 istio version that can install on k8s 1.16
  .gitignore
  examples/centralised-logging/request-logging/install_istio.sh
Labels: approved, size/XS
