Repository SeldonIO/seldon-core, pull requests merged in 2020-04, with the labels that each got.

#1649 remove wrapper metadata entry from 1.1 docs
  doc/source/python/python_component.md
Labels: approved, size/S

#1640 Remove jmx default settings for engine
  operator/controllers/seldondeployment_engine.go
Labels: approved, size/XS

#1636 Fix some readme links
  README.md
Labels: approved, size/XS

#1654 Add missing roadmap link
  README.md
Labels: size/XS

#1633 Add /scale subresource to CRD and replicas to various parts of CRD.
  .gitignore
  doc/source/examples/notebooks.rst
  doc/source/examples/scale.nblink
  doc/source/graph/autoscaling.md
  doc/source/graph/scaling.md
  doc/source/index.rst
  doc/source/python/api/seldon_core.proto.rst
  doc/source/python/api/seldon_core.rst
  doc/source/reference/release-0.2.7.md
  examples/models/autoscaling/autoscaling_example.ipynb
  examples/models/autoscaling/model_no_hpa.json
  examples/models/autoscaling/model_with_hpa.json
  examples/models/autoscaling/model_with_hpa.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  notebooks/scale.ipynb
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_types.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/replicas_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_engine.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  testing/scripts/Makefile
  testing/scripts/metrics.yaml
  testing/scripts/test_notebooks.py
Labels: approved, size/XXL

#1670 Fixed typo for version file path
  wrappers/s2i/python/Makefile
Labels: approved, size/XS

#1669 alibi-detect-server
  components/alibi-detect-server/.gitignore
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/README.md
  components/alibi-detect-server/adserver/__init__.py
  components/alibi-detect-server/adserver/__main__.py
  components/alibi-detect-server/adserver/ad_model.py
  components/alibi-detect-server/adserver/base/__init__.py
  components/alibi-detect-server/adserver/base/alibi_model.py
  components/alibi-detect-server/adserver/base/model.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/constants.py
  components/alibi-detect-server/adserver/numpy_encoder.py
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/adserver/protocols/__init__.py
  components/alibi-detect-server/adserver/protocols/request_handler.py
  components/alibi-detect-server/adserver/protocols/seldon_http.py
  components/alibi-detect-server/adserver/protocols/tensorflow_http.py
  components/alibi-detect-server/adserver/protocols/util.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_ad_model.py
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/adserver/tests/test_od_model.py
  components/alibi-detect-server/adserver/tests/test_server.py
  components/alibi-detect-server/input.json
  components/alibi-detect-server/requirements-dev.txt
  components/alibi-detect-server/requirements_server.txt
  components/alibi-detect-server/setup.py
Labels: approved, lgtm, size/XXL

#1666 fix headers level in metrics docs
  doc/source/analytics/analytics.md
Labels: approved, lgtm, size/S

#1679 Updating owners file
  OWNERS
Labels: approved, size/XS

#1496 Breaking Changes Doc for 1.1
  doc/source/analytics/analytics.md
  doc/source/reference/upgrading.md
  examples/ambassador/shadow/ambassador_shadow.ipynb
Labels: approved, size/M

#1684 Allow non-model specific predict for Tensorflow protocol
  doc/source/graph/protocols.md
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/api/test/seldonmessage_test_client.go
Labels: approved, lgtm, size/L

#1668 Explainer Gateway Fix for Istio, Ambassador and Python Client
  notebooks/explainer_examples.ipynb
  operator/constants/constants.go
  operator/controllers/ambassador.go
  operator/controllers/ambassador_test.go
  operator/controllers/seldondeployment_explainers.go
  python/seldon_core/seldon_client.py
  python/seldon_core/version.py
  python/tests/test_seldon_client.py
  testing/resources/movies-text-explainer.yaml
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/XL

#1694 fix release script to preserve comments in operator values yaml file
  release.py
Labels: approved, size/S

#1693 Leave timeouts as default
  doc/source/graph/annotations.md
  executor/api/rest/server.go
Labels: approved, size/S

#1700 add number dataType to logger
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/test.sh
Labels: approved, size/M

#1696 1695 istio client
  notebooks/explainer_examples.ipynb
  operator/controllers/seldondeployment_controller.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  python/seldon_core/seldon_client.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/XL

#1708 record names in req log entries
  components/seldon-request-logger/app/default_logger.py
Labels: approved, size/XS

#1681 fix(executor): Update proto compilation and package versions
  executor/Makefile
  executor/api/grpc/seldon/proto/prediction.pb.go
  executor/go.mod
  executor/go.sum
Labels: approved, ok-to-test, size/L

#1720 Document suppression of missing custom_metrics and custom_tags prior to 1.1
  doc/source/python/python_component.md
Labels: approved, ok-to-test, size/S

#1721 Fix typo in suppressing custom_tags missing message
  doc/source/python/python_component.md
Labels: needs-ok-to-test, size/XS

#1722 Release 1.1.0 highlights
  doc/source/graph/svcorch.md
  doc/source/reference/release-1.0.0.md
  doc/source/reference/release-1.1.0.md
  doc/source/reference/release-highlights.rst
Labels: approved, size/M

#1725 createResources also drives configmap
  helm-charts/seldon-core-operator/values.yaml
Labels: size/XS

#1738 add minimal example of deploying pachyderm-trained model
  examples/pachyderm/.gitignore
  examples/pachyderm/deploy.yaml
  examples/pachyderm/get-data.py
  examples/pachyderm/iris-trainer/Dockerfile
  examples/pachyderm/iris-trainer/Makefile
  examples/pachyderm/iris-trainer/requirements.txt
  examples/pachyderm/iris-trainer/train_iris.py
  examples/pachyderm/metadata.yaml
  examples/pachyderm/secret.yaml
  examples/pachyderm/sklearn_pachyderm.ipynb
  examples/pachyderm/train.json
Labels: approved, size/XXL

#1765 use namespace seldon-system for seldon-core-analytics
  examples/centralised-logging/full-setup-existing-kubeflow.sh
Labels: approved, size/XS
