Repository SeldonIO/seldon-core, pull requests merged in 2020-05, with the labels that each got.

#1744 Swagger UI with Embedded Seldon Deployment Values
  README.md
  doc/source/images/rest-openapi.jpg
  doc/source/workflow/quickstart.md
  doc/source/workflow/serving.md
  executor/.gitignore
  executor/Dockerfile
  executor/Makefile
  executor/api/rest/utils.go
  executor/api/rest/utils_test.go
  executor/main.go
  openapi/swagger-ui/index.html
  openapi/swagger-ui/index_bundled.html
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/L

#1795 WIP: Cherry picks for v1.1.0 patch fix
  examples/centralised-logging/fluentd-values.yaml
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: approved, do-not-merge/work-in-progress, lgtm, size/M

#1771 Add headers to curl request for executor sample
  executor/samples/local/metrics/Makefile
Labels: size/XS

#1807 Set user as default reviewer on Dependabot PRs
  .dependabot/config.yml
Labels: approved, size/XS

#1767 Fixed error of version not found when building python image
  wrappers/s2i/python/.gitignore
  wrappers/s2i/python/Dockerfile.gpu.tmpl
  wrappers/s2i/python/Dockerfile.local.tmpl
  wrappers/s2i/python/Dockerfile.tmpl
  wrappers/s2i/python/Makefile
Labels: approved, lgtm, size/S

#1810 Add versions to prerequisites
  testing/scripts/README.md
Labels: approved, size/S

#1819 Remove production warning for executor
  executor/README.md
Labels: approved, lgtm, size/XS

#1827 Add single test instructions to test scripts README
  .gitignore
  testing/scripts/README.md
Labels: approved, size/S

#1812 Use helm v3.2.0 in core-builder Dockerfile
  core-builder/Dockerfile
Labels: approved, size/XS

#1833 expose rest feedback endpoint in executor
  executor/api/metric/constants.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/api/test/seldonmessage_test_client.go
Labels: approved, lgtm, size/M

#1846 Update Storage.py to 0.3.0
  python/seldon_core/storage.py
Labels: approved, size/S

#1849 Documentation fixes on examples
  doc/source/servers/overview.md
  doc/source/servers/tensorflow.md
  doc/source/servers/xgboost.md
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_jsondata/IrisClassifier.py
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/RedditClassifier.py
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  notebooks/explainer_examples.ipynb
  notebooks/helm_examples.ipynb
  notebooks/istio_example.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/multiple_operators.ipynb
  notebooks/operator_upgrade.ipynb
  notebooks/protocol_examples.ipynb
  notebooks/resources/model_replicas.yaml
  notebooks/resources/model_scale.yaml
  notebooks/rolling_updates.ipynb
  notebooks/scale.ipynb
  notebooks/seldon_client.ipynb
  notebooks/server_examples.ipynb
  notebooks/timeouts.ipynb
Labels: approved, size/XXL

#1743 Fix broken and/or missing links in the documentation
  doc/source/R/README.md
  doc/source/analytics/routers.md
  doc/source/index.rst
  doc/source/ingress/ambassador.md
  doc/source/java/README.md
  doc/source/python/python_wrapping_docker.md
  doc/source/python/python_wrapping_s2i.md
  doc/source/python/seldon_client.md
  doc/source/servers/overview.md
  doc/source/tutorials/blogs.rst
  doc/source/workflow/install.md
  doc/source/workflow/quickstart.md
  doc/source/wrappers/language_wrappers.md
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/cicd/sig-mlops-jenkins-classic/README.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/istio/canary_update/canary.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/autoscaling/autoscaling_example.ipynb
  examples/models/h2o_mojo/h2o_model.ipynb
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/openvino/openvino-squeezenet.ipynb
  examples/models/openvino_imagenet_ensemble/openvino_imagenet_ensemble.ipynb
  examples/models/pvc-tfjob/pvc-tfjob.ipynb
  examples/models/sagemaker/sagemaker_seldon_scikit_iris_example.ipynb
  examples/models/tfserving-mnist/tfserving-mnist.ipynb
  examples/outliers/alibi-detect-combiner/notebook.ipynb
  notebooks/explainer_examples.ipynb
Labels: needs-ok-to-test, size/L

#1862 Add docs on using environment.yaml
  doc/source/python/python_wrapping_s2i.md
Labels: approved, size/M

#1843 Fix Ambassador rest/grpc timeout annotations in docs
  doc/source/ingress/ambassador.md
Labels: approved, size/XS

#1875 fix script pushing wrapper images to docker hub
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/build_scripts/push_all.sh
  wrappers/s2i/python/build_scripts/push_redhat.sh
Labels: approved, size/XS

#1863 Updating podinfo volume name to be seldon specific
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
Labels: approved, lgtm, size/XS

#1842 Add istio retries to docs
  doc/source/ingress/istio.md
Labels: size/S

#1868 factor out minio setup instructions into single notebook
  doc/source/examples/minio_setup.nblink
  examples/dvc/sklearn_dvc_minio.ipynb
  examples/minio/.gitignore
  examples/minio/minio.ipynb
  examples/minio_setup.ipynb
  examples/pachyderm/metadata.yaml
  examples/pachyderm/sklearn_pachyderm.ipynb
  notebooks/minio_setup.ipynb
Labels: approved, size/XL

#1889 fix name of minio_setup notebook in links
  examples/dvc/sklearn_dvc_minio.ipynb
  examples/minio/minio.ipynb
  examples/pachyderm/sklearn_pachyderm.ipynb
Labels: approved, size/S

#1834 Authentication and authorization for seldon core requests example
  examples/auth/README.md
  examples/auth/iris.yaml
  examples/auth/seldon-gateway.yaml
Labels: approved, size/L

#1893 make docs links relative
  doc/source/analytics/routers.md
  doc/source/examples/ambassador_circuit_breakers.nblink
  doc/source/examples/jenkins_classic.nblink
  doc/source/index.rst
  doc/source/python/api/seldon_core.proto.rst
  doc/source/python/api/seldon_core.rst
  doc/source/python/python_wrapping_docker.md
  doc/source/python/python_wrapping_s2i.md
  doc/source/python/seldon_client.md
  doc/source/reference/upgrading.md
  doc/source/workflow/quickstart.md
  examples/cicd/sig-mlops-jenkins-classic/Makefile
  examples/cicd/sig-mlops-jenkins-classic/README.md
  examples/cicd/sig-mlops-jenkins-classic/jenkins_classic.ipynb
Labels: approved, size/L

#1890 Routers not working with new Executor, fix #1876
  executor/api/util/utils.go
  executor/api/util/utils_test.go
Labels: approved, ok-to-test, size/M

#1897 increase failureThreshold in mlflow server sample
  servers/mlflowserver/samples/elasticnet_wine.yaml
Labels: approved, size/S
