Repository SeldonIO/seldon-core, pull requests merged in 2020-11, with the labels that each got.

#2558 Bump MLServer image to 0.1.1
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  notebooks/resources/iris-sklearn-v2.yaml
  notebooks/resources/iris-xgboost-v2.yaml
  notebooks/server_examples.ipynb
  testing/resources/iris-v2-inference-request.json
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/M

#2612 Fixed a typo (@trivial)
  README.md
Labels: needs-ok-to-test, size/XS

#2613 [Docs] Removed metadata from incubating as its graduated feature
  doc/source/index.rst
Labels: size/XS

#2619 Parameterize mc image and fix access_key/secret_key
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/values.yaml
Labels: ok-to-test, size/S

#2608 Update Operator and Executor Licenses
  executor/licenses/additional_license_info.csv
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/licenses/additional_license_info.csv
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
Labels: approved, size/XXL

#2627 Use UTF-8 code for check mark
  doc/source/graph/protocols.md
Labels: size/XS

#2630 Batch race condition fix
  python/seldon_core/batch_processor.py
Labels: size/M

#2626 Update Alibi-Detect wrapper and drift and outlier examples
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/setup.py
  components/drift-detection/cifar10/.gitignore
  components/drift-detection/cifar10/cifar10.yaml
  components/drift-detection/cifar10/cifar10_drift.ipynb
  components/drift-detection/cifar10/cifar10cd.yaml
  components/drift-detection/cifar10/message-dumper.yaml
  components/drift-detection/cifar10/trigger.yaml
  components/outlier-detection/cifar10/.gitignore
  components/outlier-detection/cifar10/cifar10.yaml
  components/outlier-detection/cifar10/cifar10_outlier.ipynb
  components/outlier-detection/cifar10/cifar10od.yaml
  components/outlier-detection/cifar10/message-dumper.yaml
  components/outlier-detection/cifar10/trigger.yaml
Labels: approved, size/XXL

#2635 Fix typo in reply url in outlier example
  components/outlier-detection/cifar10/cifar10_outlier.ipynb
Labels: size/XS

#2587 Add requestPath metadata on Python Wrapper
  python/seldon_core/utils.py
  python/tests/test_model_microservice.py
Labels: approved, size/L

#2636 Update workflow to work on Istio enabled namespace
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
Labels: approved, ok-to-test, size/S

#2655 Fix MLflow and TFServing images build
  ci_build_and_push_images.sh
  servers/mlflowserver/Makefile
Labels: approved, size/XS

#2653 WIP: add feedback to batch processor
  python/seldon_core/batch_processor.py
  python/seldon_core/seldon_client.py
Labels: approved, do-not-merge/work-in-progress, size/L

#2615 Upgrade to use KEDA v2.0 GA version in the demo
  examples/keda/keda_prom_auto_scale.ipynb
Labels: approved, ok-to-test, size/XS

#2650 Add retries for V2 protocol tests
  components/alibi-detect-server/adserver/od_model.py
  testing/scripts/e2e_utils/v2_protocol.py
Labels: approved, size/S

#2672 Alibi detect enhancements (Expose metrics with 0 value and include seldon_deployment_namespace tag to metric)
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_cm_model.py
  python/seldon_core/metrics.py
Labels: size/M

#2675 update minio setup
  notebooks/minio_setup.ipynb
Labels: approved, ok-to-test, size/XS

#2674 use service account for argo example
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
Labels: approved, size/L

#2671 Fix tensorflow prediction from explainer
  components/alibi-explain-server/alibiexplainer/explainer.py
  components/alibi-explain-server/tests/test_anchor_tabular.py
  testing/scripts/test_notebooks.py
Labels: approved, size/S

#2678 Updated alibi detect to 0.4.3
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/setup.py
  components/drift-detection/cifar10/cifar10_drift.ipynb
Labels: lgtm, size/M

#2684 Update testing script for KEDA v2.0 GA
  testing/scripts/Makefile
Labels: needs-ok-to-test, size/XS

#2687 Add Istio Troubleshoot for nonroot issue
  doc/source/ingress/istio.md
Labels: needs-ok-to-test, size/XS

#2695 Prepare 1.5.0 release updating docs
  doc/source/reference/images.md
Labels: size/M

#2698 Fix typo in ci build images script
  ci_build_and_push_images.sh
Labels: size/XS

#2699 fix batch logging
  python/seldon_core/batch_processor.py
  python/seldon_core/mlmd_utils.py
Labels: size/XS

#2701 Add back "seldon" gateway
  python/seldon_core/seldon_client.py
  python/tests/test_seldon_client.py
Labels: size/L

#2712 Rebuilt CRDs for 1.5.0 release
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
Labels: approved, size/S

#2708 Further release 1.6.0 version replace
  components/alibi-detect-server/Dockerfile
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  release.py
Labels: approved, size/L

#2697 Update ambassador doc for shadow deployment
  doc/source/ingress/ambassador.md
Labels: needs-ok-to-test, size/XS
