Repository SeldonIO/seldon-core, pull requests merged in 2020-07, with the labels that each got.

#2007 Update Ambassador ingress instructions to include edgectl install
  doc/source/ingress/ambassador.md
Labels: approved, ok-to-test, size/M

#2045 S2i wrapper/gpu local build
  wrappers/s2i/python/Dockerfile.gpu
  wrappers/s2i/python/requirements_gpu.txt
Labels: approved, size/S

#2071 remove incubating label regarding metadata on external API doc page
  doc/source/reference/apis/external-prediction.md
Labels: approved, size/XS

#2073 Update to version 1.2.2-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/combiners/spam_clf_combiner/spam-classification.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/input_tranformer/spam-classification.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: size/L

#2074 Redhat 1.2.1
  CHANGELOG.md
  doc/source/reference/images.md
  marketplaces/redhat/scan-images.py
  operator/seldon-operator/Makefile
  operator/seldon-operator/bundle/certified/1.2.1/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/bundle/certified/1.2.1/seldon-operator.v1.2.1.clusterserviceversion.yaml
  operator/seldon-operator/bundle/certified/seldon-operator.package.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.1/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.1/seldon-operator.v1.2.1.clusterserviceversion.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/seldon-operator.package.yaml
  operator/seldon-operator/deploy/operator.yaml
  operator/seldon-operator/testing/openshift/operator-group.yaml
  operator/seldon-operator/testing/openshift/operator-subscription-istio-110-certified.yaml
Labels: approved, size/XXL

#2054 extend seldon-single-model chart
  helm-charts/seldon-single-model/README.md
  helm-charts/seldon-single-model/templates/seldondeployment.json
  helm-charts/seldon-single-model/values.yaml
Labels: approved, size/S

#2047 Use production server by default
  doc/source/python/index.rst
  doc/source/python/python_component.md
  doc/source/python/python_server.md
  python/seldon_core/app.py
  python/seldon_core/microservice.py
  python/seldon_core/utils.py
  python/tests/test_utils.py
Labels: Python, size/XL

#2082 Move engine tests
  jenkins-x-engine.yml
  jenkins-x.yml
Labels: lgtm, ok-to-test, size/S

#2069 Address ambassador deprecation warnings
  components/routers/case_study/credit_card_default.ipynb
  doc/source/ingress/ambassador.md
  examples/cicd/cicd-argocd/seldon-core/start-seldon-core
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/Makefile
  examples/cicd/sig-mlops-seldon-jenkins-x/Makefile
  examples/models/gpu_tensorflow_deep_mnist/README.md
  notebooks/seldon_core_setup.ipynb
  testing/scripts/Makefile
Labels: size/L

#2086 Add PR template with release notes
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, size/M

#2100 run python fmt on master
  operator/helm/split_resources.py
  python/tests/test_metadata.py
  testing/scripts/e2e_utils/install.py
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_api_version.py
  testing/scripts/test_helm_charts_clusterwide.py
  testing/scripts/test_seldon_metadata.py
Labels: approved, lgtm, size/M

#2093 Operator/deps update - straightforward dependencies update
  operator/go.mod
  operator/go.sum
Labels: approved, size/L

#2104 Added fix to CI return value script
  ci_build_and_push_images.sh
Labels: size/XS

#2099 Executor/deps update - straightforward dependencies update
  executor/go.mod
  executor/go.sum
Labels: size/L

#1980 Enable production settings in loggers
  doc/source/analytics/log_level.md
  engine/src/main/resources/application.properties
  executor/api/grpc/tensorflow/client.go
  executor/api/rest/client.go
  executor/api/rest/server.go
  executor/api/util/utils.go
  executor/api/util/utils_test.go
  executor/go.mod
  executor/main.go
  operator/controllers/ambassador.go
  operator/controllers/controller_utils.go
  operator/controllers/model_initializer_injector.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/go.mod
  operator/main.go
  operator/utils/utils.go
  operator/utils/utils_test.go
  python/seldon_core/microservice.py
Labels: approved, lgtm, size/XL

#2117 operator: controller-runtime upgrade to v0.5.8
  operator/go.mod
  operator/go.sum
Labels: approved, size/M

#2106 Remove executor's dependency on k8s.io/client-go
  executor/api/client/seldondeployment_client.go
  executor/go.mod
  executor/main.go
Labels: size/M

#2129 Upgrade go dependencies: zap istio knative
  examples/istio/canary_update/mnist_v2.json
  executor/go.mod
  executor/go.sum
  operator/go.mod
  operator/go.sum
  python/licenses/license.txt
  python/licenses/license_info.csv
Labels: size/L

#2121 update version of operator in executor deps
  executor/.gitignore
  executor/Dockerfile
  executor/Dockerfile.redhat
  executor/Makefile
  executor/api/grpc/seldon/client_test.go
  executor/api/grpc/seldon/server.go
  executor/api/grpc/seldon/server_test.go
  executor/api/grpc/tensorflow/server.go
  executor/api/grpc/tensorflow/server_test.go
  executor/api/metric/client_test.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/go.mod
  executor/go.sum
  executor/operator
  executor/predictor/metadata_test.go
  executor/predictor/predictor_process.go
Labels: approved, lgtm, size/L

#1866 attach serviceAccountName to prepackaged deployment spec
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: approved, ok-to-test, size/XS

#1970 fixed noEngine
  operator/controllers/noengine_test.go
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/L

#2136 Fix Go license linting
  executor/Makefile
  executor/licenses/README.md
  executor/licenses/additional_license_info.csv
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/Makefile
  operator/licenses/README.md
  operator/licenses/additional_license_info.csv
  operator/licenses/dep.txt
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
  python/Makefile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: approved, size/XXL

#2147 Add missing license to executor
  executor/Makefile
  executor/go.mod
  executor/licenses/dep.txt
  operator/Makefile
Labels: approved, size/XS

#2137 Add operator to dependabot
  .dependabot/config.yml
Labels: approved, lgtm, size/XS

#1800 Set idletimeout
  executor/api/rest/server.go
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/XS

#2166 Update tracing dependencies
  python/requirements.txt
  python/setup.py
Labels: approved, lgtm, size/XS

#2177 Revert "Jenkins X add comment when pipeline finishes "
  ci/add-pr-build-comment
  ci/add-pr-build-comment-success
  core-builder/.gitignore
  core-builder/Dockerfile
  core-builder/Makefile
  jenkins-x-engine.yml
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x-notebooks.yml
  jenkins-x.yml
  python/Makefile
  python/tests/test_microservice.py
Labels: size/L

#2172 Routing disclaimer in executor
  doc/source/analytics/routers.md
  doc/source/graph/svcorch.md
Labels: size/S

#2167 WIP: update images reference doc for 1.2.2 release
  doc/source/reference/images.md
Labels: do-not-merge/work-in-progress, size/S

#2169 upgrade k8s.io and jaeger-client-go libraries
  executor/go.mod
  executor/go.sum
  operator/go.mod
  operator/go.sum
Labels: approved, size/M

#2171 Add mock classifier to related images for RedHat
  operator/config/manager/manager.yaml
  operator/seldon-operator/bundle/create_bundle.sh
Labels: approved, size/XS

#2131 fix(port): Update grpc executor target port
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/XS

#2159 Java Wrapper update
  incubating/wrappers/java/.DS_Store
  incubating/wrappers/java/pom.xml
Labels: approved, ok-to-test, size/M

#2170 Make Azure dependency optional
  doc/source/python/python_module.md
  python/seldon_core/imports_helper.py
  python/seldon_core/storage.py
  python/setup.cfg
  python/setup.py
  python/tests/test_azure_storage.py
  python/tests/test_storage.py
  python/tests/utils.py
Labels: approved, size/M

#2195 Fix drift predict
  components/alibi-detect-server/adserver/cd_model.py
Labels: approved, size/XS

#2196 Update licenses for Python package
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/L

#2193 add 2 args to seldon-core-microservice
  python/seldon_core/microservice.py
Labels: approved, lgtm, ok-to-test, size/S

#2205 Change Outlier call depending on type
  components/alibi-detect-server/adserver/od_model.py
Labels: approved, size/S

#2206 Upgrading 1.2.2
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/od_model.py
  executor/api/rest/server.go
  notebooks/explainer_examples.ipynb
  notebooks/protocol_examples.ipynb
  notebooks/resources/.gitignore
  notebooks/seldon_core_setup.ipynb
  operator/controllers/seldondeployment_explainers.go
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/seldon_core/microservice.py
Labels: size/XL

#2207 Fix Helm chart docs
  helm-charts/README.md.tpl
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-single-model/README.md
Labels: approved, lgtm, size/M

#2208 Release 1.2.2
  helm-charts/README.md.tpl
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-single-model/README.md
Labels: size/M

#2130 Add labels to deployments and improve label coverage of resources
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/controllers/labels.go
  operator/controllers/labels_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: approved, size/L

#2219 Update version to 1.3.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: size/L
