Repository SeldonIO/seldon-core, pull requests merged in 2020-03, with the labels that each got.

#1493 Update OWNERS
  OWNERS
Labels: approved, size/XS

#1494 Update OWNER_ALIASES
  OWNERS_ALIASES
Labels: approved, size/XS

#1383 Update amabassador retries and restructure tests for Ambassador
  doc/source/ingress/ambassador.md
  operator/controllers/ambassador.go
  operator/controllers/ambassador_test.go
Labels: approved, size/XL

#1492 updated path to openvino models
  examples/models/openvino_imagenet_ensemble/seldon_ov_predict_ensemble.json
  examples/models/openvino_imagenet_ensemble/seldon_ovms_ensemble.json
Labels: approved, ok-to-test, size/S

#1491 Always set variables for predictive unit and deployment identifiers [Fixes #1449]
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/S

#1481 tags backward compatibility in executor
  python/seldon_core/seldon_methods.py
  python/seldon_core/utils.py
  python/tests/test_combiner_microservice.py
  python/tests/test_microservice.py
  python/tests/test_model_microservice.py
  python/tests/test_router_microservice.py
  python/tests/test_transformer_microservice.py
  testing/resources/tags_combiner_grpc.json
  testing/resources/tags_combiner_rest.json
  testing/resources/tags_graph_grpc.json
  testing/resources/tags_graph_rest.json
  testing/resources/tags_single_grpc.json
  testing/resources/tags_single_rest.json
  testing/s2i/python-features/tags/Combiner.py
  testing/s2i/python-features/tags/ModelOne.py
  testing/s2i/python-features/tags/ModelTwo.py
  testing/s2i/python-features/tags/environment_combiner_grpc
  testing/s2i/python-features/tags/environment_combiner_rest
  testing/s2i/python-features/tags/environment_one_grpc
  testing/s2i/python-features/tags/environment_one_rest
  testing/s2i/python-features/tags/environment_two_grpc
  testing/s2i/python-features/tags/environment_two_rest
  testing/scripts/test_rolling_updates.py
  testing/scripts/test_tags.py
Labels: approved, lgtm, size/XL

#1487 fix operator helm file generator
  operator/helm/Makefile
Labels: approved, size/S

#1465 od logging
  examples/centralised-logging/README.md
  examples/centralised-logging/full-setup-existing-kubeflow.sh
  examples/centralised-logging/full-setup.sh
  examples/centralised-logging/request-logging/README.md
  examples/centralised-logging/request-logging/full-kind-setup.sh
  examples/centralised-logging/request-logging/seldon-request-logger-k8s.yaml
  examples/centralised-logging/request-logging/seldon-request-logger.yaml
  executor/logger/worker.go
  seldon-request-logger/Makefile
  seldon-request-logger/README.md
  seldon-request-logger/app/app.py
  seldon-request-logger/app/cifar_logger.py
  seldon-request-logger/app/cifardata.json
  seldon-request-logger/app/default_logger.py
  seldon-request-logger/app/log_helper.py
  seldon-request-logger/app/test.sh
  seldon-request-logger/app/test_cifar.sh
  seldon-request-logger/app/test_default.sh
  seldon-request-logger/cifar10.Dockerfile
  seldon-request-logger/cifareq.log
Labels: approved, size/XXL

#1522 Update Engine and top level makefiles
  Jenkinsfile
  Makefile.ci
  build-all-in-minikube
  build-all-private-repo
  engine/Dockerfile
  engine/Dockerfile.mvn
  engine/Makefile
  engine/Makefile.ci
  jenkins-x.yml
  push-all-private-repo
Labels: approved, lgtm, size/L

#1483 Update XGBoost
  helm-charts/seldon-core-operator/values.yaml
  servers/mlflowserver/Makefile
  servers/xgboostserver/Makefile
  servers/xgboostserver/test/xgboost_iris.ipynb
  servers/xgboostserver/xgboostserver/XGBoostServer.py
  servers/xgboostserver/xgboostserver/requirements.txt
Labels: approved, lgtm, size/L

#1488 Reduce flakiness on tracing tests
  testing/scripts/jaeger_utils.py
  testing/scripts/test_tracing.py
Labels: approved, lgtm, size/S

#1516 Added version to tfserving image
  helm-charts/seldon-core-operator/values.yaml
Labels: approved, size/XS

#1517 Added helmchart variable to operator to be able to set a default "global" request logging prefix
  executor/logger/constants.go
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/controllers/seldondeployment_engine.go
  operator/helm/split_resources.py
Labels: approved, size/L

#1536 Make copy of locals()
  python/seldon_core/seldon_client.py
Labels: approved, size/XS

#1534 HPA scaleTargetRef apiVersion should be consistent with Deployments
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/XS

#1535 add notebook test deps to integration tesets requirements file
  core-builder/.gitignore
  core-builder/Dockerfile
  core-builder/Makefile
  testing/scripts/Makefile
  testing/scripts/dev_requirements.txt
Labels: approved, size/S

#1497 Change explainer to pointer reference in api types
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/apis/machinelearning/v1/zz_generated.deepcopy.go
  operator/controllers/controller_utils.go
  operator/controllers/seldondeployment_explainers.go
Labels: approved, lgtm, size/S

#1446 Allow REST error payloads to be returned
  executor/api/rest/client.go
  executor/api/rest/client_test.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
Labels: approved, size/L

#1531 Added default env secret name for flexible definition of env variables
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
Labels: approved, size/M

#1553 Move protocol/transport CRD variables
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  notebooks/resources/fixed_v1.yaml
  notebooks/resources/fixed_v1_2podspecs.yaml
  notebooks/resources/fixed_v1_sep.yaml
  notebooks/resources/fixed_v2.yaml
  notebooks/resources/fixed_v2_2podspecs.yaml
  notebooks/resources/fixed_v2_sep.yaml
  notebooks/resources/model_seldon_grpc.yaml
  notebooks/resources/model_seldon_rest.yaml
  notebooks/resources/model_tfserving_grpc.yaml
  notebooks/resources/model_tfserving_rest.yaml
  operator/Makefile
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/apis/machinelearning/v1/seldondeployment_webhook.go
  operator/apis/machinelearning/v1/seldondeployment_webhook_test.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/manager/manager.yaml
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
  operator/helm/split_resources.py
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  servers/tfserving/samples/halfplustwo_rest.yaml
Labels: approved, lgtm, size/XXL

#1566 Fixed broken links and added missing docs
  README.md
  doc/source/examples/notebooks.rst
  doc/source/examples/outlier_if.nblink
  doc/source/examples/outlier_mb.nblink
  doc/source/examples/outlier_s2s.nblink
  doc/source/examples/outlier_vae.nblink
  doc/source/graph/distributed-tracing.md
  doc/source/index.rst
Labels: approved, lgtm, size/L

#1570 Add Events and fix State for SeldonDeployments
  doc/source/workflow/troubleshooting.md
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-role.yaml
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/config/rbac/role.yaml
  operator/constants/constants.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  testing/scripts/test_s2i_python.py
Labels: size/XL

#1578 Update seldon images doc to include missing and rearrange
  doc/source/graph/svcorch.md
  doc/source/reference/images.md
  operator/config/manager/configmap.yaml
Labels: approved, size/M

#1586 Added documentation page on local testing
  doc/source/index.rst
  doc/source/python/python_module.md
  doc/source/workflow/quickstart.md
  doc/source/workflow/serving.md
Labels: size/L

#1587 add missing entry in doc index (custom metrics)
  doc/source/index.rst
Labels: approved, size/XS

#1588 fix link to Prometheus docs in custom metrics documentation
  doc/source/analytics/custom_metrics.md
Labels: approved, size/XS

#1555 Add new labels to Services
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/controllers/labels.go
  operator/controllers/labels_test.go
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/L

#1591 hotfix race condition in metrics endpoint test
  python/tests/test_microservice.py
Labels: approved, size/S

#1604 Fix for empty explainers
  operator/controllers/ambassador_test.go
  operator/controllers/controller_utils.go
  operator/controllers/controller_utils_test.go
  operator/controllers/labels.go
  operator/controllers/labels_test.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
Labels: approved, lgtm, size/L

#1602 document SC 1.1 compatibility with different s2i wrappers
  doc/source/reference/upgrading.md
  incubating/wrappers/s2i/compatibility-tests/Makefile
  incubating/wrappers/s2i/compatibility-tests/Model.py
  incubating/wrappers/s2i/compatibility-tests/deploy-grpc.yaml
  incubating/wrappers/s2i/compatibility-tests/deploy-java-grpc.yaml
  incubating/wrappers/s2i/compatibility-tests/deploy-java-rest.yaml
  incubating/wrappers/s2i/compatibility-tests/deploy-rest.yaml
  incubating/wrappers/s2i/compatibility-tests/environment_grpc
  incubating/wrappers/s2i/compatibility-tests/environment_rest
Labels: approved, size/XXL

#1600 Fix labelling panic for prepackaged servers
  operator/apis/machinelearning/v1/seldondeployment_webhook.go
  operator/apis/machinelearning/v1/seldondeployment_webhook_test.go
  operator/controllers/labels.go
Labels: approved, size/M

#1585 Update explainer path for Ambassador
  notebooks/explainer_examples.ipynb
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/constants/constants.go
  operator/controllers/ambassador.go
  operator/controllers/ambassador_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_explainers.go
  python/seldon_core/seldon_client.py
Labels: approved, size/L

#1580 Ensure all labels and annotations added to created deployments
  notebooks/resources/model_with_labels.yaml
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
Labels: approved, lgtm, size/L

#1616 fix wrapper compatibility notes
  doc/source/reference/upgrading.md
Labels: approved, size/S

#1619 Added executor tests to CI
  jenkins-x.yml
Labels: approved, size/XS

#1573 Deployment name changes
  notebooks/resources/fixed_v1_2models.yaml
  notebooks/resources/fixed_v2_2models.yaml
  notebooks/resources/fixed_v2_new_name.yaml
  notebooks/rolling_updates.ipynb
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/apis/machinelearning/v1/seldondeployment_types_test.go
  operator/constants/constants.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  testing/scripts/test_notebooks.py
Labels: approved, size/XL

#1621 Fix typo in explainers.md
  doc/source/analytics/explainers.md
Labels: approved, ok-to-test, size/XS

#1624 Revert "Make inclusion of metrics in SeldonMessage configurable in 1.1"
  doc/source/python/python_component.md
  python/seldon_core/seldon_methods.py
  python/seldon_core/user_model.py
  python/tests/conftest.py
  python/tests/test_metrics.py
  testing/scripts/seldon_e2e_utils.py
Labels: size/L

#1629 Fix the base image name
  doc/source/wrappers/s2i.md
Labels: approved, ok-to-test, size/XS

#1623 Fix Prepackaged Server nil and update core examples
  doc/source/examples/keras_mnist.nblink
  doc/source/examples/notebooks.rst
  examples/ambassador/canary/ambassador_canary.ipynb
  examples/ambassador/custom/ambassador_custom.ipynb
  examples/ambassador/headers/ambassador_headers.ipynb
  examples/ambassador/shadow/ambassador_shadow.ipynb
  examples/combiners/.DS_Store
  examples/combiners/mnist_combiner/MnistCombiner.py
  examples/combiners/mnist_combiner/environment_grpc
  examples/combiners/mnist_combiner/environment_rest
  examples/combiners/mnist_combiner/mnist_combiner.ipynb
  examples/combiners/mnist_combiner/mnist_combiner.json
  examples/combiners/mnist_combiner/utils.py
  examples/combiners/mnist_combiner/visualizer.py
  examples/istio/canary_update/canary.ipynb
  examples/models/keras_mnist/.s2i/environment
  examples/models/keras_mnist/MnistClassifier.py
  examples/models/keras_mnist/contract.json
  examples/models/keras_mnist/keras_mnist.ipynb
  examples/models/keras_mnist/keras_mnist_deployment.json
  examples/models/keras_mnist/requirements.txt
  examples/models/keras_mnist/train_mnist.py
  examples/models/metrics/metrics.ipynb
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
  examples/models/openvino/openvino-squeezenet.ipynb
  examples/models/openvino_imagenet_ensemble/openvino_imagenet_ensemble.ipynb
  examples/models/payload_logging/payload_logging.ipynb
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris/sklearn_iris.py
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/tracing/tracing.ipynb
  examples/models/xss/xss-example.ipynb
  helm-charts/seldon-openvino/values.yaml
  notebooks/explainer_examples.ipynb
  notebooks/helm_examples.ipynb
  notebooks/istio_example.ipynb
  notebooks/max_grpc_msg_size.ipynb
  notebooks/multiple_operators.ipynb
  notebooks/protocol_examples.ipynb
  notebooks/resources/imagenet_explainer.yaml
  notebooks/resources/imagenet_explainer_grpc.yaml
  notebooks/resources/income_explainer.yaml
  notebooks/resources/moviesentiment_explainer.yaml
  notebooks/rolling_updates.ipynb
  notebooks/server_examples.ipynb
  notebooks/timeouts.ipynb
  operator/controllers/seldondeployment_prepackaged_servers.go
  testing/notebooks/helm_tests.ipynb
  testing/scripts/test_dev.ipynb
Labels: approved, size/XXL

#1618 Fix clean up of old virtual services
  examples/istio/canary_update/canary.ipynb
  notebooks/istio_example.ipynb
  notebooks/operator_upgrade.ipynb
  operator/constants/constants.go
  operator/controllers/cleaners.go
  operator/controllers/cleaners_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/go.mod
  testing/scripts/test_notebooks.py
Labels: size/XL

#1632 check for virtualservices before running clean up
  operator/controllers/seldondeployment_controller.go
Labels: size/XS

#1625 Make inclusion of metrics in SeldonMessage configurable in 1.1
  doc/source/python/python_component.md
  python/seldon_core/seldon_methods.py
  python/seldon_core/user_model.py
  python/tests/conftest.py
  python/tests/test_metrics.py
  testing/scripts/seldon_e2e_utils.py
Labels: approved, size/L

#1635 Add notes on missing mutating webhook
  doc/source/workflow/troubleshooting.md
Labels: approved, size/M

#1639 remove unused docs folder
  docs/autoscaling.md
  docs/developer/kubernetes-client.md
Labels: size/L

#1572 Basic support for Cloudevents with KNative Eventing Example
  examples/streaming/knative-eventing/README.ipynb
  examples/streaming/knative-eventing/README.md
  examples/streaming/knative-eventing/assets/event-display-deployment.yaml
  examples/streaming/knative-eventing/assets/event-display-trigger.yaml
  examples/streaming/knative-eventing/assets/seldon-knative-trigger.yaml
  examples/streaming/knative-eventing/assets/simple-iris-deployment.yaml
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  operator/apis/machinelearning/v1/seldondeployment_types.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/utils/utils.go
Labels: approved, size/XXL

#1643 remove crd chart
  helm-charts/seldon-core-crd/.helmignore
  helm-charts/seldon-core-crd/Chart.yaml
  helm-charts/seldon-core-crd/templates/NOTES.txt
  helm-charts/seldon-core-crd/templates/_hpa-spec-validation.tpl
  helm-charts/seldon-core-crd/templates/_object-meta-validation.tpl
  helm-charts/seldon-core-crd/templates/_pod-spec-validation.tpl
  helm-charts/seldon-core-crd/templates/seldon-deployment-crd.json
  helm-charts/seldon-core-crd/templates/spartakus-config-map.json
  helm-charts/seldon-core-crd/templates/spartakus-rbac.json
  helm-charts/seldon-core-crd/templates/spartakus-volunteer-deployment.json
  helm-charts/seldon-core-crd/values.yaml
Labels: approved, lgtm, size/XXL

#1641 update svc orch docs
  doc/source/graph/svcOrch1.png
  doc/source/graph/svcorch.md
Labels: approved, lgtm, size/M
