Repository SeldonIO/seldon-core, pull requests merged in 2020-10, with the labels that each got.

#2510 fix build_all_local.sh script to use correct gpu-related scripts
  wrappers/s2i/python/build_scripts/build_all_local.sh
Labels: approved, size/XS

#2516 remove reference to kafka chart
  helm-charts/Makefile
Labels: approved, size/XS

#2524 increase scrape interval to reduce disk usage
  helm-charts/seldon-core-analytics/files/prometheus/prometheus-config.yaml
Labels: approved, size/XS

#2527 fix integration test by adding the missing comma
  operator/config/manager/configmap.yaml
Labels: needs-ok-to-test, size/XS

#2451 Github actions added rebase command
  .github/workflows/rebase.yml
Labels: size/S

#2536 Fixed AD Server Dependencies and Added notebook integration test
  components/alibi-detect-server/setup.py
  doc/source/examples/feedback_reward_custom_metrics.nblink
  examples/feedback/metrics-server/README.ipynb
  examples/feedback/metrics-server/README.md
  examples/feedback/metrics-server/config/multiclass-deployment.yaml
  examples/feedback/reward-accuracy/README.md
  testing/scripts/test_notebooks.py
Labels: size/XXL

#2512 Add V2 examples for SKLearn and XGBoost
  doc/source/graph/protocols.md
  doc/source/index.rst
  doc/source/servers/sklearn.md
  doc/source/servers/xgboost.md
  notebooks/server_examples.ipynb
  testing/resources/iris-xgboost-v2.yaml
Labels: size/XL

#2548 fix links to metrics notebooks
  doc/source/analytics/analytics.md
Labels: size/XS

#2547 Add pidfile config for gunicorn
  doc/source/python/python_server.md
  operator/hack/create_graph_openapi_schema.py
  operator/hack/csv_hack.py
  operator/helm/split_resources.py
  python/Makefile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/seldon_core/microservice.py
Labels: ok-to-test, size/L

#2549 fix links in docs by re-adding .html suffix
  doc/source/R/README.md
  doc/source/R/r_wrapping_docker.md
  doc/source/analytics/analytics.md
  doc/source/analytics/cicd-mlops.md
  doc/source/analytics/drift_detection.md
  doc/source/analytics/explainers.md
  doc/source/analytics/kubeflow.md
  doc/source/examples/istio.md
  doc/source/index.rst
  doc/source/nodejs/README.md
  doc/source/python/python_component.md
  doc/source/python/python_module.md
  doc/source/python/python_wrapping_docker.md
  doc/source/python/python_wrapping_s2i.md
  doc/source/python/seldon_client.md
  doc/source/servers/overview.md
Labels: size/M

#2513 Fix image version bug to not overwrite non seldon images
  release.py
Labels: approved, size/S

#2515 feat(pdb): Add support for managing PDBs
  README.md
  doc/source/examples/notebooks.rst
  doc/source/graph/disruption-budgets.md
  doc/source/index.rst
  examples/models/disruption_budgets/model_with_patched_pdb.yaml
  examples/models/disruption_budgets/model_with_pdb.yaml
  examples/models/disruption_budgets/pdbs_example.ipynb
  examples/models/disruption_budgets/pdbs_example.py
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-role.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/rbac/role.yaml
  operator/constants/constants.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  testing/scripts/test_notebooks.py
Labels: ok-to-test, size/XXL

#2514 feat(defaults): Add default resources to engine/executor container
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/constants/constants.go
  operator/controllers/seldondeployment_engine.go
  operator/helm/split_resources.py
Labels: ok-to-test, size/L

#2560 image versions reference for next release
  doc/source/reference/images.md
Labels: size/M

#2561 Updated version file to 1.4.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/statsmodels/statsmodels.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/L

#2567 req logger to handle jsonData
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/test.sh
Labels: approved, size/XS

#2557 Extend drift detect server to expose metrics
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/setup.py
Labels: approved, lgtm, size/M

#2572 Adding prom annotations for feedback metrics server example
  examples/feedback/metrics-server/README.md
Labels: size/S

#2564 Fix protocols_example
  examples/models/custom_metrics/customMetrics.ipynb
  notebooks/protocol_examples.ipynb
Labels: size/S

#2571 Update to Alibi 0.5.5
  components/alibi-explain-server/.gitignore
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/alibiexplainer/kernel_shap.py
  components/alibi-explain-server/setup.py
  components/alibi-explain-server/tests/test_anchor_images.py
  components/alibi-explain-server/tests/test_kernel_shap.py
  components/alibi-explain-server/tests/test_tree_shap.py
  doc/source/analytics/explainers.md
  notebooks/explainer_examples.ipynb
Labels: approved, size/XL

#2565 Fix keda notebook testing
  examples/keda/keda_prom_auto_scale.ipynb
  examples/keda/model_with_keda_prom.yaml
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-role.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/rbac/role.yaml
  operator/controllers/seldondeployment_controller.go
  python/licenses/license.txt
  python/licenses/license_info.csv
  testing/scripts/Makefile
  testing/scripts/test_notebooks.py
Labels: ok-to-test, size/XXL

#2579 Update to 1.4.0-dev missing image version
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/M

#2583 Update to 1.5.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/statsmodels/statsmodels.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: size/L

#2544 Update microservice.R for supporting jsonData input in R
  incubating/wrappers/s2i/R/microservice.R
Labels: ok-to-test, size/M
