Repository SeldonIO/seldon-core, pull requests merged in 2020-08, with the labels that each got.

#2226 Openshift Operator 1.2.2
  doc/source/index.rst
  doc/source/ingress/openshift.md
  doc/source/workflow/install.md
  operator/seldon-operator/Makefile
  operator/seldon-operator/bundle/certified/1.2.2/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/bundle/certified/1.2.2/seldon-operator.v1.2.2.clusterserviceversion.yaml
  operator/seldon-operator/bundle/certified/seldon-operator.package.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.2/machinelearning.seldon.io_seldondeployment_crd.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/1.2.2/seldon-operator.v1.2.2.clusterserviceversion.yaml
  operator/seldon-operator/deploy/olm-catalog/seldon-operator/seldon-operator.package.yaml
  operator/seldon-operator/deploy/operator.yaml
Labels: approved, size/XXL

#2210 Add license_files to setup.py
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/setup.py
Labels: size/L

#2239 Update microservice.R
  incubating/wrappers/s2i/R/microservice.R
Labels: approved, ok-to-test, size/S

#2248 Batch benchmarking with Argo Workflows
  doc/source/examples/notebooks.rst
  doc/source/examples/vegeta_bench_argo_workflows.nblink
  doc/source/reference/benchmarking.md
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/values.yaml
  examples/batch/benchmarking-argo-workflows-vegeta/.gitignore
  examples/batch/benchmarking-argo-workflows-vegeta/README.ipynb
  examples/batch/benchmarking-argo-workflows-vegeta/README.md
  examples/batch/benchmarking-argo-workflows-vegeta/helm-charts/seldon-batch-workflow/Chart.yaml
  examples/batch/benchmarking-argo-workflows-vegeta/helm-charts/seldon-batch-workflow/README.md
  examples/batch/benchmarking-argo-workflows-vegeta/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/benchmarking-argo-workflows-vegeta/helm-charts/seldon-batch-workflow/values.yaml
Labels: approved, size/XL

#2251 Jenkins x snyk security checks
  SECURITY.md
  jenkins-x-securitychecks.yml
Labels: size/M

#2245 Update ambassador.md
  doc/source/ingress/ambassador.md
Labels: needs-ok-to-test, size/XS

#2264 Add MPL source code to images
  executor/Dockerfile
  executor/Dockerfile.redhat
  operator/Dockerfile
  operator/Dockerfile.redhat
Labels: approved, lgtm, size/M

#2265 Add kubeflow pipeline example to docs
  doc/source/index.rst
Labels: size/XS

#2266 try allowing unknown istio fields
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/XS

#2261 Updated kfserving base image
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-openvino/templates/openvino_deployment.json
  operator/config/manager/configmap.yaml
  operator/controllers/model_initializer_injector_test.go
  operator/controllers/suite_test.go
  operator/utils/k8s/testdata/configmap.yaml
Labels: size/S

#2267 Fix create release script bug
  ci/create-release
Labels: size/XS

#2269 Updated create script to perform 1.2.3 release
  ci/create-release
Labels: size/XS

#2270 Updating createrelease branch from master
  ci/create-release
Labels: size/XS

#2274 Added 1.2.3 dev tag to prepare for release
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: size/L

#2278 Adding links to README features section
  README.md
Labels: size/S

#2279 Updated branch name for nightly release
  jenkins-x.yml
Labels: size/S

#2222 Release java wrapper
  doc/source/java/README.md
  incubating/wrappers/java/pom.xml
Labels: approved, size/M

#2295 Add initial adopters file
  ADOPTERS.md
Labels: approved, size/S

#2296 docs(c1): Add c1 to adopters list
  ADOPTERS.md
Labels: approved, needs-ok-to-test, size/XS

#2294 Adding Janis to the list of approvers
  OWNERS
Labels: size/XS

#2289 2271 feedback reward custom metrics
  doc/source/examples/feedback_reward_custom_metrics.nblink
  doc/source/examples/images/grafana-import.jpg
  doc/source/examples/images/model-perf-comp.jpg
  doc/source/examples/images/realtime-accuracy.jpg
  doc/source/examples/images/single-model.jpg
  doc/source/examples/notebooks.rst
  examples/feedback/reward-accuracy/.gitignore
  examples/feedback/reward-accuracy/MetricsModel.py
  examples/feedback/reward-accuracy/README.ipynb
  examples/feedback/reward-accuracy/grafana-import.jpg
  examples/feedback/reward-accuracy/images/grafana-import.jpg
  examples/feedback/reward-accuracy/images/model-perf-comp.jpg
  examples/feedback/reward-accuracy/images/realtime-accuracy.jpg
  examples/feedback/reward-accuracy/images/single-model.jpg
  examples/feedback/reward-accuracy/model-perf-comp.jpg
  examples/feedback/reward-accuracy/realtime-accuracy.jpg
  examples/feedback/reward-accuracy/requirements.txt
  examples/feedback/reward-accuracy/single-model.jpg
  python/seldon_core/metrics.py
  python/seldon_core/seldon_methods.py
  python/seldon_core/user_model.py
  python/tests/test_metrics.py
Labels: approved, size/XL

#2305 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, size/XS

#2314 Fix shadow and no predictors validation
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
Labels: approved, size/M

#2321 Update to go 1.14.7 in Core-Builder and update executor licenses
  Makefile
  core-builder/Dockerfile
  core-builder/Makefile
  executor/licenses/additional_license_info.csv
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  jenkins-x-createrelease.yml
  jenkins-x-engine.yml
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x-notebooks.yml
  jenkins-x.yml
  release
Labels: size/XXL

#2311 Add return to IrisClassifier
  examples/models/sklearn_iris_jsondata/IrisClassifier.py
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
Labels: approved, size/XS

#2329 Add SELDON_ENVIRONMENT to Index Name
  components/seldon-request-logger/app/log_helper.py
  examples/centralised-logging/seldon-request-logger-k8s.yaml
Labels: ok-to-test, size/S

#2304 Update install.md
  doc/source/workflow/install.md
Labels: needs-ok-to-test, size/XS

#2057 allow independent installation of grafana and prometheus
  helm-charts/seldon-core-analytics/templates/grafana/grafana-net-2115-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/grafana/metrics-test-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/grafana/newdb.yaml
  helm-charts/seldon-core-analytics/templates/grafana/prediction-analytics-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/alertmanager-config-configmap.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-rules-configmap.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-server-conf-configmap.yaml
  helm-charts/seldon-core-analytics/values.yaml
Labels: ok-to-test, size/S

#2334 remove trailing slash from metadata endpoint
  doc/source/reference/apis/external-prediction.md
Labels: approved, size/XS

#2336 fix python test microservice flakiness
  python/tests/helpers.py
Labels: approved, size/XS

#2342 Update licenses
  executor/Makefile
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/Makefile
  operator/licenses/license.txt
Labels: size/L

#2339 k8s 1.18 fix
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/Makefile
  operator/config/crd/kustomization.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/kustomization.yaml
  operator/config/crd_v1/kustomizeconfig.yaml
  operator/config/crd_v1/patches/cainjection_in_seldondeployments.yaml
  operator/config/crd_v1/patches/graph_children.yaml
  operator/config/crd_v1/patches/protocol.yaml
  operator/hack/create_graph_openapi_schema.py
  operator/hack/graph_patch.tmpl.yaml
  operator/helm/Makefile
  operator/helm/split_resources.py
Labels: approved, size/XXL

#2346 align gpu image with regular python wrappers (remove tensorflow)
  doc/source/reference/images.md
  wrappers/s2i/python/Dockerfile.gpu
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/build_scripts/build_all_local.sh
  wrappers/s2i/python/build_scripts/build_local_python3.6.sh
  wrappers/s2i/python/build_scripts/build_python3.6_gpu.sh
  wrappers/s2i/python/build_scripts/build_python3.7_gpu.sh
  wrappers/s2i/python/build_scripts/build_python_gpu.sh
  wrappers/s2i/python/build_scripts/push_all.sh
  wrappers/s2i/python/build_scripts/push_python3.6.sh
  wrappers/s2i/python/build_scripts/push_python3.6_gpu.sh
  wrappers/s2i/python/build_scripts/push_python3.7.sh
  wrappers/s2i/python/build_scripts/push_python3.7_gpu.sh
  wrappers/s2i/python/build_scripts/push_python_gpu.sh
  wrappers/s2i/python/requirements_gpu.txt
Labels: approved, size/M
