Repository SeldonIO/seldon-core, pull requests merged in 2020-01, with the labels that each got.

#1311 treat config as yaml in the values
  helm-charts/seldon-core-operator/templates/configmap_seldon-config.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  operator/helm/split_resources.py
  operator/helm/values-patch.yaml
Labels: approved, size/L

#1316 set deployment replicas
  operator/controllers/seldondeployment_controller.go
Labels: approved, ok-to-test, size/XS

#1326 Exception stack trace should be logged
  engine/src/main/java/io/seldon/engine/service/InternalPredictionService.java
Labels: approved, ok-to-test, size/XS

#1319 Remove log4j
  examples/models/h2o_mojo/h2o_model.ipynb
  examples/models/h2o_mojo/pom.xml
  examples/models/h2o_mojo/train.py
Labels: size/XXL

#1329 operator build test
  operator/README.md
Labels: approved, size/XS

#1332 typo fix: missing api in io.seldon.wrapper.api.SeldonPredictionService
  doc/source/java/README.md
Labels: approved, size/S

#1334 Create and use seldonio/core-builder:0.10
  core-builder/Dockerfile
  core-builder/Makefile
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x.yml
Labels: approved, size/S

#1335 fix operator build - controller-gen install for go modules
  operator/Makefile
Labels: approved, size/XS

#1336 make gpu image Python 3 exclusive, closes #1324
  wrappers/s2i/python/Dockerfile.gpu.tmpl
Labels: approved, lgtm, size/XS

#1331 #1297 WIP Update Analytics Helm Chart
  helm-charts/seldon-core-analytics/Chart.lock
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-analytics/charts/grafana-4.2.3.tgz
  helm-charts/seldon-core-analytics/charts/prometheus-9.7.4.tgz
  helm-charts/seldon-core-analytics/files/alertmanager/config.yaml.example
  helm-charts/seldon-core-analytics/files/grafana/configs/README.md
  helm-charts/seldon-core-analytics/files/grafana/configs/convert-exported-graph.sh
  helm-charts/seldon-core-analytics/files/grafana/configs/grafana-net-2115-dashboard.json
  helm-charts/seldon-core-analytics/files/grafana/configs/import-dashboards-job.sh
  helm-charts/seldon-core-analytics/files/grafana/configs/metrics-test-dashboard.json
  helm-charts/seldon-core-analytics/files/grafana/configs/predictions-analytics-dashboard.json
  helm-charts/seldon-core-analytics/files/grafana/configs/prometheus-datasource.json
  helm-charts/seldon-core-analytics/templates/NOTES.txt
  helm-charts/seldon-core-analytics/templates/alertmanager-deployment.json
  helm-charts/seldon-core-analytics/templates/grafana-prom-dashboards-configmap.yaml
  helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
  helm-charts/seldon-core-analytics/templates/grafana-prom-import-dashboards-job.json
  helm-charts/seldon-core-analytics/templates/grafana-prom-secret.yaml
  helm-charts/seldon-core-analytics/templates/grafana-prom-virtualservice.yaml
  helm-charts/seldon-core-analytics/templates/grafana/grafana-net-2115-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/grafana/metrics-test-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/grafana/newdb.yaml
  helm-charts/seldon-core-analytics/templates/grafana/prediction-analytics-dashboard-configmap.yaml
  helm-charts/seldon-core-analytics/templates/node-exporter-daemonset.json
  helm-charts/seldon-core-analytics/templates/prometheus-deployment.json
  helm-charts/seldon-core-analytics/templates/prometheus/alertmanager-config-configmap.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-rbac.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-rules-configmap.yaml
  helm-charts/seldon-core-analytics/templates/prometheus/prometheus-server-conf-configmap.yaml
  helm-charts/seldon-core-analytics/values.yaml
Labels: size/XL

#1340 Update centralised logging example README to helm 3
  examples/centralised-logging/README.md
Labels: approved, lgtm, size/S

#1346 fix links do images descriptions, closes #1249
  doc/README.md
  doc/source/reference/images.md
  doc/source/reference/integration_nvidia_link.rst
  doc/source/reference/integration_sagemaker_link.rst
  doc/source/reference/integration_tfserving_link.rst
Labels: approved, size/M

#1358 fix tensorflow==2.1 in outliers example
  examples/outliers/alibi-detect-combiner/requirements-dev.txt
Labels: approved, lgtm, size/XS

#1367 Operator 3rd party licences
  operator/Dockerfile
  operator/Makefile
  operator/licenses/README.md
  operator/licenses/additional_license_info.csv
  operator/licenses/dep.txt
  operator/licenses/dep_repo.manual.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
Labels: approved, size/XXL

#1366 add example for custom metrics in feedback
  examples/models/template_model_with_metrics/ModelWithMetrics.py
  examples/models/template_model_with_metrics/modelWithMetrics.ipynb
Labels: approved, lgtm, size/XL

#1376 Update CRD and add executor to CI. Also remove values helm patch.
  ci_build_and_push_images.sh
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  operator/helm/Makefile
  operator/helm/values-patch.yaml
Labels: approved, size/M

#1381 Remove redundant build resources
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  readme.md
Labels: approved, size/L

#1386 Update sklearn.md
  doc/source/servers/sklearn.md
Labels: approved, ok-to-test, size/XS
