Repository SeldonIO/seldon-core, pull requests merged in 2021-01, with the labels that each got.

#2792 Updated changelog for v1.5.1
  CHANGELOG.md
Labels: approved, size/M

#2771 Added f-strings in MAB study case examples
  components/routers/epsilon-greedy/EpsilonGreedy.py
  components/routers/thompson-sampling/ThompsonSampling.py
Labels: approved, lgtm, ok-to-test, size/S

#2813 minor fix to pachyderm example (doc paths)
  doc/source/index.rst
  doc/source/reference/apis/metadata.md
  examples/pachyderm-simple/index.ipynb
Labels: approved, size/L

#2802 Update request logger to support v2 protocol
  components/seldon-request-logger/Makefile
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/test.sh
  notebooks/triton_examples.ipynb
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: size/XL

#2815 update triton tfserving example
  notebooks/triton_examples.ipynb
Labels: size/S

#2820 fix nblink to include image of pachyderm example
  doc/source/examples/pachyderm-simple.nblink
Labels: approved

#2814 extend init containers documentation
  doc/source/examples/custom_init_container.nblink
  doc/source/servers/overview.md
  examples/init_containers/Dockerfile
  examples/init_containers/Makefile
  examples/init_containers/custom_init_container.ipynb
  examples/init_containers/explicit-init-definition.yaml
  examples/init_containers/rclone-default-init.yaml
  examples/init_containers/seldon-reclone-secret.yaml
Labels: approved, lgtm, size/XL

#2770 Extending Alibi Detect Server to expose prometheus metrics for outliers
  components/alibi-detect-server/adserver/constants.py
  components/alibi-detect-server/adserver/od_model.py
Labels: approved, size/M

#2762 Allow Namespace Override for seldon-core-operator
  helm-charts/seldon-core-operator/templates/_helpers.tpl
  helm-charts/seldon-core-operator/templates/certificate_seldon-serving-cert.yaml
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-role.yaml
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-manager-sas-role.yaml
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-spartakus-volunteer.yaml
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-webhook-role.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-manager-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-manager-sas-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-spartakus-volunteer.yaml
  helm-charts/seldon-core-operator/templates/clusterrolebinding_seldon-webhook-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/configmap_seldon-config.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/templates/issuer_seldon-selfsigned-issuer.yaml
  helm-charts/seldon-core-operator/templates/role_seldon-leader-election-role.yaml
  helm-charts/seldon-core-operator/templates/role_seldon1-manager-role.yaml
  helm-charts/seldon-core-operator/templates/role_seldon1-manager-sas-role.yaml
  helm-charts/seldon-core-operator/templates/rolebinding_seldon-leader-election-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/rolebinding_seldon1-manager-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/rolebinding_seldon1-manager-sas-rolebinding.yaml
  helm-charts/seldon-core-operator/templates/service_seldon-webhook-service.yaml
  helm-charts/seldon-core-operator/templates/serviceaccount_seldon-manager.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/helm/split_resources.py
Labels: approved, ok-to-test, size/L

#2835 Revert "Bump pandas from 1.1.0 to 1.2.0 in /python"
  python/requirements-dev.txt
Labels: approved, size/XS

#2841 add hdfs example
  examples/batch/hdfs-argo-workflows/.gitignore
  examples/batch/hdfs-argo-workflows/Dockerfile
  examples/batch/hdfs-argo-workflows/Makefile
  examples/batch/hdfs-argo-workflows/deployment.yaml
  examples/batch/hdfs-argo-workflows/extra-rclone/rclone-config.yaml
  examples/batch/hdfs-argo-workflows/extra-rclone/rclone-workflow-example.yaml
  examples/batch/hdfs-argo-workflows/extra-rclone/workflow-create-data-rclone.yaml
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  examples/batch/hdfs-argo-workflows/hdfs-config.yaml
  examples/batch/hdfs-argo-workflows/hdfscli.cfg
  examples/batch/hdfs-argo-workflows/role.yaml
  examples/batch/hdfs-argo-workflows/workflow.yaml
Labels: size/XXL

#2842 Rclone powered batch
  doc/source/examples/argo_workflows_hdfs_batch.html
  doc/source/examples/notebooks.rst
  doc/source/servers/batch.md
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/Chart.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/values.yaml
  examples/batch/argo-workflows-batch/rclone-config.yaml
  examples/batch/argo-workflows-batch/role.yaml
Labels: size/XL

#2853 Manager running as non-root
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/default/manager_webhook_patch.yaml
  operator/config/manager/manager.yaml
  operator/config/openshift/kustomization.yaml
  operator/config/openshift/patch_manager_args.yaml
  operator/config/openshift/patch_manager_webhook.yaml
  operator/helm/split_resources.py
Labels: approved

#2867 Revert "Bump pandas from 1.1.0 to 1.2.0 in /python"
  python/requirements-dev.txt
Labels: approved, size/XS

#2868 Fix grpcPort and httpPort in v1 CRD
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  notebooks/protocol_examples.ipynb
  operator/config/crd/patches/graph_children.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/patches/graph_children.yaml
  operator/go.sum
Labels: size/XXL

#2886 Generate helm-charts again to fix: Error: secrets "seldon-webhook-ser…
  helm-charts/seldon-core-operator/templates/webhook.yaml
Labels: size/M

#2889 Moving basic CI to github actions
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  .github/workflows/rebase.yml
  jenkins-x-docs.yml
  jenkins-x-lint.yml
  jenkins-x.yml
Labels: size/L

#2892 Github Action fixes
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
Labels: size/S

#2852 remove mutating webhook from Seldon Core Operator
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-webhook-role.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  notebooks/explainer_examples.ipynb
  operator/Dockerfile
  operator/Dockerfile.redhat
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_webhook.go
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/config/cert/kustomization.yaml
  operator/config/controllerid/kustomization.yaml
  operator/config/controllerid/webhook-config.yaml
  operator/config/default/webhookcainjection_patch.yaml
  operator/config/lite/role_webhook.yaml
  operator/config/manifests/bases/seldon-operator.clusterserviceversion.yaml
  operator/config/namespaced/kustomization.yaml
  operator/config/namespaced/webhook-config.yaml
  operator/config/openshift/role_webhook.yaml
  operator/config/webhook/kustomization.yaml
  operator/config/webhook/kustomizeconfig.yaml
  operator/config/webhook/manifests.yaml
  operator/controllers/seldondeployment_controller.go
  operator/helm/split_resources.py
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  operator/utils/k8s/initializer.go
  operator/utils/k8s/webhook.go
  operator/utils/k8s/webhook_test.go
Labels: size/XXL

#2891 2252 resolve pyyaml cve
  python/seldon_core/utils.py
  python/setup.py
  servers/mlflowserver/mlflowserver/MLFlowServer.py
  servers/xgboostserver/xgboostserver/XGBoostServer.py
Labels: size/XS

#2894 Update Python Builder to use latest git for compatibility with github actions
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  python-builder/Dockerfile
  python-builder/Makefile
Labels: size/S

#2870 updates for redhat scans
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  engine/Dockerfile.redhat
  executor/Dockerfile.executor.redhat
  operator/Dockerfile.redhat
  servers/tfserving/Dockerfile.redhat
  wrappers/s2i/python/Dockerfile.conda
  wrappers/s2i/python/Dockerfile.redhat
Labels: ok-to-test, size/S
