Repository SeldonIO/seldon-core, pull requests merged in 2021-06, with the labels that each got.

#3252 Fixed broken "tutum/curl" image in Notebook tests tests
  examples/models/custom_metrics/customMetrics.ipynb
  examples/models/custom_metrics/get-metrics.sh
  examples/models/custom_metrics/tfservingMetrics.ipynb
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
Labels: size/S

#3243 Documenting PVC storage initialiser
  doc/source/servers/overview.md
Labels: size/S

#3248 Add kfserving protocol to alibi explainer server
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/alibiexplainer/explainer.py
  components/alibi-explain-server/alibiexplainer/model.py
  components/alibi-explain-server/alibiexplainer/proto/tensorflow/core/framework/tensor.proto
  components/alibi-explain-server/alibiexplainer/proto/tensorflow/core/framework/types.proto
  components/alibi-explain-server/alibiexplainer/server.py
  components/alibi-explain-server/alibiexplainer/v2_http.py
  components/alibi-explain-server/tests/data/truck-v2-response.json
  components/alibi-explain-server/tests/data/truck-v2.json
  components/alibi-explain-server/tests/test_v2.py
  notebooks/explainer_examples.ipynb
  operator/controllers/mlserver.go
  operator/controllers/seldondeployment_explainers.go
Labels: size/XXL

#3262 Clean up openapi
  openapi/Makefile
  openapi/README.md
  openapi/base.json
  openapi/components.json
  openapi/create_openapis.py
  openapi/paths-ambassador.json
  openapi/paths-internal.json
  openapi/security.json
Labels: size/XXL

#3240 Fix tracing debug
  examples/models/tracing/deployment_grpc.yaml
  examples/models/tracing/deployment_rest.yaml
  examples/models/tracing/tracing.ipynb
  python/seldon_core/gunicorn_utils.py
  python/seldon_core/microservice.py
Labels: size/L

#3246 Add explainer replicas and handle scale to zero
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  notebooks/explainer_examples.ipynb
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: size/L

#3256 categorical and proba for req logger ndarray
  components/seldon-request-logger/README.md
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
  components/seldon-request-logger/testing/create_dummy_metadata.py
  components/seldon-request-logger/testing/test.sh
Labels: approved, size/L

#3271 some unit tests for req logger
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/tests.py
Labels: approved, size/M

#3277 Add Triton Examples Notebook to docs
  doc/source/examples/notebooks.rst
  doc/source/examples/triton_examples.nblink
Labels: size/XS

#3280 elements for batch and tf protocol
  components/seldon-request-logger/README.md
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_mapping.py
  components/seldon-request-logger/requirements.txt
  components/seldon-request-logger/testing/cifardata.json
  components/seldon-request-logger/testing/create_dummy_metadata.py
  components/seldon-request-logger/testing/test.sh
Labels: approved, size/L

#3288 Allow MLServer envs to be overriden
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
Labels: approved, size/S

#3221 Docs styling update
  doc/requirements.txt
  doc/source/Seldon_White.png
  doc/source/_static/theme_overrides.css
  doc/source/conf.py
Labels: size/L

#3291 Docs styling fix to work on readthedocs
  doc/requirements.txt
  doc/source/_static/theme_overrides.css
  doc/source/_templates/layout.html
  doc/source/conf.py
Labels: size/M

#3286 Iter8 Integration
  doc/source/examples/iter8-separate.nblink
  doc/source/examples/iter8-single.nblink
  doc/source/examples/notebooks.rst
  doc/source/index.rst
  doc/source/rollouts/abtests.md
  doc/source/rollouts/seldon-iter8-separate.png
  doc/source/rollouts/seldon-iter8-single.png
  examples/iter8/.gitignore
  examples/iter8/ansible.cfg
  examples/iter8/inventory.ini
  examples/iter8/metrics.yaml
  examples/iter8/platformsetup.sh
  examples/iter8/playbooks/files/kind_config.yaml
  examples/iter8/playbooks/iter8.yml
  examples/iter8/progressive_rollout/separate_sdeps/abtest.ipynb
  examples/iter8/progressive_rollout/separate_sdeps/baseline.yaml
  examples/iter8/progressive_rollout/separate_sdeps/candidate.yaml
  examples/iter8/progressive_rollout/separate_sdeps/experiment.yaml
  examples/iter8/progressive_rollout/separate_sdeps/fortio.yaml
  examples/iter8/progressive_rollout/separate_sdeps/promote-v1.yaml
  examples/iter8/progressive_rollout/separate_sdeps/promote-v2.yaml
  examples/iter8/progressive_rollout/separate_sdeps/routing-rule.yaml
  examples/iter8/progressive_rollout/single_sdep/abtest.ipynb
  examples/iter8/progressive_rollout/single_sdep/abtest.yaml
  examples/iter8/progressive_rollout/single_sdep/experiment.yaml
  examples/iter8/progressive_rollout/single_sdep/fortio.yaml
  examples/iter8/progressive_rollout/single_sdep/promote-v1.yaml
  examples/iter8/progressive_rollout/single_sdep/promote-v2.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/controllers/labels.go
  operator/controllers/labels_test.go
Labels: size/XXL

#3300 Update Iter8 promote URLs
  doc/source/rollouts/abtests.md
  examples/iter8/progressive_rollout/separate_sdeps/experiment.yaml
  examples/iter8/progressive_rollout/single_sdep/experiment.yaml
Labels: size/S

#3303 Added styling for indentation of docs
  doc/source/_static/theme_overrides.css
  doc/source/conf.py
  doc/source/index.rst
Labels: size/S

#3304 Added headers to seldon core documentation
  doc/source/_static/theme_overrides.css
  doc/source/conf.py
Labels: size/M

#3308 Fixed broken rtd versions
  doc/source/conf.py
Labels: size/XS

#3306 Micro batch followup
  python/seldon_core/batch_processor.py
Labels: approved, size/S

#3170 Update sklearn_iris.ipynb
  examples/models/sklearn_iris/sklearn_iris.ipynb
Labels: approved, needs-ok-to-test, size/XS

#3309 Added docuentation fix to support rtd versions popup
  doc/source/conf.py
Labels: size/S

#3310 Update OWNERS
  OWNERS
Labels: size/XS

#3315 Update OWNERS to add [majolo]
  OWNERS
Labels: size/XS

#3317 Adding elements array support for v2 protocol single input
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_mapping.py
Labels: approved, size/XS

#3311 Added doc hint for install behind proxy
  doc/source/workflow/install.md
Labels: needs-ok-to-test, size/S

#3322 Fix deploy docs link
  doc/source/conf.py
Labels: size/XS

#3323 Update python_wrapping_docker.md
  doc/source/python/python_wrapping_docker.md
Labels: approved, size/XS

#3326 add SA to explainer podspec
  operator/controllers/seldondeployment_explainers.go
Labels: approved, size/XS

#3327 Gpt2 notebook example on Azure + Azure setup
  doc/source/examples/notebooks.rst
  doc/source/examples/triton_gpt2_example_azure.nblink
  doc/source/examples/triton_gpt2_example_azure_setup.nblink
  examples/triton_gpt2/AzureSetup.ipynb
  examples/triton_gpt2/GPT2-ONNX-Azure.ipynb
Labels: size/XXL

#3344 Fix broken docs test via broken link
  doc/source/ingress/ambassador.md
Labels: size/XS

#3346 Updated default rest threads to 1 and added grpc threads
  python/seldon_core/microservice.py
  python/seldon_core/wrapper.py
Labels: size/S

#3336 python wrapper benchmarking
  examples/models/testing/FixedBase.py
  examples/models/testing/FixedPredict.py
  examples/models/testing/FixedPredictRaw.py
  examples/models/testing/Makefile
  examples/models/testing/__init__.py
  examples/models/testing/environment_predict
  examples/models/testing/environment_predict_raw
  examples/models/testing/requirements.txt
  testing/benchmarking/python/.gitignore
  testing/benchmarking/python/python_serialization.ipynb
Labels: size/XXL

#3313 Ensure status url works with no engine
  operator/controllers/seldondeployment_controller.go
Labels: approved, size/S

#3353 Added v2 inference protocol protos into istio virtualservice
  operator/constants/constants.go
Labels: size/XS

#3342 add example upgrade path into rclone-based storage initializer
  doc/source/examples/global-rclone-upgrade.nblink
  doc/source/examples/rclone-upgrade.nblink
  doc/source/reference/upgrading.md
  doc/source/servers/kfserving-storage-initializer.md
  doc/source/servers/overview.md
  examples/init_containers/custom_init_container.ipynb
  examples/upgrade-to-rclone/global-rclone-upgrade.ipynb
  examples/upgrade-to-rclone/rclone-pod.yaml
  examples/upgrade-to-rclone/rclone-upgrade.ipynb
  examples/upgrade-to-rclone/seldon-kfserving-secret.yaml
  examples/upgrade-to-rclone/seldon-rclone-secret.yaml
  examples/upgrade-to-rclone/sklearn-iris-kfserving.yaml
  examples/upgrade-to-rclone/sklearn-iris-rclone.yaml
  examples/upgrade-to-rclone/sklearn-iris-sa.yaml
  examples/upgrade-to-rclone/sklearn-iris-secret.yaml
Labels: approved, size/XXL
