Repository SeldonIO/seldon-core, pull requests merged in 2021-12, with the labels that each got.

#3754 Address MLServer flakiness in CI tests
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
  servers/mlflowserver/Makefile
  testing/scripts/e2e_utils/v2_protocol.py
  wrappers/s2i/python/Dockerfile
Labels: size/M

#3788 Added MPL Licenses to Docker images
  executor/Dockerfile.executor
  executor/Dockerfile.executor.redhat
  operator/Dockerfile
  operator/Dockerfile.redhat
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Dockerfile.conda
  wrappers/s2i/python/Dockerfile.gpu
Labels: size/L

#3789 batch processor: always prioritize tags from model
  python/seldon_core/batch_processor.py
Labels: size/XS

#3774 Support https on batch processor
  doc/source/reference/release-1.7.0.md
  doc/source/servers/batch.md
  python/seldon_core/batch_processor.py
  python/seldon_core/seldon_client.py
  testing/scripts/test_batch_processor.py
Labels: size/L, approved

#3791 use lowercase seldon-puid in batch processor
  python/seldon_core/batch_processor.py
  testing/scripts/test_batch_processor.py
Labels: size/M, approved

#3793 Addressed vulnerabilities with snyk for containers and libraries
  .github/workflows/security_tests.yml
  executor/.snyk
  operator/.snyk
  python/.snyk
  python/setup.py
Labels: size/M

#3794 Tweak script to generate MLflow environment tarball
  servers/mlflowserver/models/elasticnet_wine/.inference-env/.gitignore
  servers/mlflowserver/models/elasticnet_wine/Makefile
  servers/mlflowserver/models/elasticnet_wine/output/.gitignore
  servers/mlflowserver/models/elasticnet_wine/output/.keep
  servers/mlflowserver/models/elasticnet_wine/requirements.txt
Labels: size/S, approved

#3768 Allow deployment name as prefix when default name to long
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types_test.go
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: size/L, approved

#3783 build adserver dockerimage using poetry-defined environment
  .github/workflows/alibidetect_tests.yml
  components/alibi-detect-server/.gitignore
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/tests/test_server.py
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
  components/alibi-detect-server/requirements-dev.txt
  components/alibi-detect-server/requirements_server.txt
  components/alibi-detect-server/setup.py
  components/alibi-explain-server/Dockerfile
  examples/feedback/metrics-server/README.ipynb
  examples/feedback/metrics-server/README.md
  examples/feedback/metrics-server/config/multiclass-deployment.yaml
  examples/models/mean_classifier/Makefile
  release.py
Labels: size/XXL

#3796 fix missing rclone in adserver
  components/alibi-detect-server/Dockerfile
Labels: size/XS

#3795 Bump MLServer image to 1.0.0.rc1
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  testing/scripts/test_alibi_explain_v2.py
  testing/scripts/test_prepackaged_servers.py
Labels: size/M, approved, do-not-merge/hold

#3800 Add note for MacOS users
  ansible/README.md
Labels: size/XS, approved, needs-ok-to-test

#3801 Use consistent identity not per-request UUID for worker IDs
  components/alibi-detect-server/adserver/server.py
Labels: size/XS

#3807 Exclude caBundle field when cert-manager is enabled
  helm-charts/seldon-core-operator/templates/webhook.yaml
Labels: size/XS, approved
