Repository SeldonIO/seldon-core, pull requests merged in 2021-08, with the labels that each got.

#3444 Adding instructions for migration of Kubernetes post 1.18
  doc/source/reference/upgrading.md
Labels: size/S

#3443 remove assertion
  python/seldon_core/utils.py
  testing/docker/fixed-model/Makefile
  testing/scripts/test_operator_updates.py
Labels: approved, size/XS

#3453 Add golangci-lint linters to the executor
  executor/.errcheck_excludes.txt
  executor/.golangci.yml
  executor/api/client/client.go
  executor/api/grpc/client.go
  executor/api/grpc/client_test.go
  executor/api/grpc/kfserving/client.go
  executor/api/grpc/kfserving/server.go
  executor/api/grpc/seldon/client.go
  executor/api/grpc/seldon/client_test.go
  executor/api/grpc/seldon/server.go
  executor/api/grpc/seldon/server_test.go
  executor/api/grpc/seldon/test/test_server.go
  executor/api/grpc/tensorflow/client.go
  executor/api/grpc/tensorflow/server.go
  executor/api/grpc/tensorflow/server_test.go
  executor/api/kafka/client.go
  executor/api/kafka/proxy.go
  executor/api/kafka/server.go
  executor/api/kafka/server_test.go
  executor/api/kafka/topic.go
  executor/api/kafka/worker.go
  executor/api/metric/client.go
  executor/api/metric/client_test.go
  executor/api/metric/server.go
  executor/api/payload/metadata.go
  executor/api/payload/metadata_test.go
  executor/api/payload/payload_test.go
  executor/api/payload/proto_test.go
  executor/api/rest/client.go
  executor/api/rest/client_test.go
  executor/api/rest/kfserving.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/api/rest/tensorflow.go
  executor/api/rest/utils.go
  executor/api/rest/utils_test.go
  executor/api/test/seldonmessage_test_client.go
  executor/api/tracing/trace_test.go
  executor/api/util/utils_test.go
  executor/cmd/executor/main.go
  executor/cmd/proxy/main.go
  executor/k8s/annotation.go
  executor/k8s/annotation_test.go
  executor/logger/dispatcher.go
  executor/logger/worker.go
  executor/predictor/components.go
  executor/predictor/metadata.go
  executor/predictor/metadata_test.go
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
  executor/predictor/ready_checker.go
  executor/predictor/utils.go
Labels: approved, size/L

#3455 Add golangci-lint linters to the operator
  operator/.errcheck_excludes.txt
  operator/.golangci.yml
  operator/apis/machinelearning.seldon.io/v1/defaults_test.go
  operator/apis/machinelearning.seldon.io/v1/prepack.go
  operator/apis/machinelearning.seldon.io/v1/prepack_test.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types_test.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_webhook.go
  operator/controllers/cleaners.go
  operator/controllers/controller_utils.go
  operator/controllers/labels.go
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
  operator/controllers/model_initializer_injector.go
  operator/controllers/model_initializer_injector_test.go
  operator/controllers/replicas_test.go
  operator/controllers/resources/credentials/gcs/gcs_secret.go
  operator/controllers/resources/credentials/gcs/gcs_secret_test.go
  operator/controllers/resources/credentials/s3/s3_secret.go
  operator/controllers/resources/credentials/s3/s3_secret_test.go
  operator/controllers/resources/credentials/service_account_credentials.go
  operator/controllers/security.go
  operator/controllers/security_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
  operator/utils/k8s/certs.go
  operator/utils/k8s/certs_test.go
  operator/utils/k8s/configmap.go
  operator/utils/k8s/configmap_test.go
  operator/utils/k8s/crd.go
  operator/utils/k8s/crd_test.go
  operator/utils/k8s/initializer.go
  operator/utils/k8s/webhook.go
  operator/utils/k8s/webhook_test.go
  operator/utils/utils.go
  operator/utils/utils_test.go
Labels: approved, size/L

#3456 Add golangci-lint to operator and executor test step and to core-builder image
  .github/workflows/executor_tests.yml
  .github/workflows/operator_tests.yml
  core-builder/Dockerfile
  core-builder/Makefile
  executor/Makefile
  executor/README.md
  operator/Makefile
  operator/README.md
Labels: approved, size/M

#3472 Add a walk-through example to train and deploy an mlflow model using v2 protocol
  doc/source/servers/mlflow.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/L, approved

#3478 Fixes for release pipeline
  .lighthouse/jenkins-x/release.yaml
  ci_build_and_push_images.sh
Labels: size/XS, approved

#3458 Updating Alibi Detect Custom Metrics Server to use Dill instead of Pickle
  components/alibi-detect-server/adserver/cm_model.py
  components/alibi-detect-server/setup.py
Labels: size/XS

#3469 Bump seldonio/mlserver to 0.4.0
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/S, approved

#3483 Add a first pass mlflow v2 end to end example
  doc/source/examples/mlflow_v2_protocol_end_to_end.nblink
  doc/source/examples/notebooks.rst
  examples/models/mlflow_v2_protocol_end_to_end/README.ipynb
  examples/models/mlflow_v2_protocol_end_to_end/README.md
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/XXL, approved

#3486 Tidy up mlflow docs
  doc/source/servers/mlflow.md
Labels: size/S, approved

#3491 Fix master alibi detect
  components/alibi-detect-server/requirements_server.txt
  release.py
  testing/resources/adserver-cifar10-od-rclone.yaml
  testing/resources/adserver-cifar10-od.yaml
Labels: size/M

#3490 fix alibi detect server
  components/alibi-detect-server/requirements_server.txt
  testing/resources/adserver-cifar10-od-rclone.yaml
  testing/resources/adserver-cifar10-od.yaml
Labels: size/XS

#3496 adserver flakiness fix
  testing/scripts/test_alibi_detect_server.py
Labels: size/M, approved

#3504 gcp notes for storage initializers
  doc/source/servers/kfserving-storage-initializer.md
  doc/source/servers/overview.md
Labels: size/M

#3501 Alibi explain 110 fix
  components/alibi-explain-server/alibiexplainer/server.py
  doc/source/analytics/explainers.md
  notebooks/explainer_examples.ipynb
Labels: size/S

#3539 lock numba to 0.53.1 for alibi explain image
  components/alibi-explain-server/Dockerfile
Labels: size/XS
