Repository SeldonIO/seldon-core, pull requests merged in 2021-11, with the labels that each got.

#3706 Added security scans for containers
  .github/workflows/security_tests.yml
Labels: size/L

#3709 Add ginkgo Make target
  operator/Makefile
Labels: size/S

#3711 add shutdown_delay option to executor & gRPC GracefulStop
  executor/cmd/executor/main.go
  executor/predictor/utils.go
  executor/predictor/utils_test.go
Labels: size/L, needs-ok-to-test

#3642 e2e examples for iris explainer using poetry-defined environment
  ansible/README.md
  ansible/playbooks/kind_cluster.yaml
  ansible/playbooks/kind_many_workers.yaml
  ansible/playbooks/main.yaml
  ansible/playbooks/seldon_core.yaml
  ansible/playbooks/vars/default.yaml
  doc/source/analytics/explainers.md
  doc/source/examples/iris_explainer_poetry.nblink
  doc/source/servers/overview.md
  examples/explainers/iris-explainer-poetry/.gitignore
  examples/explainers/iris-explainer-poetry/iris-explainer.ipynb
  examples/explainers/iris-explainer-poetry/iris-with-explainer.yaml
  examples/explainers/iris-explainer-poetry/iris.yaml
  examples/explainers/iris-explainer-poetry/rclone.conf
  examples/explainers/iris-explainer-poetry/secret.yaml
  examples/explainers/iris-explainer-poetry/train.py
Labels: size/XL, approved

#3718 Batch processor enhancemenst through raw data parameter
  doc/source/servers/batch.md
  python/seldon_core/batch_processor.py
  python/swag.txt
  testing/.gitignore
  testing/scripts/.gitignore
  testing/scripts/test_batch_processor.py
Labels: size/L, approved

#3728 Mnist e2e triton
  doc/source/examples/triton_mnist_e2e.nblink
  doc/source/servers/triton.md
  examples/mnist_triton_e2e/.gitignore
  examples/mnist_triton_e2e/deployment.yaml
  examples/mnist_triton_e2e/mnist-triton.ipynb
  examples/mnist_triton_e2e/poetry.lock
  examples/mnist_triton_e2e/pyproject.toml
  examples/mnist_triton_e2e/rclone.conf
  examples/mnist_triton_e2e/secret.yaml
  examples/mnist_triton_e2e/train.py
Labels: size/XXL

#3734 Performance fix for the logger in the executor
  executor/cmd/executor/main.go
  executor/go.mod
  executor/logger/collector.go
  executor/logger/dispatcher.go
  executor/logger/log_memory_benchmark_test.go
  executor/logger/worker.go
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
Labels: size/L

#3737 fix python lint
  examples/mnist_triton_e2e/mnist-triton.ipynb
Labels: size/XS

#3724 Chart annotations
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/helm/split_resources.py
Labels: size/M, needs-ok-to-test

#3736 Fix 1.22 Webhook Create by ensuring v1 is used
  operator/utils/k8s/configmap.go
  operator/utils/k8s/crd.go
  operator/utils/k8s/initializer.go
  operator/utils/k8s/utils.go
  operator/utils/k8s/webhook.go
  operator/utils/k8s/webhook_test.go
Labels: size/L, approved

#3731 add endpoint to match python status endpoint
  executor/api/rest/server.go
Labels: size/XS, needs-ok-to-test

#3741 Chart annotations cont, manager container security context
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/helm/split_resources.py
Labels: size/S, needs-ok-to-test

#3738 Logger params
  doc/source/graph/annotations.md
  doc/source/reference/upgrading.md
  executor/cmd/executor/main.go
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-benchmark-workflow/README.md
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/README.md
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/config/manager/manager.yaml
  operator/constants/constants.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_engine_test.go
  operator/helm/split_resources.py
Labels: size/L, approved

#3707 Sherif akoush/sc 2543/alibi explain mlserver runtime
  doc/source/analytics/explainers.md
  doc/source/examples/iris_anchor_tabular_explainer_v2.nblink
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/values.yaml
  notebooks/explainer_examples_v2.ipynb
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/apis/machinelearning.seldon.io/v1alpha2/zz_generated.deepcopy.go
  operator/apis/machinelearning.seldon.io/v1alpha3/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/manager/configmap.yaml
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
  operator/controllers/suite_test.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  testing/resources/iris_anchor_tabular_explainer_v2.yaml
  testing/scripts/test_alibi_explain_v2.py
Labels: size/XL

#3743 Transformers example
  doc/source/examples/notebooks.rst
  doc/source/examples/transformers-v2-protocol.nblink
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/gpt2-graph.svg
  examples/transformers/v2-protocol/seldondeployment.yaml
  examples/transformers/v2-protocol/tokeniser/model-settings.json
  examples/transformers/v2-protocol/tokeniser/requirements.txt
  examples/transformers/v2-protocol/tokeniser/runtime.py
Labels: size/L

#3745 Fixing docs-build test
  doc/source/contents.rst
  doc/source/install/kind.rst
  doc/source/nav/archive.rst
  doc/source/nav/getting-started.rst
  doc/source/nav/reference.rst
  doc/source/python/python_server.rst
Labels: size/M, approved

#3746 executor: decompress gzip paloyads before logging them
  executor/api/payload/utils.go
  executor/api/rest/kfserving.go
  executor/logger/types.go
  executor/logger/worker.go
  executor/predictor/predictor_process.go
  executor/samples/local/kfserving/Makefile
  executor/samples/local/kfserving/model.yaml
Labels: size/L, approved

#3744 Sherif akoush/sc 2549/alibi v1 fixes
  .github/workflows/alibiexplainer_tests.yml
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/alibiexplainer/__main__.py
  components/alibi-explain-server/alibiexplainer/ale.py
  components/alibi-explain-server/alibiexplainer/anchor_images.py
  components/alibi-explain-server/alibiexplainer/anchor_tabular.py
  components/alibi-explain-server/alibiexplainer/anchor_text.py
  components/alibi-explain-server/alibiexplainer/constants.py
  components/alibi-explain-server/alibiexplainer/explainer.py
  components/alibi-explain-server/alibiexplainer/explainer_wrapper.py
  components/alibi-explain-server/alibiexplainer/integrated_gradients.py
  components/alibi-explain-server/alibiexplainer/kernel_shap.py
  components/alibi-explain-server/alibiexplainer/model.py
  components/alibi-explain-server/alibiexplainer/parser.py
  components/alibi-explain-server/alibiexplainer/seldon_http.py
  components/alibi-explain-server/alibiexplainer/server.py
  components/alibi-explain-server/alibiexplainer/tree_shap.py
  components/alibi-explain-server/alibiexplainer/utils.py
  components/alibi-explain-server/alibiexplainer/v2_http.py
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  components/alibi-explain-server/setup.py
  components/alibi-explain-server/tests/data/input.json
  components/alibi-explain-server/tests/make_test_models.py
  components/alibi-explain-server/tests/test_ale.py
  components/alibi-explain-server/tests/test_anchor_images.py
  components/alibi-explain-server/tests/test_anchor_tabular.py
  components/alibi-explain-server/tests/test_anchor_text.py
  components/alibi-explain-server/tests/test_app.py
  components/alibi-explain-server/tests/test_integrated_gradients.py
  components/alibi-explain-server/tests/test_kernel_shap.py
  components/alibi-explain-server/tests/test_parser.py
  components/alibi-explain-server/tests/test_tree_shap.py
  components/alibi-explain-server/tests/test_v2.py
  components/alibi-explain-server/tests/utils.py
  operator/controllers/seldondeployment_explainers.go
Labels: size/XXL, approved

#3762 fixed iris sklearn model example
  examples/models/sklearn_iris/sklearn_iris.ipynb
Labels: size/XS, approved, needs-ok-to-test

#3771 Docs: Removed argument from tags example
  doc/source/python/python_component.md
Labels: size/XS, needs-ok-to-test
