Repository SeldonIO/seldon-core, pull requests merged in 2021-04, with the labels that each got.

#3044 docs: use Helm v3 commands in Istio docs
  doc/source/examples/istio_canary.nblink
  doc/source/examples/notebooks.rst
  doc/source/ingress/istio.md
  examples/istio/README.md
  examples/istio/canary/.gitignore
  examples/istio/canary/README.md
  examples/istio/canary/istio_canary.ipynb
  notebooks/istio_example.ipynb
  notebooks/seldon_core_setup.ipynb
Labels: needs-ok-to-test, size/XL

#3014 Request logger elastic mapping type unsetting
  components/seldon-request-logger/README.md
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
Labels: approved, size/S

#3116 Allow nil graph TYPE
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
Labels: size/M

#3048 Add keepalive
  doc/source/python/python_server.md
  python/seldon_core/microservice.py
Labels: ok-to-test, size/XS

#3134 Fix broken Alibi Detect image in master
  components/alibi-detect-server/requirements_server.txt
  examples/models/pvc-tfjob/pvc-tfjob.ipynb
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/L

#3118 mlflow example fix & image change: do not use editable install of SC for s2i wrapper
  doc/source/servers/mlflow.md
  examples/models/mlflow_server_ab_test_ambassador/mlflow_server_ab_test_ambassador.ipynb
  notebooks/server_examples.ipynb
  servers/mlflowserver/samples/elasticnet_wine.yaml
  wrappers/s2i/python/Dockerfile.gpu
  wrappers/s2i/python/Dockerfile.local
  wrappers/s2i/python/Dockerfile.redhat
Labels: size/S

#3135 Update kustomize to 4.1.2
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  core-builder/Dockerfile
  core-builder/Makefile
  examples/models/pvc-tfjob/pvc-tfjob.ipynb
  operator/Dockerfile
  operator/helm/Makefile
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  release
Labels: size/L

#3104 Depricate persistence
  doc/source/python/python_wrapping_docker.md
  doc/source/python/python_wrapping_s2i.md
  python/conda.recipe/meta.yaml
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/seldon_core/microservice.py
  python/seldon_core/persistence.py
  python/setup.py
  python/tests/helpers.py
  python/tests/resources/custom-metrics-model/.s2i/environment
  python/tests/resources/model-template-app/.s2i/environment
  python/tests/resources/model-template-app2/.s2i/environment
  python/tests/test_microservice.py
  wrappers/s2i/python/s2i/bin/run
Labels: size/L
