Repository SeldonIO/seldon-core, pull requests merged in 2021-03, with the labels that each got.

#2990 Support model repositories for Triton and Tensorflow Servers
  executor/api/grpc/kfserving/server.go
  executor/api/grpc/seldon/server.go
  executor/api/grpc/tensorflow/server.go
  executor/api/kafka/worker.go
  executor/api/rest/server.go
  executor/go.sum
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
  notebooks/resources/.gitignore
  notebooks/triton_examples.ipynb
  testing/scripts/e2e_utils/v2_protocol.py
  testing/scripts/test_prepackaged_servers.py
Labels: approved, size/L

#2989 small improvements to metrics server example
  examples/feedback/feedback-metrics-server/README.ipynb
  examples/feedback/feedback-metrics-server/README.md
  examples/feedback/metrics-server/README.ipynb
  examples/feedback/metrics-server/README.md
  examples/feedback/metrics-server/config/multiclass-deployment.yaml
Labels: size/L

#3012 fix: missing string ending in python snippet in serving.md
  doc/source/workflow/serving.md
Labels: needs-ok-to-test, size/XS

#3015 Notebook tests/metrics server port 8003
  examples/feedback/metrics-server/README.ipynb
Labels: size/M

#3018 Clear methods when Gunicorn worker exits
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/seldon_core/gunicorn_utils.py
  python/seldon_core/metrics.py
  python/seldon_core/microservice.py
  python/tests/resources/custom-metrics-model/.s2i/environment
  python/tests/resources/custom-metrics-model/MyModel.py
  python/tests/test_gunicorn_utils.py
  python/tests/test_metrics.py
Labels: approved, size/L

#3028 update python licenses
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/S

#3008 fix indentation of argo batch template
  examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml
Labels: size/S

#3006 Update manifests to use 0.4.1 controller gen for webhook creation
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/Makefile
  operator/config/webhook/manifests.yaml
Labels: size/M

#3030 Fixes #3029
  README.md
Labels: size/XS

#3045 docs: add helm v3 commands
  doc/source/workflow/usage-reporting.md
  examples/cicd/sig-mlops-jenkins-classic/README.md
  examples/models/aws_eks_deep_mnist/README.md
  examples/models/azure_aks_deep_mnist/README.md
  examples/models/gpu_tensorflow_deep_mnist/README.md
  testing/profiling/engine/README.md
Labels: needs-ok-to-test, size/S

#3047 Fix nil pointer dereference panics in mlserver
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
Labels: size/S

#3049 Revert "Update manifests to use 0.4.1 controller gen for webhook creation"
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/Makefile
  operator/config/webhook/manifests.yaml
Labels: size/M

#3051 fix broken link
  doc/source/ingress/istio.md
Labels: size/XS

#3023 Update health status
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  python/seldon_core/user_model.py
  python/seldon_core/wrapper.py
  python/tests/test_microservice.py
Labels: approved, size/M

#3031 Delete mutating webhook if exists when operator creates resources
  helm-charts/seldon-core-operator/templates/clusterrole_seldon-webhook-role.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/config/lite/role_webhook.yaml
  operator/config/openshift/role_webhook.yaml
  operator/utils/k8s/initializer.go
  operator/utils/k8s/webhook.go
Labels: size/M

#3061 environment.yml typo in docs
  doc/source/python/python_wrapping_s2i.md
Labels: size/XS

#3064 Support kfserving protocol in status URL
  operator/utils/utils.go
  operator/utils/utils_test.go
Labels: size/M

#3071 Fixes broken docs-build test
  CHANGELOG.md
Labels: size/XS

#3076 Updating spacy notebook
  examples/models/sklearn_spacy_text/Dockerfile
  examples/models/sklearn_spacy_text/reddit_clf.json
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
Labels: approved, size/L

#3060 GPU drift work
  components/alibi-detect-server/Dockerfile.gpu
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/__main__.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/requirements-gpu.txt
  components/drift-detection/nvidia-triton-cifar10/cifar10_drift.ipynb
  notebooks/explainer_examples.ipynb
Labels: size/XXL

#3083 Updated tag 1.8.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/reference/drift-gpu.png
  doc/source/reference/release-1.6.0.md
  doc/source/reference/release-1.7.0.md
  doc/source/reference/release-highlights.rst
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/mean_classifier/image_metadata.json
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-abtest/values.yaml
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/README.md
  helm-charts/seldon-mab/values.yaml
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/tfserving_proxy/image_metadata.json
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/L

#3089 rclone-based storage initializer - first steps
  ci_build_and_push_images.sh
  components/rclone-storage-initializer/Dockerfile
  components/rclone-storage-initializer/Makefile
  components/rclone-storage-initializer/readme.md
Labels: size/L

#3088 note on scaling request logger
  components/seldon-request-logger/README.md
Labels: size/S

#3090 fix kustomize patch to include storageInitializerImage in the CRD
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  notebooks/explainer_examples.ipynb
  operator/config/crd/patches/graph_children.yaml
  operator/config/crd_v1/patches/graph_children.yaml
Labels: approved, size/L

#3086 Add note on storageInitializerImage to release-1.7.0 highlights
  doc/source/reference/release-1.7.0.md
Labels: size/S

#3085 Merge pull request #3060 from cliveseldon/3033_gpu_drift
  components/alibi-detect-server/Dockerfile.gpu
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/__main__.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/requirements-gpu.txt
  components/drift-detection/nvidia-triton-cifar10/cifar10_drift.ipynb
  notebooks/explainer_examples.ipynb
Labels: size/XXL

#3074 Update python server docs
  doc/source/python/api/seldon_core.rst
  doc/source/python/python_server.md
Labels: approved, size/S

#3093 Increasing memory of notebook tests
  .lighthouse/jenkins-x/notebooks.yaml
Labels: size/XS

#3095 Add raw_data parameter to SeldonClient predict
  examples/models/sklearn_iris/sklearn_iris.ipynb
  python/seldon_core/seldon_client.py
  python/tests/test_seldon_client.py
Labels: approved, size/L

#3094 Fix grammar
  doc/source/servers/mlflow.md
Labels: needs-ok-to-test, size/XS
