Repository SeldonIO/seldon-core, pull requests merged in 2021-07, with the labels that each got.

#3361 Updated documentation google tag
  doc/source/conf.py
Labels: size/XS

#3365 Fix docs
  doc/source/examples/notebooks.rst
Labels: size/S

#3363 add ansible runbook for Seldon Core minimal example
  notebooks/ansible/.gitignore
  notebooks/ansible/ansible.cfg
  notebooks/ansible/core.yaml
  notebooks/ansible/inventory.ini
  notebooks/ansible/seldon-core.ipynb
  notebooks/ansible/sklearn.yaml
Labels: size/XL

#3376 Updated core builder to 3.7.10
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .lighthouse/jenkins-x/benchmark.yaml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  ci_build_and_push_images.sh
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Dockerfile.gpu
  core-builder/Dockerfile
  core-builder/Makefile
  python/licenses/license_info.no_versions.csv
  testing/scripts/Makefile
Labels: size/M

#3380 Updating Python images to 3.7.10 (including python builder and python wrapper + dependent images)
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  ci_build_and_push_images.sh
  python-builder/Dockerfile
  python-builder/Makefile
Labels: size/M

#3381 Updating all python wrappers to use new base 3.7.10 (including all dependent images)
  ci_build_and_push_images.sh
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/Makefile
  examples/models/mean_classifier/Makefile
  servers/sklearnserver/Makefile
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Dockerfile.local
  wrappers/s2i/python/Dockerfile.redhat
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/build_scripts/build_all.sh
  wrappers/s2i/python/build_scripts/build_all_local.sh
  wrappers/s2i/python/build_scripts/build_conda_base.sh
  wrappers/s2i/python/build_scripts/build_local_python3.7.sh
  wrappers/s2i/python/build_scripts/build_local_redhat.sh
  wrappers/s2i/python/build_scripts/build_python3.7.sh
  wrappers/s2i/python/build_scripts/build_python3.7_gpu.sh
  wrappers/s2i/python/build_scripts/build_redhat.sh
  wrappers/s2i/python/build_scripts/push_python3.7.sh
  wrappers/s2i/python/build_scripts/push_python3.7_gpu.sh
Labels: size/M

#3387 Updating Argo Workflows link since repo renamed
  examples/cicd/cicd-argocd/argo/start-argo
  examples/cicd/cicd-argocd/argo/stop-argo
  testing/scripts/conftest.py
Labels: size/XS

#3388 Update MLServer link
  doc/source/conf.py
Labels: size/XS

#3351 Add Azure Monitoring section in GPT2 on Azure notebook
  examples/triton_gpt2/GPT2-ONNX-Azure.ipynb
  examples/triton_gpt2/SeldonMetricsDashboard.json
  examples/triton_gpt2/azure-metrics-cm.yaml
  examples/triton_gpt2/azure.jpg
  examples/triton_gpt2/azuredashboard.jpg
Labels: needs-ok-to-test, size/XL

#3392 Added updates to push 0.4.2 java wrapper
  incubating/wrappers/java/Makefile
  incubating/wrappers/java/src/main/java/io/seldon/wrapper/api/ModelPredictionController.java
  incubating/wrappers/java/src/test/java/io/seldon/wrapper/grpc/GrpcServiceTest.java
Labels: size/S

#3390 include seldon-puid in grpc headers
  examples/batch/argo-workflows-batch/README.ipynb
  examples/batch/argo-workflows-batch/README.md
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  executor/api/grpc/kfserving/server.go
  executor/api/grpc/seldon/server.go
  executor/samples/local/graph/Makefile
  executor/samples/local/graph/Model.py
  executor/samples/local/graph/model.yaml
  executor/samples/local/kfserving/Makefile
  executor/samples/local/kfserving/model.yaml
  testing/benchmarking/automated-benchmark/README.ipynb
  testing/scripts/test_notebooks.py
Labels: approved, size/M

#3400 Fixing broken links causings docs lint/build tests failure
  doc/source/examples/triton_gpt2_example_azure.nblink
  doc/source/reference/images.md
  examples/models/statsmodels/statsmodels.ipynb
  examples/streaming/knative-eventing/README.ipynb
  examples/triton_gpt2/GPT2-ONNX-Azure.ipynb
Labels: size/S

#3356 adding multiple grpc connections for python server and executor client
  examples/models/testing/Makefile
  examples/triton_gpt2/AzureSetup.ipynb
  examples/triton_gpt2/GPT2-ONNX-Azure.ipynb
  examples/upgrade-to-rclone/global-rclone-upgrade.ipynb
  executor/api/grpc/seldon/client.go
  helm-charts/seldon-benchmark-workflow/templates/workflow.yaml
  python/seldon_core/microservice.py
  python/seldon_core/wrapper.py
  testing/benchmarking/automated-benchmark/README.ipynb
  testing/benchmarking/python/python_serialization.ipynb
  testing/scripts/Makefile
  testing/scripts/kind_test_all.sh
  testing/scripts/test_benchmark.py
Labels: approved, ok-to-test, size/XL

#3407 Upgrade Alibi to 0.6.0
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/alibiexplainer/anchor_text.py
  components/alibi-explain-server/alibiexplainer/explainer.py
  components/alibi-explain-server/alibiexplainer/proto/tensorflow/core/framework/types.proto
  components/alibi-explain-server/alibiexplainer/server.py
  components/alibi-explain-server/setup.py
  components/alibi-explain-server/tests/test_ale.py
  components/alibi-explain-server/tests/test_anchor_images.py
  components/alibi-explain-server/tests/test_anchor_tabular.py
  components/alibi-explain-server/tests/test_anchor_text.py
  components/alibi-explain-server/tests/test_integrated_gradients.py
  components/alibi-explain-server/tests/test_tree_shap.py
  doc/source/analytics/explainers.md
  doc/source/reference/upgrading.md
  doc/source/servers/sklearn.md
  doc/source/servers/xgboost.md
  notebooks/explainer_examples.ipynb
  servers/sklearnserver/sklearnserver/requirements.txt
  servers/xgboostserver/xgboostserver/requirements.txt
Labels: size/XL

#3412 Return Child Node message upon error in Executor
  executor/predictor/predictor_process.go
Labels: needs-ok-to-test, size/XS

#3406 fix push of conda base image
  testing/scripts/Makefile
  wrappers/s2i/python/Dockerfile.local
  wrappers/s2i/python/Dockerfile.redhat
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/README.md
  wrappers/s2i/python/build_scripts/build_all_local.sh
  wrappers/s2i/python/build_scripts/build_local_redhat.sh
  wrappers/s2i/python/build_scripts/push_all.sh
  wrappers/s2i/python/build_scripts/push_conda_base.sh
Labels: size/M

#3416 update timeouts notebook for 30sec delayed model
  notebooks/resources/model_long_timeouts.json
  notebooks/resources/model_short_timeouts.json
  notebooks/timeouts.ipynb
Labels: size/L

#3419 Revert "Sherif akoush issue/2621/refactor env var retrieval"
  components/alibi-detect-server/adserver/cm_model.py
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/requirements-dev.txt
  python/seldon_core/env_utils.py
  python/seldon_core/metrics.py
  python/seldon_core/utils.py
  python/seldon_core/wrapper.py
  python/tests/test_model_microservice.py
  python/tests/test_utils.py
Labels: size/XL

#3423 Request Logger JsonData Fix
  components/seldon-request-logger/Dockerfile
  components/seldon-request-logger/Makefile
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
  components/seldon-request-logger/app/tests.py
Labels: approved, size/L

#3430 Fix alertmanager alert context "unkown -> unknown"
  helm-charts/seldon-core-analytics/files/prometheus/prometheus-config.yaml
  helm-charts/seldon-core-analytics/files/prometheus/rules.default/cpu-usage.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules.default/instance-availability.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules.default/low-disk-space.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules.default/mem-usage.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules/cpu-usage.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules/instance-availability.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules/low-disk-space.rules.yml
  helm-charts/seldon-core-analytics/files/prometheus/rules/mem-usage.rules.yml
  monitoring/prometheus/rules.default/cpu-usage.rules
  monitoring/prometheus/rules.default/instance-availability.rules
  monitoring/prometheus/rules.default/low-disk-space.rules
  monitoring/prometheus/rules.default/mem-usage.rules
Labels: approved, lgtm, size/M

#3433 Added dynamic documentation search
  doc/requirements.txt
  doc/source/conf.py
Labels: size/XS

#3431 Removing trailing slash to tensorflow serving URL in status addressable
  operator/utils/utils.go
  operator/utils/utils_test.go
Labels: size/XS

#3437 Disable parallel documentation build
  doc/Makefile
Labels: size/XS

#3420 Sherif akoush issue/2621/refactor env var retrieval
  components/alibi-detect-server/adserver/cm_model.py
  python/requirements-dev.txt
  python/seldon_core/env_utils.py
  python/seldon_core/metrics.py
  python/seldon_core/utils.py
  python/seldon_core/wrapper.py
  python/tests/test_model_microservice.py
  python/tests/test_utils.py
Labels: size/L
