Repository SeldonIO/seldon-core, pull requests merged in 2021-09, with the labels that each got.

#3560 Adding elastic loggging for drift detector data
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
  components/seldon-request-logger/app/log_mapping.py
  notebooks/explainer_examples.ipynb
  testing/benchmarking/logger/kafka.ipynb
Labels: size/M, approved

#3566 Add elastic logging for reference data logs
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
Labels: size/M, approved

#3564 Splitting feature level drift metrics in seldon request logger
  components/seldon-request-logger/app/default_logger.py
Labels: size/M, approved, lgtm

#3568 Fix rbac for leadership election
  helm-charts/seldon-core-operator/templates/role_seldon-leader-election-role.yaml
  operator/config/rbac/leader_election_role.yaml
Labels: size/S

#3471 Auto set GOMAXPROCS based on container limits in executor and operator
  executor/cmd/executor/main.go
  executor/cmd/proxy/main.go
  executor/go.mod
  executor/go.sum
  executor/licenses/additional_license_info.csv
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/go.mod
  operator/go.sum
  operator/main.go
Labels: size/L

#3571 Update kind
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .lighthouse/jenkins-x/benchmark.yaml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/models.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
  core-builder/Dockerfile
  core-builder/Makefile
  testing/resources/kind_config.yaml
  testing/scripts/test_operator_updates.py
Labels: size/M, approved

#3577 Allow user customize LeaderElectionID
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
  operator/main.go
Labels: size/S, needs-ok-to-test

#3580 bump up mlserver image version to 0.4.1
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/S

#3570 fix server version check for operator
  operator/utils/k8s/crd.go
  operator/utils/k8s/utils.go
  operator/utils/k8s/utils_test.go
  operator/utils/k8s/webhook.go
Labels: size/L

#3578 transmit event key from input topic to output topic in kafka
  executor/api/kafka/server.go
  executor/api/kafka/worker.go
Labels: size/XS, needs-ok-to-test

#3594 Fixed Python Component document typo
  doc/source/python/python_component.md
Labels: size/XS, approved

#3593 add note on SO_REUSEPORT requirement
  doc/source/reference/upgrading.md
Labels: size/XS

#3591 Python38 as default
  doc/source/reference/images.md
  doc/source/reference/upgrading.md
  wrappers/s2i/python/Makefile
  wrappers/s2i/python/build_scripts/build_all.sh
  wrappers/s2i/python/build_scripts/push_all.sh
Labels: size/S, approved

#3606 fix no-auth feature distribution
  components/seldon-request-logger/app/log_mapping.py
Labels: size/XS, approved

#3607 Bugfix request logger
  components/seldon-request-logger/app/default_logger.py
Labels: size/S, approved

#3608 Bump MLServer version to 0.5.0
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/S, approved

#3610 Release 1.12.0-dev tag
  CHANGELOG.md
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/reference/images.md
  doc/source/reference/upgrading.md
  doc/source/servers/kfserving-storage-initializer.md
  doc/source/servers/overview.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/mean_classifier/image_metadata.json
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/upgrade-to-rclone/global-rclone-upgrade.ipynb
  examples/upgrade-to-rclone/rclone-upgrade.ipynb
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-abtest/values.yaml
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/values.yaml
  operator/Dockerfile.redhat
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/tfserving_proxy/image_metadata.json
  servers/xgboostserver/xgboostserver/image_metadata.json
  testing/resources/adserver-cifar10-od-rclone.yaml
  testing/resources/adserver-cifar10-od.yaml
  version.txt
Labels: size/L, approved

#3619 Added GOMAXPROCS for CI pipeline jobs in JX
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M

#3617 Added python timeouts
  python/seldon_core/flask_utils.py
  python/seldon_core/microservice.py
Labels: size/S

#3624 update slack link
  doc/source/index.rst
Labels: size/XS
