Repository SeldonIO/seldon-core, pull requests merged in 2021-10, with the labels that each got.

#3623 Adding an interval config to batch processor component
  doc/source/servers/batch.md
  python/seldon_core/batch_processor.py
Labels: size/M, approved

#3628 bulk insert batch requests
  components/seldon-request-logger/app/default_logger.py
Labels: size/M

#3630 Updated broken links for Argo in docs to fix tests
  examples/cicd/sig-mlops-jenkins-classic/README.md
  examples/cicd/sig-mlops-jenkins-classic/jenkins_classic.ipynb
Labels: size/S

#3631 Updated batch processor e2e tests to include interval parameter
  testing/scripts/test_batch_processor.py
Labels: size/XS

#3549 build alibi explain server using poetry
  .github/workflows/alibiexplainer_tests.yml
  components/alibi-explain-server/.gitignore
  components/alibi-explain-server/.tool-versions
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/README.md
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  components/alibi-explain-server/requirements-apis.txt
  components/alibi-explain-server/tests/test_ale.py
  components/alibi-explain-server/tests/test_anchor_images.py
  components/alibi-explain-server/tests/test_anchor_tabular.py
  components/alibi-explain-server/tests/test_anchor_text.py
  components/alibi-explain-server/tests/test_integrated_gradients.py
  components/alibi-explain-server/tests/test_kernel_shap.py
  components/alibi-explain-server/tests/test_tree_shap.py
  python-builder/Dockerfile
  python-builder/Makefile
Labels: size/XXL, approved

#3614 use ipv4 protocol (for systems without ipv6)
  python/seldon_core/microservice.py
Labels: size/XS

#3638 Update release script to update on all images it builds
  ci_build_and_push_images.sh
Labels: size/M, approved
