Repository SeldonIO/seldon-core, pull requests merged in 2021-02, with the labels that each got.

#2906 Update cuda version in wrapper Dockerfile.GPU
  wrappers/s2i/python/Dockerfile.gpu
Labels: approved, ok-to-test, size/XS

#2916 update licenses for 1.6.0
  executor/licenses/additional_license_info.csv
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/licenses/additional_license_info.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
Labels: approved, size/XXL

#2918 yum update seemingly not needed for operator
  operator/Dockerfile.redhat
Labels: size/XS

#2917 tag all images as 1.2.4
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/deep_mnist/Makefile
  examples/models/mean_classifier/image_metadata.json
  examples/models/nvidia-mnist/Makefile
  examples/models/nvidia-mnist/nvidia_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/sk_mnist/Makefile
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_iris_jsondata/sklearn_iris_jsondata.ipynb
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  executor/Dockerfile.redhat
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  integrations/tfserving/image_metadata.json
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: size/L

#2920 Fixing typo on knative_eventing.md
  doc/source/streaming/knative_eventing.md
Labels: needs-ok-to-test, size/S

#2905 Updated CR
  doc/source/reference/seldon-deployment.rst
Labels: size/XS

#2915 Update keda_prom_auto_scale.ipynb to fix keda config in the doc
  examples/keda/keda_prom_auto_scale.ipynb
Labels: ok-to-test, size/XS

#2922 Add summary metrics to executor
  doc/source/analytics/analytics.md
  doc/source/examples/metrics.nblink
  examples/models/metrics/general_metrics.ipynb
  executor/api/metric/client.go
  executor/api/metric/constants.go
  executor/api/metric/server.go
  executor/api/rest/client.go
  executor/api/rest/server.go
  executor/samples/local/metrics/Makefile
  executor/samples/local/metrics/model.yaml
  testing/scripts/test_notebooks.py
Labels: size/L

#2925 Updated 1.7.0 tag and added release notes
  doc/source/python/python_wrapping_s2i.md
  doc/source/reference/images.md
  doc/source/reference/release-1.6.0.md
  doc/source/reference/release-highlights.rst
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/pom.xml
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/statsmodels/statsmodels.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  examples/ray/batch-split-proxy/ray-proxy.ipynb
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  version.txt
Labels: size/L

#2898 feat(examples/pachyderm-cd4ml): Add demo of redeploying old model
  examples/pachyderm-cd4ml/index.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/XL

#2946 Update OWNERS to add Ivan
  OWNERS
Labels: size/XS

#2948 Change hashicorp/hcl dependency url to match new main branch
  executor/Dockerfile.executor
  executor/Dockerfile.executor.redhat
  operator/Dockerfile
  operator/Dockerfile.redhat
Labels: approved, size/XS

#2949 Fix version in files: 1.7.0-dev
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/models/mean_classifier/image_metadata.json
  executor/Dockerfile.executor.redhat
  helm-charts/seldon-abtest/values.yaml
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/values.yaml
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/tfserving_proxy/image_metadata.json
  servers/xgboostserver/xgboostserver/image_metadata.json
Labels: approved, size/M

#2940 Extract SeldonPodSpec Metadata into custom struct to allow structural CRD schema
  executor/api/metric/client_test.go
  executor/api/rest/client_test.go
  executor/go.mod
  executor/go.sum
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/controller_utils.go
  operator/controllers/replicas_test.go
  operator/controllers/seldondeployment_controller_test.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: size/XXL

#2972 Fix elasticsearch index
  components/alibi-detect-server/adserver/cm_model.py
Labels: approved, lgtm, ok-to-test, size/XS

#2941 Seldon CRD Status Removal
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/Makefile
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_webhook.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/status.json
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/kustomization.yaml
  operator/config/crd_v1/patches/protocol.yaml
  operator/config/crd_v1/patches/status.json
  operator/config/machinelearning.seldon.io_seldondeployments.yaml
Labels: approved, ok-to-test, size/XXL

#2970 Addressing CVEs from Python base Image
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
  README.md
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/setup.py
  testing/scripts/Makefile
Labels: size/L

#2973 Amended docker mount folder for CI builds
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS

#2974 Updated PIP in base image to align with Python Cryptography Framework version
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/Makefile
  doc/source/reference/upgrading.md
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Dockerfile.redhat
Labels: size/S

#2954 Remove managedFields from seldon pod spec metadata
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: size/L

#2947 Fix concurrent map writes in executor
  executor/predictor/predictor_process.go
Labels: size/M

#2977 Addressing CVEs for Redhat Python based images
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
  ci_build_and_push_images.sh
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/seldon-request-logger/requirements.txt
  components/storage-initializer/Dockerfile
  examples/models/chainer_mnist/chainer_mnist.ipynb
  examples/models/custom_metrics/Makefile
  examples/models/metadata/models/generic-node/Makefile
  examples/models/metadata/models/init-metadata/Makefile
  examples/models/runtime_metrics_tags/runtime_metrics_tags.ipynb
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris_customdata/Makefile
  examples/models/sklearn_iris_customdata/sklearn_iris_customdata.ipynb
  examples/models/sklearn_iris_jsondata/Makefile
  examples/models/sklearn_spacy_text/sklearn_spacy_text_classifier_example.ipynb
  examples/models/statsmodels/statsmodels.ipynb
  examples/models/xss/Makefile
  examples/models/xss/xss-example.ipynb
  examples/output_transformers/Makefile
  examples/ray/batch-split-proxy/ray-proxy.ipynb
  python-builder/Dockerfile
  python-builder/Makefile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/setup.py
  servers/mlflowserver/mlflowserver/requirements.txt
  testing/docker/echo-model/Makefile
  testing/docker/fixed-model/Makefile
  testing/scripts/test_seldon_metadata.py
  testing/scripts/test_tags.py
  wrappers/s2i/python/Dockerfile.redhat
Labels: size/L

#2923 opendistro elastic
  .gitignore
  components/alibi-detect-server/adserver/cm_model.py
  doc/source/analytics/logging.md
  examples/centralised-logging/README.md
  examples/centralised-logging/elastic-kind.yaml
  examples/centralised-logging/elastic-minikube.yaml
  examples/centralised-logging/fluentd-values.yaml
  examples/centralised-logging/full-kind-setup.sh
  examples/centralised-logging/install_istio.sh
  examples/centralised-logging/install_knative.sh
  examples/centralised-logging/kibana-virtualservice.yaml
  examples/centralised-logging/kind_config.yaml
  examples/centralised-logging/seldon-request-logger-k8s.yaml
  examples/centralised-logging/seldon-request-logger.yaml
  examples/centralised-logging/values-opendistro-kind.yaml
  examples/feedback/feedback-metrics-server/README.ipynb
  examples/feedback/feedback-metrics-server/README.md
  examples/feedback/feedback-metrics-server/config/multiclass-deployment.yaml
  examples/feedback/feedback-metrics-server/config/multiclass-service.yaml
  examples/feedback/feedback-metrics-server/config/trigger.yaml
Labels: approved, size/XXL

#2981 Change version of JNI build image
  doc/source/java-jni/README.md
  incubating/wrappers/java/pom.xml
  incubating/wrappers/s2i/java-jni/Dockerfile.build
  incubating/wrappers/s2i/java-jni/Dockerfile.runtime
  incubating/wrappers/s2i/java-jni/Makefile
  incubating/wrappers/s2i/java-jni/s2i/bin/assemble
  incubating/wrappers/s2i/java-jni/s2i/bin/assemble-runtime
  incubating/wrappers/s2i/java-jni/s2i/bin/run
  incubating/wrappers/s2i/java-jni/test/model-template-app/Makefile
  incubating/wrappers/s2i/java-jni/test/model-template-app/pom.xml
  testing/s2i/java/pom.xml
  testing/scripts/test_s2i_java.py
Labels: size/L

#2976 Change seldon-core-microservice to spot unknown args
  python/seldon_core/microservice.py
Labels: approved, size/XS

#2618 feat(svc): Add predictorSpec annotations to service
  operator/controllers/seldondeployment_controller.go
Labels: ok-to-test, size/S

#2937 Extend CRD: allow to define storageInitializerImage in the graph definition
  doc/source/servers/overview.md
  examples/init_containers/Makefile
  examples/init_containers/custom_init_container.ipynb
  examples/init_containers/rclone-default-init.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/Makefile
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/model_initializer_injector.go
  operator/controllers/model_initializer_injector_test.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/go.sum
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: approved, size/L
