Repository SeldonIO/seldon-core, pull requests merged in 2021-05, with the labels that each got.

#3166 Explicit mapping for elasticsearch Indexes in request logger component
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_mapping.py
Labels: size/L

#3163 Documentation updates for the Ambassador Install process and to introduce CRD based config.
  doc/source/ingress/ambassador.md
  examples/ambassador/custom/ambassador_custom.ipynb
  notebooks/seldon_core_setup.ipynb
Labels: needs-ok-to-test, size/L

#3171 include seldonio/rclone-storageinitializer in release.py script
  release.py
Labels: size/M

#3188 update docs
  doc/source/ingress/istio.md
Labels: needs-ok-to-test, size/M

#3172 include rclone in adserver
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/adserver/ad_model.py
  components/alibi-detect-server/adserver/base/alibi_model.py
  components/alibi-detect-server/adserver/base/storage.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/cm_model.py
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/setup.py
  components/drift-detection/cifar10/cifar10_drift.ipynb
  components/outlier-detection/cifar10/cifar10_outlier.ipynb
  components/outlier-detection/nvidia-triton-cifar10/cifar10_outlier.ipynb
  components/rclone-storage-initializer/Dockerfile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  testing/resources/adserver-cifar10-od-rclone.yaml
  testing/resources/adserver-cifar10-od.yaml
  testing/scripts/seldon_e2e_utils.py
  testing/scripts/test_alibi_detect_server.py
Labels: size/XXL

#3191 update community call calendar
  doc/source/developer/community.md
Labels: size/XS

#3153 ensure http and grpc envs are used
  helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/apis/machinelearning.seldon.io/v1/defaults_test.go
  operator/config/manager/manager.yaml
  operator/controllers/seldondeployment_explainers.go
  operator/helm/split_resources.py
Labels: size/M

#3200 Allow leader election to use configurable seldon-manager service account
  helm-charts/seldon-core-operator/templates/rolebinding_seldon-leader-election-rolebinding.yaml
  operator/helm/split_resources.py
Labels: size/XS

#3203 make rclone storage initializer more verbose
  components/alibi-detect-server/adserver/base/storage.py
  components/rclone-storage-initializer/Dockerfile
Labels: size/XS

#3205 Fix operator image build for redhat
  operator/Dockerfile.redhat
Labels: size/XS

#3160 Update Alibi-Detect to 0.6.2
  components/alibi-detect-server/adserver/ad_model.py
  components/alibi-detect-server/adserver/base/__init__.py
  components/alibi-detect-server/adserver/base/model.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/cm_model.py
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/adserver/protocols/request_handler.py
  components/alibi-detect-server/adserver/protocols/seldonfeedback_http.py
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_ad_model.py
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/adserver/tests/test_od_model.py
  components/alibi-detect-server/adserver/tests/test_server.py
  components/alibi-detect-server/requirements_server.txt
  components/alibi-detect-server/setup.py
  components/drift-detection/cifar10/cifar10_drift.ipynb
  components/outlier-detection/cifar10/cifar10_outlier.ipynb
  python/Makefile
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/seldon_core/seldon_client.py
  testing/scripts/test_alibi_detect_server.py
  testing/scripts/test_operator_updates.py
Labels: size/XXL

#3209 Tfserving proxy custom data
  servers/tfserving_proxy/TfServingProxy.py
Labels: ok-to-test, size/L

#3183 request logger metadata lookup
  components/seldon-request-logger/Makefile
  components/seldon-request-logger/README.md
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_mapping.py
  components/seldon-request-logger/requirements.txt
  components/seldon-request-logger/testing/create_dummy_metadata.py
  components/seldon-request-logger/testing/deploy_model.sh
  components/seldon-request-logger/testing/test.sh
Labels: approved, size/L

#3217 Gpt2 notebook example
  examples/triton_gpt2/README.ipynb
Labels: approved, size/L

#3222 Converting model predictions schema to dict in request logger processing
  components/seldon-request-logger/app/log_mapping.py
Labels: approved, size/XS

#3220 Tensorflow multi-model server
  doc/source/servers/tensorflow.md
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  notebooks/protocol_examples.ipynb
Labels: approved, size/L

#3219 Start 190 dev
  .lighthouse/jenkins-x/notebooks.yaml
  CHANGELOG.md
  components/alibi-detect-server/Dockerfile
  components/alibi-explain-server/Dockerfile
  components/seldon-request-logger/Dockerfile
  components/storage-initializer/Dockerfile
  doc/source/python/python_wrapping_s2i.md
  doc/source/reference/upgrading.md
  doc/source/servers/overview.md
  doc/source/workflow/overview.md
  doc/source/workflow/quickstart.md
  engine/Dockerfile.redhat
  engine/pom.xml
  examples/batch/hdfs-argo-workflows/hdfs-batch.ipynb
  examples/batch/kubeflow-pipelines-batch/README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/image_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/models/news_classifier/seldon_custom_server_README.ipynb
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/Makefile
  examples/cicd/sig-mlops-jenkins-classic/servers/torchserver/test/sklearn_iris.ipynb
  examples/cicd/sig-mlops-seldon-jenkins-x/seldon_custom_server_README.ipynb
  examples/explainers/imagenet/resources/transformer/Makefile
  examples/feedback/reward-accuracy/README.ipynb
  examples/kubeflow/kubeflow_seldon_e2e_pipeline.ipynb
  examples/models/alibaba_ack_deep_mnist/alibaba_cloud_ack_deep_mnist.ipynb
  examples/models/aws_eks_deep_mnist/aws_eks_deep_mnist.ipynb
  examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb
  examples/models/mean_classifier/image_metadata.json
  examples/models/resnet/Makefile
  examples/models/resnet/reset.ipynb
  executor/Dockerfile.executor.redhat
  hack/update_python_version.sh
  helm-charts/seldon-abtest/values.yaml
  helm-charts/seldon-core-analytics/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/values.yaml
  operator/Dockerfile.redhat
  operator/config/manager/configmap.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  python/seldon_core/version.py
  python/setup.py
  servers/mlflowserver/mlflowserver/image_metadata.json
  servers/sklearnserver/sklearnserver/image_metadata.json
  servers/tfserving/Dockerfile.redhat
  servers/tfserving_proxy/image_metadata.json
  servers/xgboostserver/xgboostserver/image_metadata.json
  version.txt
Labels: approved, size/XXL

#3231 option to skip verify ssl on req logger
  components/seldon-request-logger/app/log_mapping.py
Labels: size/XS

#3239 update notebooks to use port 8080 for istio
  notebooks/backwards_compatability.ipynb
  notebooks/istio_example.ipynb
  notebooks/protocol_examples.ipynb
  notebooks/scale.ipynb
  notebooks/triton_examples.ipynb
Labels: size/S
