Repository SeldonIO/seldon-core, pull requests merged in 2022-06, with the labels that each got.

#4135 update kind
  ansible/playbooks/kind_cluster.yaml
Labels: size/XS, approved

#4117 Add optional manual commit to seldon kafka server
  executor/api/kafka/server.go
  executor/api/kafka/worker.go
  executor/cmd/executor/main.go
Labels: size/M, approved, needs-ok-to-test

#4139 Fix. Ensemble model. Previouse not saved data in jagear. Working with…
  examples/models/openvino_imagenet_ensemble/openvino_imagenet_ensemble.ipynb
  examples/models/openvino_imagenet_ensemble/seldon_ov_predict_ensemble.yaml
Labels: size/L, approved, needs-ok-to-test

#4142 fix alibi tests
  testing/resources/iris_anchor_tabular_explainer.yaml
  testing/resources/tf_cifar_anchor_image_explainer.yaml
Labels: size/S

#4107 fix transport missing in executor
  examples/kafka/cifar10/cifar10_kafka.ipynb
  examples/kafka/cifar10/cluster-cloud.yaml
  examples/kafka/cifar10/cluster-kind.yaml
  operator/controllers/seldondeployment_engine.go
Labels: size/XXL

#4145 Fix typo in error message for Anchor tabular
  components/alibi-explain-server/alibiexplainer/anchor_tabular.py
Labels: size/XS, approved

#4144 Create graph-modes.md
  doc/source/graph/graph-modes.md
  doc/source/nav/config/deployments.rst
Labels: size/L, approved, needs-ok-to-test

#4136 Upgrade to k8s 0.23 APIs, remove v1beta1 as default, upgrade KEDA
  doc/source/reference/upgrading.md
  executor/cmd/proxy/main.go
  executor/go.mod
  executor/go.sum
  executor/licenses/additional_license_info.csv
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  notebooks/seldon_core_setup.ipynb
  notebooks/server_examples.ipynb
  operator/Dockerfile
  operator/Makefile
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/cainjection_in_seldondeployments.yaml
  operator/config/crd/patches/graph.json
  operator/config/crd/patches/graph_children.yaml
  operator/config/crd/patches/preserve_ukn_fields.yaml
  operator/config/crd/patches/protocol.yaml
  operator/config/crd/patches/structural.json
  operator/config/crd/patches/structural2.json
  operator/config/crd/patches/volumes.json
  operator/config/crd/patches/webhook_in_seldondeployments.yaml
  operator/config/crd_v1/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1/kustomization.yaml
  operator/config/crd_v1/kustomizeconfig.yaml
  operator/config/crd_v1/patches/cainjection_in_seldondeployments.yaml
  operator/config/crd_v1/patches/graph_children.yaml
  operator/config/crd_v1/patches/status.json
  operator/config/crd_v1_small/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/cleaners_test.go
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/helm/Makefile
  operator/licenses/additional_license_info.csv
  operator/licenses/dep.txt
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
  operator/main.go
  operator/testing/istio-crd-10.yaml
  operator/testing/istio-crd.yaml
  operator/testing/keda.sh_scaledobjects.yaml
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  operator/utils/k8s/crd.go
  operator/utils/k8s/crd_test.go
  operator/utils/k8s/initializer.go
Labels: size/XXL

#4148 Bump MLServer version to 1.1.0
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  operator/controllers/mlserver.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  testing/resources/iris_anchor_tabular_explainer_v2.yaml
  testing/resources/tf_cifar_anchor_image_explainer_v2.yaml
Labels: size/M, approved

#4155 fix broken mlflow model build
  servers/mlflowserver/models/elasticnet_wine/Makefile
  servers/mlflowserver/models/elasticnet_wine/requirements.txt
Labels: size/XS, approved

#4157 Fixed operator redhat image
  operator/Dockerfile.redhat
Labels: size/XS, approved

#4161 update rest_predict_seldon wrong hardcoded version in route
  python/seldon_core/seldon_client.py
Labels: size/XS, needs-ok-to-test

#4170 [Doc] Add missing yaml styling for code snippets
  doc/source/analytics/explainers.md
  doc/source/graph/graph-modes.md
  doc/source/graph/inference-graph.md
  doc/source/graph/scaling.md
  doc/source/ingress/istio.md
  doc/source/ingress/openshift.md
  doc/source/servers/tensorflow.md
  doc/source/streaming/kafka.md
  operator/openshift.md
Labels: size/M, approved, needs-ok-to-test

#4196 fix link to minio example in triton page
  doc/source/servers/triton.md
Labels: size/XS, needs-ok-to-test

#4195 typo fix in logging number of gRPC workers
  python/seldon_core/microservice.py
Labels: size/XS, approved, needs-ok-to-test

#4194 typo fix in logging number of gRPC threads used
  python/seldon_core/microservice.py
Labels: size/XS, approved, needs-ok-to-test
