Repository SeldonIO/seldon-core, pull requests merged in 2022-03, with the labels that each got.

#3971 Issue #3968: Allow hostNetwork=true for seldon operator
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/default/manager_prometheus_metrics_patch.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: size/M, approved, needs-ok-to-test

#3780 support traffic settings for shadow deployment with istio
  examples/istio/shadow/.gitignore
  examples/istio/shadow/README.md
  examples/istio/shadow/istio_shadow.ipynb
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
  operator/controllers/seldondeployment_controller.go
Labels: size/XL, approved, needs-ok-to-test

#3991 Fixing nbqa linting for latest notebook
  doc/source/examples/notebooks.rst
  examples/kafka/kafka_keda/cifar10_kafka.ipynb
  testing/scripts/README.md
Labels: size/S

#3992 added tag for s2i python image
  doc/source/wrappers/s2i.md
Labels: size/XS

#3990 Bumping rclone image version to 1.57.0
  components/rclone-storage-initializer/Dockerfile
Labels: size/XS, approved

#3987 Release v1.13.1 for OpenShift
  components/rclone-storage-initializer/Dockerfile.redhat
  components/rclone-storage-initializer/Makefile
  marketplaces/redhat/scan-images.py
  operator/Makefile
  operator/bundle-certified/manifests/seldon-operator-certified.clusterserviceversion.yaml
  operator/bundle-certified/metadata/annotations.yaml
  operator/bundle.Dockerfile
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/manifests/bases/seldon-operator.clusterserviceversion.yaml
  operator/config/openshift/patch_manager_env.yaml
  operator/openshift.md
  operator/openshift/tests/catalog-source-olm.yaml
  operator/openshift/tests/operator-group-olm.yaml
  operator/openshift/tests/operator-subscription-olm.yaml
Labels: size/L

#3995 Update sklearn iris example
  examples/models/sklearn_iris/Makefile
  examples/models/sklearn_iris/sklearn_iris.ipynb
  examples/models/sklearn_iris/sklearn_iris_deployment.yaml
Labels: size/L, approved

#4005 Decompress prediction events before logging to kafka topics
  executor/logger/worker.go
Labels: size/XS, approved
