Repository SeldonIO/seldon-core, pull requests merged in 2022-05, with the labels that each got.

#4075 Update seldon-deployment.rst
  doc/source/reference/seldon-deployment.rst
Labels: size/XS, approved

#4069 Pass through model name env var for MLServer
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  testing/docker/mock-preprocessor/Makefile
  testing/docker/mock-preprocessor/model-settings.json
  testing/resources/graph-v2.yaml
Labels: size/L

#4078 Fixed random seed for anchor explanation
  components/alibi-explain-server/alibiexplainer/anchor_images.py
  components/alibi-explain-server/alibiexplainer/anchor_tabular.py
  components/alibi-explain-server/alibiexplainer/anchor_text.py
Labels: size/S, approved

#4079 Adding configuration for feature level drift metrics
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/constants.py
Labels: size/S, approved

#4081 Huggingface optimum prepackaged server
  doc/source/nav/config/servers.rst
  doc/source/servers/huggingface.md
  helm-charts/seldon-core-operator/values.yaml
  operator/apis/machinelearning.seldon.io/v1/prepack.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/config/manager/configmap.yaml
  operator/controllers/mlserver.go
Labels: size/L, approved

#4089 respect envSecretRefName coming from helm values
  ansible/README.md
  ansible/playbooks/kind_cluster.yaml
  ansible/playbooks/kind_many_workers.yaml
  ansible/playbooks/main.yaml
  ansible/playbooks/seldon_core.yaml
  ansible/playbooks/vars/default.yaml
  doc/source/analytics/analytics.md
  examples/models/metrics/get-metrics.sh
  examples/models/metrics/metrics.ipynb
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
  operator/controllers/seldondeployment_prepackaged_servers.go
Labels: size/L

#4006 Sorted metric tags to avoid duplicate prom data with gRPC requests
  python/seldon_core/metrics.py
  python/tests/test_runtime_metrics_tags.py
Labels: size/S, approved, ok-to-test

#4099 Don't hardcode UID for Triton containers
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
Labels: size/S, approved

#4077 Adding protocol info to executor payload logging worker
  executor/cmd/executor/main.go
  executor/logger/dispatcher.go
  executor/logger/log_memory_benchmark_test.go
  executor/logger/worker.go
  executor/predictor/predictor_process_test.go
Labels: size/M, approved

#4094 Update cache folder and bump MLServer image
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  operator/controllers/mlserver.go
Labels: size/XS

#4114 use alternative multiprocessing library if USE_MULTIPROCESS_PACKAGE i…
  python/seldon_core/microservice.py
Labels: size/S
