Repository SeldonIO/seldon-core, pull requests merged in 2022-12, with the labels that each got.

#4464 Prefix v1 workflows
  .github/workflows/alibidetect_tests.yml
  .github/workflows/alibiexplainer_tests.yml
  .github/workflows/docs.yml
  .github/workflows/draft-release.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  .github/workflows/security_tests.yml
Labels: size/M, approved

#4463 Images update
  components/rclone-storage-initializer/Dockerfile
  executor/Dockerfile.executor.redhat
  marketplaces/redhat/Makefile
  marketplaces/redhat/scan-images.py
  operator/Dockerfile.redhat
Labels: size/S

#4467 adjust to executor use of ubi not ubi-minimal
  executor/Dockerfile.executor.redhat
Labels: size/XS

#4469 add placeholder for V2 image build workflow
  .github/workflows/images.yaml
Labels: size/S, approved

#4471 rename v2 images workflow extension
  .github/workflows/images.yml
Labels: size/XS, approved

#4470 fix image build
  .github/workflows/images.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: size/S

#4473 Do not include v1 changes in v2 changelog
  .github/workflows/draft-release.yml
Labels: size/XS

#4474 Do not include V1 changes in V2 changelog (#4473)
  .github/workflows/draft-release.yml
Labels: size/XS

#4475 add hint to v2 images workflow
  .github/workflows/images.yml
Labels: size/XS, approved

#4476 v2: Update API protocs with latest protoc
  apis/go/mlops/agent/agent.pb.go
  apis/go/mlops/agent/agent_grpc.pb.go
  apis/go/mlops/agent_debug/agent_debug.pb.go
  apis/go/mlops/agent_debug/agent_debug_grpc.pb.go
  apis/go/mlops/chainer/chainer.pb.go
  apis/go/mlops/chainer/chainer_grpc.pb.go
  apis/go/mlops/proxy/proxy.pb.go
  apis/go/mlops/proxy/proxy_grpc.pb.go
  apis/go/mlops/scheduler/scheduler.pb.go
  apis/go/mlops/scheduler/scheduler_grpc.pb.go
  apis/go/mlops/scheduler/storage.pb.go
  apis/go/mlops/v2_dataplane/v2_dataplane.pb.go
  apis/go/mlops/v2_dataplane/v2_dataplane_grpc.pb.go
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/ChainerOuterClass.java
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineStepUpdateKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineUpdateStatusMessageKt.kt
Labels: size/XL

#4485 Clarify use of SCv1 in Helm chart descriptions + fix typo
  helm-charts/README.md.tpl
  helm-charts/seldon-abtest/Chart.yaml
  helm-charts/seldon-benchmark-workflow/Chart.yaml
  helm-charts/seldon-core-loadtesting/Chart.yaml
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-mab/Chart.yaml
  helm-charts/seldon-od-model/Chart.yaml
  helm-charts/seldon-od-transformer/Chart.yaml
  helm-charts/seldon-openvino/Chart.yaml
  helm-charts/seldon-single-model/Chart.yaml
Labels: size/S, approved

#4490 Update readme with license and docs links
  README.md
Labels: size/XS

#4492 Temporary fix for envtest for operator
  operator/Makefile
Labels: size/XS

#4493 improve landing README
  README.md
Labels: size/S

#4491 v2: Autoscaling docs - small updates
  docs/source/contents/kubernetes/autoscaling/index.md
  docs/source/contents/models/index.md
  docs/source/contents/servers/index.md
Labels: size/XS

#4486 Fix typos in operator Helm chart for v1.15 release
  helm-charts/seldon-core-operator/Chart.yaml
  helm-charts/seldon-core-operator/README.md
Labels: size/XS

#4487 Return meaningful error on empty bucket sync for model uri
  samples/models/error-uri-notexist.yaml
  scheduler/pkg/agent/rclone/rclone.go
  scheduler/pkg/agent/rclone/rclone_test.go
  scheduler/pkg/agent/repository/mlserver/mlserver.go
  scheduler/pkg/agent/repository/model_repository.go
  scheduler/pkg/agent/repository/triton/triton.go
Labels: size/M

#4496 Enable GPU for docker-compose deployment
  docs/source/contents/getting-started/docker-installation/index.md
  scheduler/Makefile
  scheduler/all-gpu.yaml
Labels: size/S

#4481 [SCv2] Improve inference docs re routing and headers
  docs/source/contents/inference/index.md
Labels: Documentation, size/L, v2

#4483 limit changelog to current version
  create-changelog
Labels: size/XS, approved

#4480 update licenses for 1.15.0 release
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/XXL

#4502 Bump MLServer version to 1.2.1
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-benchmark-workflow/README.md
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-loadtesting/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  helm-charts/seldon-mab/README.md
  helm-charts/seldon-od-model/README.md
  helm-charts/seldon-od-transformer/README.md
  helm-charts/seldon-openvino/README.md
  helm-charts/seldon-single-model/README.md
  operator/config/manager/configmap.yaml
Labels: size/M, approved

#4503 Bump MLServer version to 1.2.1 (V2)
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
  scheduler/env.all
Labels: size/S

#4504 Add a notebook test for changing model replicas
  scheduler/notebooks/k8s-envoy-change-test.ipynb
Labels: size/L

#4501 Disable autoscaling tracking on agent for models that are fixed
  apis/go/mlops/agent/agent.pb.go
  apis/go/mlops/agent/agent_grpc.pb.go
  apis/mlops/agent/agent.proto
  scheduler/all-host-network.yaml
  scheduler/all-internal.yaml
  scheduler/cmd/scheduler/main.go
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/client_test.go
  scheduler/pkg/agent/server.go
  scheduler/pkg/agent/server_test.go
  scheduler/pkg/proxy/server.go
Labels: size/L, v2

#4498 Upgrading docker compose CLI command
  scheduler/Makefile
Labels: size/XS, needs-ok-to-test

#4509 V1.15.0 redhat release
  operator/bundle-certified.Dockerfile
  operator/bundle-certified/manifests/seldon-operator-certified.clusterserviceversion.yaml
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/openshift.md
Labels: size/L, approved

#4510 Openshift update
  operator/bundle-certified.Dockerfile
  operator/bundle-certified/manifests/seldon-operator-certified.clusterserviceversion.yaml
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/openshift.md
Labels: size/L, approved

#4511 Ensure x-request-id header matches kafka key
  scheduler/pkg/kafka/pipeline/kafkamanager.go
  scheduler/pkg/kafka/pipeline/utils.go
  scheduler/pkg/kafka/pipeline/utils_test.go
Labels: size/M, v2

#4515 Fix possible SIGSEV after producer close in modelgateway
  scheduler/pkg/kafka/gateway/infer.go
  scheduler/pkg/kafka/gateway/manager.go
  scheduler/pkg/kafka/gateway/worker.go
  scheduler/pkg/kafka/gateway/worker_test.go
Labels: size/M

#4516 Link how to install docker compose v2 from github releases
  docs/source/contents/getting-started/docker-installation/index.md
Labels: size/XS

#4523 v2: Update tls licenses and add summary
  Makefile
  components/tls/Makefile
  components/tls/licenses/license.txt
  components/tls/licenses/license_info.csv
  components/tls/licenses/repo.txt
  licenses/3rd-party-summary.txt
Labels: v2

#4512 Change stream id to use pipeline name
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Pipeline.kt
  scheduler/pkg/kafka/gateway/infer.go
Labels: size/XS, v2

#4529 v2: Add an example k8s server pvc example
  docs/source/contents/examples/index.md
  docs/source/contents/examples/k8s-pvc.md
  docs/source/contents/kubernetes/resources/server/index.md
  samples/examples/k8s-pvc/Makefile
  samples/examples/k8s-pvc/iris.yaml
  samples/examples/k8s-pvc/k8s-pvc.ipynb
  samples/examples/k8s-pvc/k8s-pvc.md
  samples/examples/k8s-pvc/kind-config.yaml
  samples/examples/k8s-pvc/pvc.yaml
  samples/examples/k8s-pvc/server.yaml
Labels: v2

#4530 Update controller gen and operator kubebuilder testing
  notebooks/protocol_examples.ipynb
  operator/Makefile
  operator/client/machinelearning.seldon.io/v1/clientset/versioned/fake/register.go
  operator/client/machinelearning.seldon.io/v1/clientset/versioned/scheme/register.go
  operator/client/machinelearning.seldon.io/v1alpha2/clientset/versioned/fake/register.go
  operator/client/machinelearning.seldon.io/v1alpha2/clientset/versioned/scheme/register.go
  operator/client/machinelearning.seldon.io/v1alpha3/clientset/versioned/fake/register.go
  operator/client/machinelearning.seldon.io/v1alpha3/clientset/versioned/scheme/register.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd_v1_small/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/rbac/role.yaml
  operator/config/webhook/manifests.yaml
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: v1

#4534 Update local-over-commit-test.ipynb
  scheduler/notebooks/local-over-commit-test.ipynb
Labels: v2

#4535 v2: Remove need for ONESHELL in go lint
  components/tls/Makefile
  hodometer/Makefile
  operator/Makefile
  scheduler/Makefile
Labels: v2

#4537 Fix annotation updates and redo semantic equality using patch checker
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/controllers/mlserver.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_engine.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/go.mod
  operator/go.sum
  operator/licenses/dep.txt
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
Labels: v1

#4500 Update markdown transforming sed scripts
  samples/Makefile
  samples/cli-tests.md
  samples/examples/huggingface/huggingface.ipynb
  samples/examples/huggingface/huggingface.md
  samples/examples/huggingface/test-transforms.md
  samples/examples/huggingface/train.md
  samples/examples/image_classifier/infer.md
  samples/examples/image_classifier/train.md
  samples/examples/income_classifier/infer-k8s.md
  samples/examples/income_classifier/infer.md
  samples/examples/income_classifier/infer_local.md
  samples/examples/income_classifier/train.md
  samples/examples/pandasquery/infer.md
  samples/examples/pandasquery/infer_local.md
  samples/experiment_versions.md
  samples/explainer-examples.md
  samples/huggingface.md
  samples/inference.md
  samples/k8s-batch-examples.md
  samples/k8s-examples.md
  samples/k8s-explainers.md
  samples/k8s-tritonclient-aio.md
  samples/k8s-tritonclient.md
  samples/local-examples.md
  samples/local-experiments.md
  samples/markdown-transforms.sh
  samples/markdown-transforms/coalesce-blank-lines.sed
  samples/markdown-transforms/format-bash-blocks.sed
  samples/markdown-transforms/format-output-blocks.sed
  samples/markdown-transforms/remove-trailing-whitespace.sed
  samples/metrics.md
  samples/pipeline-errors.md
  samples/pipeline-examples.md
  samples/pipeline-ready-and-metadata.md
  samples/pipeline-versions.md
  samples/python-examples.md
  samples/rolling-update.md
  samples/trigger_joins.md
Labels: enhancement, Documentation, size/XXL, v2
