Repository SeldonIO/seldon-core, pull requests merged in 2022-10, with the labels that each got.

#4390 Reverted Conda base image to 4.13.0 until patched in 4.14.0
  wrappers/s2i/python/Makefile
Labels: size/XS

#4343 Fix vim CVE in Alibi images
  README.md
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/Dockerfile
  doc/source/nav/archive.rst
  doc/source/tutorials/openshift_s2i.md
  examples/explainers/iris-explainer-poetry/iris-explainer.ipynb
  examples/mnist_triton_e2e/mnist-triton.ipynb
  examples/outliers/cifar10-od-poetry/cifar10-od.ipynb
  examples/pachyderm-cd4ml/index.ipynb
  examples/pachyderm-simple/index.ipynb
  examples/triton_gpt2/GPT2-ONNX-Azure.ipynb
  python-builder/Dockerfile
  python-builder/Makefile
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Dockerfile.conda
  wrappers/s2i/python/Makefile
Labels: size/XXL, approved

#4393 Fix Conda download version
  wrappers/s2i/python/Makefile
Labels: size/XS, approved

#4392 Openshift move to quay
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/Makefile
  components/rclone-storage-initializer/Makefile
  components/storage-initializer/Makefile
  examples/models/mean_classifier/Makefile
  executor/Makefile
  operator/Makefile
  operator/openshift.md
  servers/mlflowserver/Makefile
  servers/sklearnserver/Makefile
  servers/tfserving/Makefile
  servers/tfserving_proxy/Makefile
  servers/xgboostserver/Makefile
Labels: size/L, approved

#4405 Update libraries to solve CVEs reported for 1.15.0 build
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  servers/sklearnserver/sklearnserver/requirements.txt
Labels: size/XXL
