Repository SeldonIO/seldon-core, pull requests merged in 2022-09, with the labels that each got.

#4301 Ensure request is chained before payload is logged
  executor/licenses/dep.txt
  executor/predictor/predictor_process.go
Labels: size/S

#4271 Add UTF-8 support for Flask jsonify
  python/seldon_core/wrapper.py
Labels: size/XS, needs-ok-to-test

#4267 added comments about routing in predictChildren
  executor/predictor/predictor_process.go
Labels: size/S, needs-ok-to-test

#4235 Add progress deadline support for SDeps
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/webhook/manifests.yaml
  operator/controllers/seldondeployment_controller.go
Labels: size/L

#4325 Add reference for V2 Inference Protocol
  doc/Makefile
  doc/source/_static/openapi/v2/dataplane.yaml
  doc/source/_static/proto/v2/dataplane.proto
  doc/source/_static/theme_overrides.css
  doc/source/_templates/page.html
  doc/source/conf.py
  doc/source/graph/svcorch.md
  doc/source/python/python_component.md
  doc/source/reference/apis/index.rst
  doc/source/reference/apis/v2-protocol.md
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/README.md
  openapi/v2/Makefile
  openapi/v2/dataplane.yaml
  proto/v2/Makefile
  proto/v2/README.md
  proto/v2/dataplane.proto
  proto/v2/template.md
Labels: size/XXL

#4329 update conda in base image and use ubi9
  wrappers/s2i/python/Dockerfile.conda
  wrappers/s2i/python/Makefile
Labels: size/S

#4337 Embedding intro video in docs
  README.md
  doc/requirements.txt
  doc/source/conf.py
  doc/source/images/core-play-logo.png
  doc/source/index.rst
Labels: size/XS, approved

#4342 Fix resource lock type
  operator/config/manager/manager.yaml
Labels: size/XS

#4338 Use timer instead of time.After to prevent memory leaks in logger
  executor/logger/collector.go
Labels: size/XS, approved, needs-ok-to-test, do-not-merge/hold

#4350 update k8s versions supported in docs
  doc/source/workflow/install.rst
Labels: size/XS, approved

#4268 factored out make_rest_server_debug/prod
  .gitignore
  python/seldon_core/microservice.py
Labels: size/L, approved, needs-ok-to-test
