Repository SeldonIO/seldon-core, pull requests merged in 2022-01, with the labels that each got.

#3829 Updated license branch from master to main for hashicorp/go-version
  executor/Dockerfile.executor
  executor/Dockerfile.executor.redhat
  operator/Dockerfile
  operator/Dockerfile.redhat
Labels: size/XS, approved

#3832 reference to kfserving storage initializer from dockerhub
  doc/source/reference/release-1.7.0.md
  doc/source/reference/upgrading.md
  doc/source/servers/kfserving-storage-initializer.md
  examples/init_containers/custom_init_container.ipynb
  examples/upgrade-to-rclone/global-rclone-upgrade.ipynb
  examples/upgrade-to-rclone/rclone-upgrade.ipynb
  examples/upgrade-to-rclone/sklearn-iris-kfserving.yaml
  helm-charts/seldon-openvino/templates/openvino_deployment.json
  operator/config/manager/configmap.yaml
  operator/controllers/model_initializer_injector_test.go
  operator/controllers/suite_test.go
  operator/utils/k8s/testdata/configmap.yaml
Labels: size/M

#3837 Added missing words
  doc/source/workflow/overview.md
Labels: size/XS, needs-ok-to-test

#3838 Bump seldon-deploy-sdk to 1.4.1.2 in request logger
  components/seldon-request-logger/requirements.txt
Labels: size/XS, approved

#3842 Update overview.md
  doc/source/servers/overview.md
Labels: size/XS, approved

#3843 Update mlflow.md
  doc/source/servers/mlflow.md
Labels: size/XS, approved

#3844 Read OIDC resource parameter
  components/seldon-request-logger/app/log_mapping.py
Labels: size/L, approved

#3851 Operator sets seldondeployment to failed when deployment not progressing
  operator/Makefile
  operator/README.md
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/config/crd/kustomization.yaml
  operator/config/manifests/bases/seldon-operator.clusterserviceversion.yaml
  operator/controllers/seldondeployment_controller.go
  operator/licenses/license.txt
  operator/utils/k8s/webhook.go
Labels: size/M

#3865 Add agrski as approver
  OWNERS
Labels: size/S

#3813 Seldon add ssl
  doc/source/analytics/logging.md
  executor/.gitignore
  executor/api/kafka/server.go
  executor/api/util/utils.go
  executor/api/util/utils_test.go
  executor/logger/dispatcher.go
  executor/logger/worker.go
  executor/logger/worker_test.go
  executor/predictor/predictor_process_test.go
Labels: size/L, approved

#3855 Add events to namespaced roles
  helm-charts/seldon-core-operator/templates/role_seldon1-manager-role.yaml
  operator/config/namespaced/role.yaml
Labels: size/S, approved

#3863 Bump upper constrains of MLflow server dependencies
  notebooks/resources/elasticnet_wine_v2.yaml
  notebooks/server_examples.ipynb
  servers/mlflowserver/mlflowserver/requirements.txt
  testing/scripts/kind_test_all.sh
Labels: size/M, approved

#3870 Upgrade confluent-kafka-go to v1.8.2
  executor/go.mod
  executor/go.sum
Labels: size/XS, needs-ok-to-test

#3875 Updating security tests to run on 1.13.0-dev images
  .github/workflows/security_tests.yml
Labels: size/S, approved

#3892 Changes ndarry to ndarray
  openapi/engine.oas3.json
Labels: size/XS, needs-ok-to-test

#3868 Add support to use PEM string for SSL
  executor/api/kafka/server.go
  executor/api/util/utils.go
  executor/logger/worker.go
  executor/logger/worker_test.go
Labels: size/L, needs-ok-to-test

#3894 Adding test skip until fixed via 3857
  testing/scripts/test_rolling_updates.py
Labels: size/XS

#3897 Fix seldon manager configmap for alibiexplainer version
  operator/config/manager/configmap.yaml
  release.py
Labels: size/M, approved

#3888 Updated cert-manager API version
  examples/security/ssl_requests/README.ipynb
  examples/security/ssl_requests/README.md
  helm-charts/seldon-core-operator/templates/certificate_seldon-serving-cert.yaml
  helm-charts/seldon-core-operator/templates/issuer_seldon-selfsigned-issuer.yaml
  operator/Makefile
  operator/config/certmanager/certificate.yaml
  operator/config/default/kustomization.yaml
Labels: size/S, needs-ok-to-test

#3879 Updating helm docs for 1.13.0-dev
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-mab/README.md
Labels: size/M

#3905 Update autoscale docs
  doc/source/graph/scaling.md
  examples/models/autoscaling/autoscaling_example.ipynb
Labels: size/S, needs-ok-to-test
