Repository SeldonIO/seldon-core, pull requests merged in 2022-11, with the labels that each got.

#4418 Add security scans for MLServer images
  .github/workflows/security_tests.yml
Labels: size/S

#4419 scan -sc images only for 1.15.0
  .github/workflows/security_tests.yml
Labels: size/XS, approved

#4416 Enables SSL_SASL
  executor/api/kafka/server.go
  executor/api/util/utils.go
  executor/logger/worker.go
Labels: size/M, approved, needs-ok-to-test

#4417 push of MLServer images for Red Hat certification
  marketplaces/redhat/.gitignore
  marketplaces/redhat/Makefile
  marketplaces/redhat/scan-images.py
  operator/openshift.md
Labels: size/M

#4394 Allow urllib3 >= 1.26.5
  python/setup.py
Labels: size/XS, needs-ok-to-test

#4427 Set allowPrivilegeEscalation to false for the service orchestrator
  operator/controllers/seldondeployment_engine.go
Labels: size/XS, needs-ok-to-test

#4435 Improve Kafka config handling in executor
  executor/api/kafka/server.go
  executor/api/util/kafka.go
  executor/api/util/utils.go
  executor/logger/worker.go
Labels: size/L, approved

#4437 Add missing related images for v2 protocol
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/apis/machinelearning.seldon.io/v1/prepack.go
  operator/apis/machinelearning.seldon.io/v1/prepack_test.go
  operator/apis/machinelearning.seldon.io/v1/seldon_deployment_status.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_webhook.go
  operator/config/manager/manager.yaml
  operator/config/manifests/bases/seldon-operator.clusterserviceversion.yaml
  operator/controllers/mlserver.go
  operator/controllers/mlserver_test.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_engine_test.go
  operator/controllers/seldondeployment_explainers.go
  operator/controllers/seldondeployment_explainers_test.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
  operator/controllers/utils/controller_utils.go
  operator/utils/utils.go
Labels: size/XL, approved

#4440 Update kind & k8s versions in Ansible setup
  ansible/playbooks/kind_cluster.yaml
Labels: size/XS, approved

#4351 Factor out _make_run_grpc_server
  python/seldon_core/microservice.py
Labels: size/L, approved, needs-ok-to-test

#4406 4041 upgrading jaeger
  doc/source/graph/distributed-tracing.md
  examples/models/tracing/tracing.ipynb
  testing/resources/graph-tracing.json
  testing/resources/jaeger.yaml
  testing/scripts/Makefile
Labels: size/M, approved

#4458 add tar to wrapper image as it is missing after move to ubi-minimal
  wrappers/s2i/python/Dockerfile.conda
Labels: size/XS, approved

#4448 Bump MLServer version to 1.2.0
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  testing/resources/iris_anchor_tabular_explainer_v2.yaml
  testing/resources/tf_cifar_anchor_image_explainer_v2.yaml
  testing/scripts/Makefile
  testing/scripts/test_alibi_explain.py
  testing/scripts/test_alibi_explain_v2.py
Labels: size/M, approved
