Repository SeldonIO/seldon-core, pull requests merged in 2022-08, with the labels that each got.

#4238 Adding prepackaged server separate pod instructions
  doc/source/graph/graph-modes.md
Labels: size/S

#4250 Updated stalebot to ensure it only actions relevant issues/prs
  .github/workflows/stalebot.yml
Labels: size/XS

#4256 Added fix for webhook issues on 1.12.0
  testing/scripts/test_operator_updates.py
Labels: size/XS, approved

#4249 Make verbosity configurable and not leak sensitive values
  components/rclone-storage-initializer/Dockerfile
Labels: size/XS, needs-ok-to-test

#4259 fix workflow on red hat image scan process
  components/alibi-detect-server/.gitignore
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Makefile
  examples/models/mean_classifier/.gitignore
  examples/models/mean_classifier/Makefile
  executor/.gitignore
  operator/.gitignore
  servers/mlflowserver/Makefile
  servers/sklearnserver/Makefile
  servers/tfserving_proxy/Makefile
  servers/xgboostserver/Makefile
Labels: size/M

#4265 Added fix for clashing zombie webhook in integration tests
  testing/scripts/test_operator_updates.py
Labels: size/XS, approved

#4287 1.14.1 to master
  CHANGELOG.md
  components/.gitignore
  components/alibi-detect-server/.gitignore
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-explain-server/.gitignore
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Makefile
  components/rclone-storage-initializer/Dockerfile
  components/rclone-storage-initializer/Dockerfile.redhat
  components/rclone-storage-initializer/Makefile
  components/storage-initializer/Dockerfile
  components/storage-initializer/Makefile
  doc/source/reference/upgrading.md
  examples/models/mean_classifier/.gitignore
  examples/models/mean_classifier/Makefile
  executor/.gitignore
  executor/Dockerfile.executor.redhat
  executor/Makefile
  operator/.gitignore
  operator/Dockerfile.redhat
  operator/Makefile
  operator/bundle-certified.Dockerfile
  operator/bundle-certified/manifests/machinelearning.seldon.io_seldondeployments.yaml
  operator/bundle-certified/manifests/seldon-operator-certified.clusterserviceversion.yaml
  operator/bundle-certified/metadata/annotations.yaml
  operator/bundle.Dockerfile
  operator/bundle/manifests/machinelearning.seldon.io_seldondeployments.yaml
  operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml
  operator/bundle/metadata/annotations.yaml
  operator/config/manager/configmap.yaml
  operator/hack/csv_hack.py
  operator/openshift.md
  operator/openshift/tests/README.md
  operator/openshift/tests/catalog-source-openshift-certified.yaml
  operator/openshift/tests/catalog-source-openshift.yaml
  servers/.gitignore
  servers/mlflowserver/Makefile
  servers/sklearnserver/.gitignore
  servers/sklearnserver/Makefile
  servers/tfserving/Dockerfile.redhat
  servers/tfserving/Makefile
  servers/tfserving_proxy/Makefile
  servers/xgboostserver/Makefile
  wrappers/s2i/python/Dockerfile
Labels: size/XXL, approved

#4286 move to Flask 2.x
  .readthedocs.yml
  components/alibi-detect-server/poetry.lock
  doc/requirements.txt
  python/seldon_core/flask_utils.py
  python/setup.py
Labels: size/L

#4288 add upgrading note on Flask 2.x upgrade
  doc/source/reference/upgrading.md
Labels: size/XS, approved

#4289 Adding licenses updates as part of the post-release process
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
Labels: size/XXL, approved
