Repository SeldonIO/seldon-core, pull requests merged in 2022-02, with the labels that each got.

#3898 Pass down ports info to MLServer
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/seldondeployment.yaml
  operator/controllers/mlserver.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/utils/utils.go
Labels: size/L

#3874 Updating inference logic to add node level request-response logging
  executor/predictor/predictor_process.go
Labels: size/L

#3871 bump alibi-detect to 0.8.1 in adserver
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/protocols/seldon_http.py
  components/alibi-detect-server/adserver/protocols/v2.py
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
Labels: size/XXL

#3907 Fixing Alibi Detect Server response cloud event data is json marshalled string
  components/alibi-detect-server/adserver/server.py
  components/alibi-detect-server/adserver/tests/test_server.py
  components/drift-detection/cifar10/cifar10_drift.ipynb
  components/drift-detection/nvidia-triton-cifar10/cifar10_drift.ipynb
  components/outlier-detection/cifar10/cifar10_outlier.ipynb
  components/outlier-detection/nvidia-triton-cifar10/cifar10_outlier.ipynb
  doc/source/reference/upgrading.md
Labels: size/M

#3805 Add model_name when chaining requests
  executor/api/grpc/kfserving/client.go
  executor/api/grpc/kfserving/client_test.go
  testing/docker/mock-preprocessor/Makefile
  testing/docker/mock-preprocessor/model-settings.json
  testing/docker/mock-preprocessor/runtime.py
  testing/resources/graph-v2.yaml
  testing/scripts/Makefile
  testing/scripts/conftest.py
  testing/scripts/dev_requirements.txt
  testing/scripts/e2e_utils/v2_protocol.py
  testing/scripts/test_graph.py
  testing/scripts/test_prepackaged_servers.py
Labels: size/L

#3916 Bump MLServer image to 1.0.0.rc2
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/seldondeployment.yaml
  examples/transformers/v2-protocol/tokeniser/requirements.txt
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
  testing/scripts/test_alibi_explain_v2.py
Labels: size/M

#3925 Skip request logging if skip header is present
  components/alibi-explain-server/alibiexplainer/utils.py
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  components/alibi-explain-server/tests/test_utils.py
  executor/api/payload/metadata.go
  executor/api/payload/metadata_test.go
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
Labels: size/L, approved

#3927 Bump MLServer to 1.0.0
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/tokeniser/requirements.txt
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: size/M

#3928 Add test for tensorflow prepackaged Seldon protocol with resource requests
  operator/controllers/seldondeployment_prepackaged_servers_test.go
Labels: size/L

#3937 Adding chmod to dockefile example
  doc/source/python/python_wrapping_docker.md
Labels: size/XS

#3948 Fixed Flask dependency by pinning markupsafe and itsdangerous
  python/setup.py
Labels: size/XS, approved

#3950 Updating broken link in documentation
  doc/source/workflow/install.rst
Labels: size/XS

#3949 Addresing security vulnerabilities for 1.13.1 release
  .github/workflows/security_tests.yml
Labels: size/S

#3959 Update security policy to outline current security scans
  SECURITY.md
Labels: size/S

#3958 cast float/int 64 to 32 in alibi-detect-server
  components/alibi-detect-server/adserver/ad_model.py
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/adserver/protocols/util.py
Labels: size/S

#3951 Updated base golang images to 1.17.7
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .lighthouse/jenkins-x/benchmark.yaml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/models.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  .lighthouse/jenkins-x/release.yaml
  core-builder/Dockerfile
  core-builder/Makefile
  executor/Dockerfile.executor
  executor/Dockerfile.executor.redhat
  operator/Dockerfile
  operator/Dockerfile.redhat
Labels: size/M

#3962 Merging 1.13.1 changelog and update to 1.14.0-dev images
  CHANGELOG.md
  doc/source/reference/images.md
  helm-charts/seldon-abtest/README.md
  helm-charts/seldon-core-analytics/README.md
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-mab/README.md
Labels: size/XXL, approved
