Repository SeldonIO/seldon-core, pull requests merged in 2022-07, with the labels that each got.

#4207 fix metadata
  executor/predictor/predictor_process.go
  operator/controllers/suite_test.go
Labels: size/XS

#4200 typo fix in logging bind_address of gRPC server
  python/seldon_core/microservice.py
Labels: size/XS, needs-ok-to-test

#4214 renamed server_[123]_func to server_[rest|grpc|custom]_func
  python/seldon_core/microservice.py
Labels: size/S, approved, needs-ok-to-test

#4210 upgrade pip, conda and setuptools in s2i image
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Makefile
Labels: size/XS

#4213 factored out parse_args from main
  python/.gitignore
  python/seldon_core/microservice.py
Labels: size/S, needs-ok-to-test

#4211 Allow leader election controls for manager
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
  operator/main.go
Labels: size/M

#4218 Added fix for removed guard on webhook
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/helm/split_resources.py
Labels: size/S, approved

#4216 enh: Add support to configure PrepackedTriton with no storage initialiser
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/constants/constants.go
  operator/controllers/model_initializer_injector.go
  operator/controllers/model_initializer_injector_test.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
Labels: size/L, approved, needs-ok-to-test

#4228 Fix Typo in Readme.md
  helm-charts/seldon-core-operator/README.md
Labels: size/XS, approved, needs-ok-to-test

#4230 Fixed trailing dash created from helm split resources
  helm-charts/seldon-core-operator/templates/certificate_seldon-serving-cert.yaml
  helm-charts/seldon-core-operator/templates/issuer_seldon-selfsigned-issuer.yaml
  helm-charts/seldon-core-operator/templates/serviceaccount_seldon-manager.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/helm/split_resources.py
Labels: size/S, approved

#4232 Adding stalebot for issues and PRs with defaults
  .github/workflows/stalebot.yml
Labels: size/S, approved

#4242 doc: add util comment && identation
  examples/outliers/alibi-detect-combiner/train_classifier.py
Labels: size/XS, needs-ok-to-test
