Repository SeldonIO/seldon-core, pull requests merged in 2022-04, with the labels that each got.

#4020 Update ab_test_2pods.json
  helm-charts/seldon-abtest/templates/ab_test_2pods.json
Labels: size/XS, approved, needs-ok-to-test

#4018 Fixed Flask breaking version by werkzeug dependency limit to 2.1
  .github/workflows/alibidetect_tests.yml
  python/setup.py
Labels: size/XS

#4025 Updating typings for prediction API documentation
  doc/source/python/python_component.md
Labels: size/S

#4032 Updating model inputs for new schema
  examples/triton_gpt2/README.ipynb
Labels: size/S, approved

#4030 Allow priorityClassName for manager
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/helm/split_resources.py
Labels: size/XS

#4026 Updated CPP example to use latest 3.8 base image
  examples/models/cpp/buildsystem-override/README.ipynb
  examples/models/cpp/buildsystem-override/README.md
  examples/models/cpp/simple-cpp/README.ipynb
  examples/models/cpp/simple-cpp/README.md
  incubating/wrappers/s2i/cpp/Makefile
Labels: size/M

#4035 Extended GPT2 MLServer Pipeline Example to include post-processor
  examples/transformers/v2-protocol/README.ipynb
  examples/transformers/v2-protocol/README.md
  examples/transformers/v2-protocol/seldondeployment.yaml
  examples/transformers/v2-protocol/tokeniser/model-settings.json
  examples/transformers/v2-protocol/tokeniser/requirements.txt
  examples/transformers/v2-protocol/tokeniser/runtime.py
Labels: size/L

#4016 Python request logger example component deprication and removal
  ci_build_and_push_images.sh
  components/seldon-request-logger/Dockerfile
  components/seldon-request-logger/Makefile
  components/seldon-request-logger/README.md
  components/seldon-request-logger/app/default_logger.py
  components/seldon-request-logger/app/log_helper.py
  components/seldon-request-logger/app/log_mapping.py
  components/seldon-request-logger/app/tests.py
  components/seldon-request-logger/requirements.txt
  components/seldon-request-logger/testing/cifardata.json
  components/seldon-request-logger/testing/create_dummy_metadata.py
  components/seldon-request-logger/testing/deploy_model.sh
  components/seldon-request-logger/testing/test.sh
  doc/source/analytics/logging.md
  doc/source/reference/upgrading.md
  examples/centralised-logging/README.md
  examples/centralised-logging/fluentd-values.yaml
  examples/centralised-logging/full-kind-setup.sh
  examples/centralised-logging/install_istio.sh
  examples/centralised-logging/install_knative.sh
  examples/centralised-logging/kibana-custom-search.png
  examples/centralised-logging/kibana-virtualservice.yaml
  examples/centralised-logging/kind_config.yaml
  examples/centralised-logging/seldon-request-logger-k8s.yaml
  examples/centralised-logging/seldon-request-logger.yaml
  examples/centralised-logging/trigger.yaml
  examples/centralised-logging/values-opendistro-kind.yaml
  testing/scripts/test_notebooks.py
Labels: size/XXL, approved

#4039 Removed request logger from github security workflows
  .github/workflows/security_tests.yml
Labels: size/S

#4027 Enabling optional grpc server on python level only
  doc/source/python/python_server.rst
  python/seldon_core/microservice.py
Labels: size/M

#4044 fix removal of request logger to fix CI
  doc/source/reference/upgrading.md
  marketplaces/redhat/scan-images.py
  release.py
  testing/scripts/Makefile
Labels: size/XS

#4055 Outlier example poetry
  doc/source/analytics/explainers.md
  doc/source/analytics/outlier_detection.md
  doc/source/examples/cifar10_od_poetry.nblink
  doc/source/examples/notebooks.rst
  doc/source/nav/archive.rst
  doc/source/nav/config/integrations.rst
  examples/outliers/cifar10-od-poetry/.gitignore
  examples/outliers/cifar10-od-poetry/broker.yaml
  examples/outliers/cifar10-od-poetry/cifar10-od.ipynb
  examples/outliers/cifar10-od-poetry/cifar10.yaml
  examples/outliers/cifar10-od-poetry/event-display.yaml
  examples/outliers/cifar10-od-poetry/images/cifar10_image.json
  examples/outliers/cifar10-od-poetry/images/outlier_image.json
  examples/outliers/cifar10-od-poetry/kservice.yaml
  examples/outliers/cifar10-od-poetry/poetry.lock
  examples/outliers/cifar10-od-poetry/pyproject.toml
  examples/outliers/cifar10-od-poetry/rclone.conf
  examples/outliers/cifar10-od-poetry/secret.yaml
  examples/outliers/cifar10-od-poetry/train.py
  examples/outliers/cifar10-od-poetry/trigger.yaml
  util/kubectl-proxy/Dockerfile
  util/kubectl-proxy/Makefile
Labels: size/XXL, approved

#4054 Forward request parameters while chaining models via kfserve grpc
  executor/api/grpc/kfserving/client.go
  executor/api/grpc/kfserving/client_test.go
Labels: size/S, approved, needs-ok-to-test

#4028 Protocol specific ready checkers
  doc/source/python/python_component.md
  doc/source/reference/upgrading.md
  executor/api/kafka/server.go
  executor/api/rest/server.go
  executor/api/rest/server_test.go
  executor/cmd/executor/main.go
  executor/predictor/ready_checker.go
  helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/manager.yaml
  operator/controllers/seldondeployment_engine.go
  operator/helm/split_resources.py
  python/seldon_core/user_model.py
Labels: size/L, approved

#4064 lock jager operator helm chart to fix integration tests
  testing/scripts/Makefile
Labels: size/XS

#4066 change versions we test upgrade of operator from
  testing/scripts/test_operator_updates.py
Labels: size/XS, approved

#4061 Adding tests to explicitly state expected behaviour of v2 protocol chaining in REST
  executor/api/rest/kfserving_test.go
Labels: size/M
