Repository SeldonIO/seldon-core, pull requests merged in 2023-02, with the labels that each got.

#4639 Bug fix and update to notebook
  samples/model-zoo.ipynb
  scheduler/pkg/agent/repository/mlserver/settings.go
Labels: v2

#4626 k6 multiple models run
  scheduler/pkg/envoy/processor/incremental_test.go
  scheduler/pkg/scheduler/filters/replicarequirements_test.go
  scheduler/pkg/scheduler/sorters/replicaindex_test.go
  scheduler/pkg/scheduler/sorters/replicamemory_test.go
  scheduler/pkg/store/mesh.go
  tests/k6/Dockerfile.k6
  tests/k6/components/model.js
  tests/k6/components/settings.js
  tests/k6/components/utils.js
  tests/k6/configs/k8s/base/k6.yaml
  tests/k6/notebooks/agent/agent_test_runner.sh
  tests/k6/scenarios/experiment.js
  tests/k6/scenarios/infer_constant_rate.js
  tests/k6/scenarios/infer_constant_vu.js
  tests/k6/scenarios/load_predict_unload.js
  tests/k6/scenarios/model_constant_rate.js
  tests/k6/scenarios/pipeline.js
  tests/k6/scenarios/predict_agent_oc.js
Labels: v2

#4641 Fix available memory overflowing
  scheduler/pkg/agent/state_manager.go
  scheduler/pkg/agent/state_manager_test.go
  scheduler/pkg/envoy/processor/incremental_test.go
  scheduler/pkg/scheduler/filters/replicamemory.go
  scheduler/pkg/scheduler/filters/replicamemory_test.go
  scheduler/pkg/scheduler/filters/replicarequirements_test.go
  scheduler/pkg/scheduler/scheduler.go
  scheduler/pkg/scheduler/scheduler_test.go
  scheduler/pkg/scheduler/sorters/loaded_test.go
  scheduler/pkg/scheduler/sorters/replicaindex_test.go
  scheduler/pkg/scheduler/sorters/replicamemory_test.go
  scheduler/pkg/server/server.go
  scheduler/pkg/store/mesh.go
Labels: v2

#4644 fix typos in 2.2.0 testing
  samples/examples/huggingface/Makefile
  samples/examples/huggingface/huggingface.ipynb
  samples/examples/huggingface/huggingface.md
  samples/examples/image_classifier/Makefile
  samples/examples/image_classifier/infer.ipynb
  samples/examples/image_classifier/infer.md
  samples/examples/income_classifier/Makefile
  samples/examples/income_classifier/infer.ipynb
  samples/examples/income_classifier/infer.md
  samples/model-zoo.md
Labels: v2

#4647 Retry on server load fail
  scheduler/cmd/agent/main.go
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/client_test.go
  scheduler/pkg/agent/client_utils.go
  scheduler/pkg/agent/client_utils_test.go
  scheduler/pkg/scheduler/filters/replicamemory.go
  scheduler/pkg/scheduler/filters/replicamemory_test.go
Labels: v2

#4600 Delete oprhaned services and update Ambassador docs
  doc/source/install/aws.rst
  doc/source/install/azure.rst
  doc/source/install/gcp.rst
  doc/source/install/kind.rst
  doc/source/workflow/install.rst
  operator/controllers/cleaners.go
  operator/controllers/seldondeployment_controller.go
Labels: v1

#4650 Small CLI Updates
  operator/cmd/seldon/cli/experiment_stop.go
  operator/cmd/seldon/cli/file.go
  operator/cmd/seldon/cli/model_unload.go
  operator/cmd/seldon/cli/pipeline_inspect.go
  operator/cmd/seldon/cli/pipeline_load.go
  operator/cmd/seldon/cli/pipeline_unload.go
  operator/pkg/cli/kafka.go
  operator/pkg/cli/scheduler.go
Labels: v2

#4645 Upgrade istio and pdbs
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .lighthouse/jenkins-x/integration.yaml
  .lighthouse/jenkins-x/notebooks.yaml
  core-builder/Dockerfile
  core-builder/Makefile
  doc/source/analytics/analytics.md
  examples/keda/keda_prom_auto_scale.ipynb
  examples/keda/model_with_keda_prom.yaml
  examples/keda/pod-monitor.yaml
  examples/models/autoscaling/autoscaling_example.ipynb
  executor/api/grpc/kfserving/inference/grpc_service.pb.go
  executor/api/grpc/kfserving/inference/model_config.pb.go
  executor/go.mod
  executor/go.sum
  executor/licenses/dep.txt
  executor/licenses/license.txt
  executor/licenses/license_info.csv
  executor/licenses/repo.txt
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  helm-charts/seldon-core-operator/templates/webhook.yaml
  operator/Makefile
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1alpha3/seldondeployment_webhook.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1_small/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/cleaners.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/licenses/dep.txt
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
  testing/resources/kind_config.yaml
  testing/scripts/.gitignore
  testing/scripts/Makefile
  testing/scripts/metrics.yaml
Labels: v1

#4661 Add scaling docs for V2
  docs/source/contents/kubernetes/index.md
  docs/source/contents/kubernetes/scaling/index.md
Labels: v2

#4660 Add resource generic load, unload, status to CLI
  operator/cmd/seldon/cli/load.go
  operator/cmd/seldon/cli/root.go
  operator/cmd/seldon/cli/status.go
  operator/cmd/seldon/cli/unload.go
  operator/config/crd/bases/mlops.seldon.io_pipelines.yaml
  operator/pkg/cli/generic.go
  operator/pkg/cli/scheduler.go
Labels: v2

#4664 Updated rclone docs
  docs/source/contents/kubernetes/cloud-storage/index.md
Labels: v2

#4408 Use FQDN in the host field of Istio resources
  operator/controllers/seldondeployment_controller.go
Labels: size/S, needs-ok-to-test, v1

#4591 Bump MLServer to 1.2.3 (v1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4672 Use constant from constants package
  operator/controllers/seldondeployment_controller.go
Labels: v1

#4662 Adding logging section to FAQ
  docs/source/contents/faqs/index.md
Labels: v2

#4675 Ensure settings for max message size
  k8s/helm-charts/seldon-core-v2-setup/templates/kafka.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/config/serverconfigs/mlserver.yaml
  operator/pkg/cli/kafka.go
  scheduler/all-base.yaml
  scheduler/config/kafka-internal.json
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/BatchProcessor.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Configuration.kt
  scheduler/pkg/agent/v2.go
  scheduler/pkg/kafka/gateway/infer.go
Labels: v2

#4677 Update Kafka install docs
  docs/source/contents/getting-started/kubernetes-installation/helm.md
  docs/source/contents/getting-started/kubernetes-installation/kafka.md
  kafka/strimzi/README.md
Labels: v2

#4687 chore: update setuptools version to 65.5.1
  python/setup.py
  servers/mlflowserver/models/elasticnet_wine/Makefile
  wrappers/s2i/python/Dockerfile
Labels: needs-ok-to-test

#4540 upgrade cryptography python package
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
  python-builder/Dockerfile
  python-builder/Makefile
  python/requirements-dev.txt
  python/seldon_core/proto/prediction_pb2.py
  python/seldon_core/proto/prediction_pb2.pyi
  python/seldon_core/proto/tensorflow/core/framework/resource_handle_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor.proto
  python/seldon_core/proto/tensorflow/core/framework/tensor_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/tensor_shape_pb2.py
  python/seldon_core/proto/tensorflow/core/framework/types.proto
  python/seldon_core/proto/tensorflow/core/framework/types_pb2.py
  python/setup.py
Labels: v1
