Repository SeldonIO/seldon-core, pull requests merged in 2023-03, with the labels that each got.

#4533 4489 router logger
  executor/predictor/predictor_process.go
  executor/predictor/predictor_process_test.go
Labels: v1

#4528 fix service host for separate pods with prepacked servers
  examples/graph_examples/combiner-prepack-sep-pods.yaml
  examples/graph_examples/combiner-prepack.yaml
  examples/graph_examples/combiner-sep-pods.yaml
  examples/graph_examples/graph-examples.ipynb
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
  testing/scripts/Makefile
Labels: v1

#4703 Bump version of golint
  .github/workflows/draft-release.yml
  .github/workflows/images.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  components/tls/Makefile
  hodometer/Makefile
  operator/Makefile
  scheduler/Makefile
Labels: v2

#4713 Increase idle connection of REST proxy to timeout to 30 minutes
  scheduler/pkg/agent/rproxy.go
Labels: v2

#4172 HPA upgrade
  doc/source/graph/scaling.md
  doc/source/workflow/install.rst
  examples/models/autoscaling/autoscaling_example.ipynb
  examples/models/autoscaling/model_with_hpa_v2.yaml
  examples/models/autoscaling/model_with_hpa_v2beta1.yaml
  executor/go.mod
  executor/go.sum
  helm-charts/seldon-core-operator/templates/customresourcedefinition_v1_seldondeployments.machinelearning.seldon.io.yaml
  operator/README.md
  operator/apis/machinelearning.seldon.io/v1/conversion.go
  operator/apis/machinelearning.seldon.io/v1/conversion_test.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/apis/machinelearning.seldon.io/v1/zz_generated.deepcopy.go
  operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/config/crd_v1_small/bases/machinelearning.seldon.io_seldondeployments.yaml
  operator/controllers/seldondeployment_controller.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/main.go
  operator/testing/machinelearning.seldon.io_seldondeployments.yaml
Labels: size/XXL, do-not-merge/work-in-progress, v1

#4702 Bump MLServer to 1.2.4 (V1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4701 Bump MLServer to 1.2.4 (V2)
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
Labels: v2

#4714 Link to v2 codebase in v1 readme
  README.md
Labels: v1

#4716 Fix golang version in security tests
  .github/workflows/security_tests_v2.yml
Labels: v2

#4718 Docs: Add a section in Servers for setting extra capabilities
  docs/source/contents/servers/index.md
  samples/models/extra-model-requirements.yaml
  samples/servers/mlserver-extra-capabilities.yaml
Labels: area/documentation, v2

#4720 Add parameter to dashboard by namespace
  prometheus/dashboards/seldon.json
Labels: v2

#4722 Upgrade some packages for CVE - yaml.v3 and golang.org/x/text
  components/tls/go.mod
  components/tls/go.sum
  hodometer/go.mod
  hodometer/go.sum
  operator/go.mod
  operator/go.sum
  scheduler/go.mod
  scheduler/go.sum
Labels: v2

#4723 Update icenses and copyright for v2
  components/tls/licenses/dep.txt
  components/tls/licenses/license.txt
  components/tls/licenses/license_info.csv
  components/tls/licenses/repo.txt
  hodometer/licenses/dep.txt
  hodometer/licenses/license.txt
  hodometer/licenses/license_info.csv
  hodometer/licenses/repo.txt
  licenses/3rd-party-summary.txt
  operator/licenses/dep.txt
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  operator/licenses/repo.txt
  samples/examples/image_classifier/train.py
  scheduler/licenses/license.txt
  scheduler/licenses/license_info.csv
Labels: v2

#4727 update dataflow engine dependencies
  scheduler/data-flow/build.gradle.kts
Labels: v2

#4728 Use fix versions of base images for v2 images
  hodometer/Dockerfile.hodometer
  hodometer/Dockerfile.receiver
  operator/Dockerfile
  scheduler/Dockerfile.agent
  scheduler/Dockerfile.dataflow
  scheduler/Dockerfile.envoy
  scheduler/Dockerfile.modelgateway
  scheduler/Dockerfile.pipelinegateway
  scheduler/Dockerfile.rclone
  scheduler/Dockerfile.scheduler
Labels: v2

#4725 fix(seldon operator): infinite service updating if extra default fileds applied by k8s
  operator/controllers/seldondeployment_controller.go
Labels: v1

#4745 Update rclone to 1.62.2
  scheduler/Dockerfile.rclone
Labels: v2

#4747 Fixes check for invalid crd name
  operator/Makefile
Labels: needs-ok-to-test

#4753 revert user to 1000
  scheduler/all-base.yaml
Labels: needs-ok-to-test, v2

#4771 Minior: Fix knative wording
  doc/source/servers/batch.md
  doc/source/streaming/knative_eventing.md
Labels: needs-ok-to-test
