Repository SeldonIO/seldon-core, pull requests merged in 2023-01, with the labels that each got.

#4401 Fixed explainer controller to handle istio hosts annotation
  operator/controllers/seldondeployment_explainers.go
Labels: size/XS, approved, needs-ok-to-test, v1

#4550 use ubuntu-latest for GHA
  .github/workflows/alibidetect_tests.yml
  .github/workflows/alibiexplainer_tests.yml
  .github/workflows/docs.yml
  .github/workflows/executor_lint.yml
  .github/workflows/executor_tests.yml
  .github/workflows/operator_lint.yml
  .github/workflows/operator_tests.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_tests.yml
Labels: v1

#4551 Fix grpc connection retry to control and data plane services
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/rproxy.go
  scheduler/pkg/agent/rproxy_grpc.go
  scheduler/pkg/agent/v2.go
  scheduler/pkg/agent/v2_test.go
  scheduler/pkg/kafka/gateway/client.go
  scheduler/pkg/kafka/gateway/worker.go
  scheduler/pkg/kafka/pipeline/status/client.go
  scheduler/pkg/util/constants.go
Labels: v2

#4557 Retry ModelFailed models
  scheduler/pkg/agent/server.go
  scheduler/pkg/scheduler/scheduler.go
  scheduler/pkg/scheduler/scheduler_test.go
  scheduler/pkg/store/memory.go
Labels: v2

#4559 docs: update GUNICOR_THREADS default value in the docs
  doc/source/python/python_server.rst
Labels: needs-ok-to-test

#4560 v2: update triton, grpc payload size, cli raw output processing
  k8s/Makefile
  k8s/yaml/seldon-v2-components.yaml
  operator/config/serverconfigs/kustomization.yaml
  operator/pkg/cli/infer.go
  samples/examples/image_classifier/infer.ipynb
  scheduler/Makefile
  scheduler/env.all
  scheduler/pkg/agent/rproxy_grpc.go
  scheduler/pkg/kafka/gateway/worker.go
  scheduler/pkg/kafka/pipeline/grpcserver.go
  scheduler/pkg/util/constants.go
Labels: v2

#4505 Fix: support models saved with mlflow=2 in mlflowserver conda_env_create
  servers/mlflowserver/mlflowserver/conda_env_create.py
Labels: size/XS, needs-ok-to-test, v1

#4569 Change dataflow application id to unique
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Configuration.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Pipeline.kt
Labels: v2

#4568 v2: Ensure grpc outgoing context has metadata
  scheduler/pkg/agent/rproxy_grpc.go
  scheduler/pkg/agent/rproxy_grpc_test.go
Labels: v2

#4571 Bump MLServer's message size
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/yaml/seldon-v2-components.yaml
  operator/config/serverconfigs/mlserver.yaml
  scheduler/all-base.yaml
  scheduler/all-mlserver.yaml
  scheduler/k8s/mlserver/mlserver.yaml
Labels: v2

#4538 Add CLI config command to manage configs
  docs/source/contents/cli/docs/seldon.md
  docs/source/contents/cli/docs/seldon_config.md
  docs/source/contents/cli/docs/seldon_config_activate.md
  docs/source/contents/cli/docs/seldon_config_add.md
  docs/source/contents/cli/docs/seldon_config_deactivate.md
  docs/source/contents/cli/docs/seldon_config_list.md
  docs/source/contents/cli/docs/seldon_config_remove.md
  docs/source/contents/cli/docs/seldon_experiment.md
  docs/source/contents/cli/docs/seldon_experiment_list.md
  docs/source/contents/cli/docs/seldon_experiment_start.md
  docs/source/contents/cli/docs/seldon_experiment_status.md
  docs/source/contents/cli/docs/seldon_experiment_stop.md
  docs/source/contents/cli/docs/seldon_model.md
  docs/source/contents/cli/docs/seldon_model_infer.md
  docs/source/contents/cli/docs/seldon_model_list.md
  docs/source/contents/cli/docs/seldon_model_load.md
  docs/source/contents/cli/docs/seldon_model_metadata.md
  docs/source/contents/cli/docs/seldon_model_status.md
  docs/source/contents/cli/docs/seldon_model_unload.md
  docs/source/contents/cli/docs/seldon_pipeline.md
  docs/source/contents/cli/docs/seldon_pipeline_infer.md
  docs/source/contents/cli/docs/seldon_pipeline_inspect.md
  docs/source/contents/cli/docs/seldon_pipeline_list.md
  docs/source/contents/cli/docs/seldon_pipeline_load.md
  docs/source/contents/cli/docs/seldon_pipeline_status.md
  docs/source/contents/cli/docs/seldon_pipeline_unload.md
  docs/source/contents/cli/docs/seldon_server.md
  docs/source/contents/cli/docs/seldon_server_list.md
  docs/source/contents/cli/docs/seldon_server_status.md
  docs/source/contents/cli/index.md
  operator/cmd/seldon/cli/config_activate.go
  operator/cmd/seldon/cli/config_add.go
  operator/cmd/seldon/cli/config_deactivate.go
  operator/cmd/seldon/cli/config_list.go
  operator/cmd/seldon/cli/config_remove.go
  operator/cmd/seldon/cli/experiment_start.go
  operator/cmd/seldon/cli/experiment_status.go
  operator/cmd/seldon/cli/experiment_stop.go
  operator/cmd/seldon/cli/model_infer.go
  operator/cmd/seldon/cli/model_load.go
  operator/cmd/seldon/cli/model_status.go
  operator/cmd/seldon/cli/model_unload.go
  operator/cmd/seldon/cli/pipeline_infer.go
  operator/cmd/seldon/cli/pipeline_inspect.go
  operator/cmd/seldon/cli/pipeline_load.go
  operator/cmd/seldon/cli/pipeline_status.go
  operator/cmd/seldon/cli/pipeline_unload.go
  operator/cmd/seldon/cli/root.go
  operator/cmd/seldon/cli/server_status.go
  operator/pkg/cli/config.go
  operator/pkg/cli/configs.go
Labels: v2

#4584 Fix SSL modelgateway kafka admin client bug
  docs/source/contents/getting-started/kubernetes-installation/tls/strimzi.md
  scheduler/pkg/kafka/gateway/infer.go
Labels: v2

#4583 Fix model delete hang when FailedSchedule
  scheduler/pkg/scheduler/scheduler.go
  scheduler/pkg/store/memory.go
  scheduler/pkg/store/memory_test.go
Labels: v2

#4582 AnchorText example for movies sentiment
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  samples/explainer-examples.ipynb
  samples/explainer-examples.md
  samples/models/income.yaml
  samples/models/moviesentiment-explainer.yaml
  samples/models/moviesentiment.yaml
  samples/scripts/explainers/.gitignore
  samples/scripts/explainers/Makefile
  samples/scripts/explainers/make_test_models.py
  samples/scripts/explainers/model-settings.json.template
  samples/scripts/models/.gitignore
  samples/scripts/models/Makefile
  samples/scripts/models/income/.gitignore
  samples/scripts/models/income/model-settings.json
  samples/scripts/models/income/train.py
  samples/scripts/models/iris/.gitignore
  samples/scripts/models/iris/model-settings.json
  samples/scripts/models/iris/train.py
  samples/scripts/models/moviesentiment/.gitignore
  samples/scripts/models/moviesentiment/model-settings.json
  samples/scripts/models/moviesentiment/train.py
  scheduler/Makefile
Labels: v2

#4586 Add bytes rawcontents correct handling and ensure headers are passed
  operator/pkg/cli/infer.go
  scheduler/pkg/kafka/gateway/worker.go
  scheduler/pkg/kafka/gateway/worker_test.go
  scheduler/pkg/kafka/pipeline/v2.go
  scheduler/pkg/kafka/pipeline/v2_test.go
Labels: v2

#4536 Add SASL_SSL for Kafka Auth
  ansible/roles/ecosystem/defaults/main.yaml
  ansible/roles/ecosystem/tasks/kafka.yaml
  components/tls/pkg/password/file.go
  components/tls/pkg/password/file_test.go
  components/tls/pkg/password/k8s_secret.go
  components/tls/pkg/password/k8s_secret_test.go
  components/tls/pkg/password/store.go
  components/tls/pkg/password/store_test.go
  components/tls/pkg/password/testdata/p1/password
  components/tls/pkg/tls/file.go
  components/tls/pkg/tls/store.go
  components/tls/pkg/tls/util.go
  components/tls/pkg/util/util.go
  docs/source/contents/getting-started/kubernetes-installation/index.md
  docs/source/contents/getting-started/kubernetes-installation/security/index.md
  docs/source/contents/getting-started/kubernetes-installation/security/msk.md
  docs/source/contents/getting-started/kubernetes-installation/security/networking.jpg
  docs/source/contents/getting-started/kubernetes-installation/security/reference.md
  docs/source/contents/getting-started/kubernetes-installation/security/strimzi-mtls.md
  docs/source/contents/getting-started/kubernetes-installation/security/strimzi-sasl.md
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/kustomize/helm-components/patch_dataflow.yaml
  k8s/kustomize/helm-components/patch_modelgateway.yaml
  k8s/kustomize/helm-components/patch_pipelinegateway.yaml
  k8s/samples/ansible-strimzi-kafka-sasl-scram.yaml
  k8s/samples/values-strimzi-kafka-sasl-scram.yaml
  kafka/strimzi/templates/cluster.yaml
  kafka/strimzi/templates/user.yaml
  kafka/strimzi/values.yaml
  operator/cmd/seldon/cli/pipeline_inspect.go
  operator/pkg/cli/config.go
  operator/pkg/cli/kafka.go
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/Cli.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/Main.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Configuration.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/Config.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/K8sCertSecretsProvider.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/Provider.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/sasl/Config.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/sasl/K8sPasswordSecretsProvider.kt
  scheduler/data-flow/src/main/resources/local.properties
  scheduler/pkg/kafka/config/tls.go
  scheduler/pkg/kafka/gateway/infer.go
Labels: v2

#4590 Bump MLServer to 1.2.3
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
Labels: v2

#4543 Allow ServerConfig and Server labels and annotations to be passed to StatefulSet
  operator/controllers/reconcilers/server_reconciler.go
  operator/controllers/reconcilers/statefulset/statefulset_reconciler.go
  operator/controllers/reconcilers/statefulset/statefulset_reconciler_test.go
  operator/pkg/utils/utils.go
  operator/pkg/utils/utils_test.go
Labels: v2

#4589 WIP: update copyright
  apis/go/mlops/agent/agent.pb.go
  apis/go/mlops/agent/agent_grpc.pb.go
  apis/go/mlops/agent_debug/agent_debug.pb.go
  apis/go/mlops/agent_debug/agent_debug_grpc.pb.go
  apis/go/mlops/chainer/chainer.pb.go
  apis/go/mlops/chainer/chainer_grpc.pb.go
  apis/go/mlops/proxy/proxy.pb.go
  apis/go/mlops/proxy/proxy_grpc.pb.go
  apis/go/mlops/scheduler/scheduler.pb.go
  apis/go/mlops/scheduler/scheduler_grpc.pb.go
  apis/go/mlops/scheduler/storage.pb.go
  apis/go/mlops/v2_dataplane/v2_dataplane_grpc.pb.go
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/BatchKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/ChainerOuterClassGrpcKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/ChainerOuterClassKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineStepUpdateKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineSubscriptionRequestKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineTensorMappingKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineTopicKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineUpdateMessageKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineUpdateStatusMessageKt.kt
  apis/mlops/chainer/kotlin/io/seldon/mlops/chainer/PipelineUpdateStatusResponseKt.kt
  components/tls/pkg/password/file.go
  components/tls/pkg/password/file_test.go
  components/tls/pkg/password/k8s_secret.go
  components/tls/pkg/password/k8s_secret_test.go
  components/tls/pkg/password/store.go
  components/tls/pkg/password/store_test.go
  components/tls/pkg/util/util.go
  hack/boilerplate.go.txt
  hack/boilerplate.python.txt
  operator/cmd/seldon/cli/config_activate.go
  operator/cmd/seldon/cli/config_add.go
  operator/cmd/seldon/cli/config_deactivate.go
  operator/cmd/seldon/cli/config_list.go
  operator/cmd/seldon/cli/config_remove.go
  operator/pkg/cli/configs.go
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/headers/PipelineHeaderSetter.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/sasl/Config.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/sasl/K8sPasswordSecretsProvider.kt
Labels: v2

#4588 WIP: v2 licenses update
  hodometer/licenses/license.txt
  scheduler/licenses/repo.txt
Labels: v2

#4592 update income example and yamls
  samples/examples/income_classifier/.gitignore
  samples/examples/income_classifier/Makefile
  samples/examples/income_classifier/drift-detector/.gitignore
  samples/examples/income_classifier/infer.ipynb
  samples/examples/income_classifier/infer.md
  samples/examples/income_classifier/requirements.txt
  samples/examples/income_classifier/train.ipynb
  samples/examples/income_classifier/train.md
  samples/examples/income_classifier/train.py
  samples/explainer-examples.ipynb
  samples/models/income-drift.yaml
  samples/models/income-explainer-pipeline.yaml
  samples/models/income-explainer.yaml
  samples/models/income-outlier.yaml
  samples/models/income-preprocess.yaml
  samples/models/income.yaml
Labels: v2

#4593 updated notebook markdown
  samples/explainer-examples.md
  samples/k8s-batch-examples.ipynb
  samples/k8s-batch-examples.md
  samples/k8s-explainers.ipynb
  samples/k8s-explainers.md
  samples/pipeline-examples.md
  samples/pipeline-to-pipeline.md
Labels: v2

#4606 Update multi-model serving and overcommit docs
  docs/source/contents/about/index.md
  docs/source/contents/about/multimodel2.png
  docs/source/contents/about/multimodel3.png
  docs/source/contents/explainers/index.md
  docs/source/contents/kubernetes/metrics/index.md
  docs/source/contents/models/index.md
  docs/source/contents/models/mms/mms.md
  docs/source/contents/models/mms/mms.png
  docs/source/contents/models/mms/overcommit.png
  samples/local-over-commit-test.ipynb
  samples/local-over-commit-test.md
Labels: v2

#4609 Fix incorrect GUNICORN_THREADS default value in documentation
  doc/source/python/python_server.rst
Labels: needs-ok-to-test

#4611 Stop Agent if subservices are not ready
  docs/source/contents/models/mms/mms.md
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/yaml/seldon-v2-components.yaml
  operator/config/serverconfigs/mlserver.yaml
  operator/config/serverconfigs/triton.yaml
  samples/local-over-commit-test.ipynb
  samples/local-over-commit-test.md
  scheduler/cmd/agent/cli/flags.go
  scheduler/cmd/agent/main.go
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/client_test.go
  scheduler/pkg/agent/client_utils.go
  scheduler/pkg/agent/rclone/rclone.go
  scheduler/pkg/agent/rproxy_grpc_test.go
  scheduler/pkg/agent/v2.go
  scheduler/pkg/agent/v2_test.go
Labels: v2

#4619 Add app-vulns flag to V2 images
  .github/workflows/security_tests_v2.yml
Labels: v2

#4618 Dont hold a global lock when publishing to `EventHub`
  scheduler/pkg/agent/server.go
  scheduler/pkg/store/memory_status.go
Labels: bug, v2

#4621 Fix model progressing state getting stuck if agent dies
  scheduler/pkg/agent/server.go
  scheduler/pkg/agent/server_test.go
  scheduler/pkg/store/memory.go
  scheduler/pkg/store/memory_test.go
  scheduler/pkg/store/mesh.go
  scheduler/pkg/store/mesh_test.go
Labels: v2, reliability

#4616 adding local batch example
  docs/source/contents/examples/batch-examples-k8s.md
  docs/source/contents/examples/batch-examples-local.md
  docs/source/contents/examples/index.md
Labels: v2

#4612 Fix CVEs for Alibi images
  .github/workflows/alibiexplainer_tests.yml
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/adserver/__main__.py
  components/alibi-detect-server/adserver/ad_model.py
  components/alibi-detect-server/adserver/base/__init__.py
  components/alibi-detect-server/adserver/base/alibi_model.py
  components/alibi-detect-server/adserver/cd_model.py
  components/alibi-detect-server/adserver/od_model.py
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/alibiexplainer/seldon_http.py
  components/alibi-explain-server/alibiexplainer/utils.py
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  examples/feedback/metrics-server/config/multiclass-deployment.yaml
  notebooks/server_examples.ipynb
  testing/scripts/kind_test_all.sh
  testing/scripts/test_alibi_detect_server.py
  testing/scripts/test_alibi_explain_v2.py
Labels: v1

#4608 Add app-vulns flag to Python images
  .github/workflows/security_tests.yml
Labels: v1

#4629 Add CONTRIBUTING file (V2)
  CONTRIBUTING.md
Labels: v2

#4630 Move Envoy image to UBI
  scheduler/Dockerfile.envoy
Labels: v2

#4628 v2: Change to ubi images for go applications
  hodometer/Dockerfile.hodometer
  hodometer/Dockerfile.receiver
  operator/Dockerfile
  scheduler/Dockerfile.agent
  scheduler/Dockerfile.modelgateway
  scheduler/Dockerfile.pipelinegateway
  scheduler/Dockerfile.scheduler
Labels: v2

#4624 v2: Add ability to load without model configuration files and add more examples
  docs/source/contents/examples/index.md
  docs/source/contents/examples/model-zoo.md
  docs/source/contents/getting-started/index.md
  docs/source/contents/models/inference-artifacts/index.md
  samples/.gitignore
  samples/examples/huggingface/huggingface.md
  samples/examples/image_classifier/train.ipynb
  samples/model-zoo-requirements.txt
  samples/model-zoo.ipynb
  samples/model-zoo.md
  samples/model-zoo_files/model-zoo_17_0.png
  samples/model-zoo_files/model-zoo_31_0.png
  samples/models/add10.yaml
  samples/models/cifar10-no-config.yaml
  samples/models/conditional.yaml
  samples/models/income-lgb.yaml
  samples/models/income-xgb.yaml
  samples/models/mnist-onnx.yaml
  samples/models/mnist-pytorch.yaml
  samples/models/mul10.yaml
  samples/models/sklearn-iris-gs.yaml
  samples/models/wine-mlflow.yaml
  samples/pipeline-examples.ipynb
  samples/pipeline-examples.md
  samples/scripts/models/Makefile
  samples/scripts/models/cifar10-tensorflow/.gitignore
  samples/scripts/models/income-lgb/.gitignore
  samples/scripts/models/income-lgb/train.py
  samples/scripts/models/income-xgb/.gitignore
  samples/scripts/models/income-xgb/train.py
  samples/scripts/models/mnist-onnx/.gitignore
  samples/scripts/models/mnist-pytorch/.gitignore
  samples/scripts/models/mnist-pytorch/config.pbtxt
  samples/scripts/models/wine-mlflow/.gitignore
  samples/scripts/models/wine-mlflow/train.py
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/client_test.go
  scheduler/pkg/agent/repository/mlserver/mlserver.go
  scheduler/pkg/agent/repository/mlserver/mlserver_test.go
  scheduler/pkg/agent/repository/mlserver/settings.go
  scheduler/pkg/agent/repository/mlserver/settings_test.go
  scheduler/pkg/agent/repository/mlserver/testdata/model.py
  scheduler/pkg/agent/repository/model_repository.go
  scheduler/pkg/agent/repository/model_repository_test.go
  scheduler/pkg/agent/repository/triton/triton.go
  scheduler/pkg/agent/repository/triton/triton_test.go
Labels: v2

#4632 Migrate dataflow engine to UBI9 base image
  scheduler/Dockerfile.dataflow
Labels: v2
