Repository SeldonIO/seldon-core, pull requests merged in 2023-04, with the labels that each got.

#4743 setup.py `grpcio-reflection < 2`
  python/setup.py
Labels: needs-ok-to-test

#4741 Fix check for separate annotation pid
  operator/apis/machinelearning.seldon.io/v1/defaults.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go
  operator/controllers/selddondeployment_controller_components_test.go
  operator/controllers/seldondeployment_controller.go
Labels: v1

#4784 refactor(agent): Format agent code
  scheduler/pkg/agent/client.go
  scheduler/pkg/agent/config/config.go
  scheduler/pkg/agent/k8s/secrets.go
  scheduler/pkg/agent/rclone/rclone.go
  scheduler/pkg/agent/rclone/rclone_config.go
  scheduler/pkg/agent/rclone/rclone_test.go
  scheduler/pkg/agent/repository/model_repository.go
Labels: v2

#4780 fix(agent): Use type from storage config and enforce name matches config
  scheduler/pkg/agent/rclone/rclone.go
Labels: v2

#4781 feat(dataflow): Use raw contents in joins if any message uses raw contents
  samples/pipeline-examples.ipynb
  samples/pipeline-examples.md
  samples/pipelines/tfsimples-input.yaml
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Joiner.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/StreamTransforms.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/protocol.kt
Labels: v2

#4779 feat(dataflow): Add missing filter for requests without input tensors
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Joiner.kt
Labels: v2

#4790 Triton inference server upgrade to 23.03 release
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  samples/model-zoo.ipynb
  samples/model-zoo.md
  samples/models/mnist-onnx.yaml
  samples/models/mnist-pytorch.yaml
  samples/scripts/models/Makefile
  scheduler/Makefile
  scheduler/env.all
  scheduler/k8s/triton/triton.yaml
Labels: v2

#4772 feat(samples): Add kernel shap explainer for income model
  samples/scripts/models/Makefile
  samples/scripts/models/income/.gitignore
  samples/scripts/models/income/classifier/model-settings.json
  samples/scripts/models/income/explainers/anchor-explainer/model-settings.json
  samples/scripts/models/income/explainers/kernel-shap-explainer/model-settings.json
  samples/scripts/models/income/train.py
Labels: v2

#4744 check for duplicate svc-name annotations
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go
  operator/apis/machinelearning.seldon.io/v1/seldondeployment_webhook_test.go
Labels: v1

#4787 Bump MLServer to 1.3.0 (V2)
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  samples/examples/image_classifier/infer.ipynb
  samples/examples/image_classifier/infer.md
  samples/examples/income_classifier/infer.ipynb
  samples/examples/income_classifier/infer.md
  samples/explainer-examples.ipynb
  samples/explainer-examples.md
  samples/k8s-batch-examples.ipynb
  samples/k8s-batch-examples.md
  samples/k8s-examples.ipynb
  samples/k8s-examples.md
  samples/k8s-explainers.ipynb
  samples/k8s-explainers.md
  samples/k8s-tritonclient-aio.ipynb
  samples/k8s-tritonclient-aio.md
  samples/k8s-tritonclient.ipynb
  samples/k8s-tritonclient.md
  samples/model-zoo.ipynb
  samples/model-zoo.md
  samples/models/cifar10-drift-detect.yaml
  samples/models/cifar10-outlier-detect.yaml
  samples/models/income-drift.yaml
  samples/models/income-explainer-pipeline.yaml
  samples/models/income-explainer.yaml
  samples/models/income-lgb.yaml
  samples/models/income-outlier.yaml
  samples/models/income-preprocess.yaml
  samples/models/income-xgb.yaml
  samples/models/income.yaml
  samples/models/moviesentiment-explainer.yaml
  samples/models/moviesentiment.yaml
  samples/models/sklearn-iris-gs.yaml
  samples/models/wine-mlflow.yaml
  samples/scripts/models/Makefile
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4788 Bump MLServer to 1.3.0 (V1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4796 updated overview.md with azureblob example
  doc/source/servers/overview.md
Labels: needs-ok-to-test

#4798 Upgrade to go 1.19.8 due to CVE-2023-24537
  hodometer/Dockerfile.hodometer
  hodometer/Dockerfile.receiver
  operator/Dockerfile
  scheduler/Dockerfile.agent
  scheduler/Dockerfile.modelgateway
  scheduler/Dockerfile.pipelinegateway
  scheduler/Dockerfile.scheduler
Labels: v2

#4815 Use a more recent jdk base image
  scheduler/Dockerfile.dataflow
Labels: v2

#4814 Add utilities to re-build artefacts
  samples/Makefile
  samples/README.md
  samples/scripts/explainers/Makefile
  samples/scripts/models/Makefile
Labels: v2
