Repository SeldonIO/seldon-core, pull requests merged in 2023-05, with the labels that each got.

#4786 refactor(dataflow): Refactor conversion to binary contents
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/BinaryContent.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Joiner.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/protocol.kt
Labels: v2

#4742 Allow spec provided prod security context to take precendence
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_controller_test.go
Labels: v1

#4829 Pin bitnami kafka to 3.3.1 in local installation
  scheduler/Makefile
Labels: v2

#4836 Remove librpmio from Dockerfile.dataflow
  scheduler/Dockerfile.dataflow
Labels: v2

#4812 Delete request-logger path from testing script
  testing/scripts/kind_test_all.sh
Labels: needs-ok-to-test, v1

#4791 Fix python grpc api build
  apis/Makefile
  apis/python/mlops/v2_dataplane/v2_dataplane_pb2.py
  apis/python/mlops/v2_dataplane/v2_dataplane_pb2.pyi
  apis/python/mlops/v2_dataplane/v2_dataplane_pb2_grpc.py
Labels: v2

#4807 Bump MLServer to 1.3.2 (V2)
  k8s/Makefile
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/seldon-v2-components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4808 Bump MLServer to 1.3.2 (V1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4834 feat(models): Add model status message for k8s resource status
  operator/apis/mlops/v1alpha1/model_conditions.go
  operator/apis/mlops/v1alpha1/pipeline_types.go
  operator/controllers/mlops/model_controller.go
  operator/controllers/mlops/pipeline_controller.go
  operator/scheduler/client.go
  operator/scheduler/model.go
  operator/scheduler/pipeline.go
Labels: v2

#4841 k6 fixes for model names
  tests/k6/components/utils.js
  tests/k6/scenarios/infer_constant_rate.js
  tests/k6/scenarios/predict_agent_oc.js
Labels: v2

#4817 release(documentation): add compilation of commands to tag go packages
  RELEASE.md
Labels: v2

#4832 Use release namespace for configmaps in setup helm chart
  k8s/helm-charts/seldon-core-v2-setup/templates/agent.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/kafka.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/rclone-gs-public.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/tracing.yaml
Labels: needs-ok-to-test, v2

#4831 feat(kafka): add support for SASL with PLAIN mechanism
  components/tls/pkg/tls/util.go
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/kustomize/helm-components/patch_dataflow.yaml
  k8s/kustomize/helm-components/patch_modelgateway.yaml
  k8s/kustomize/helm-components/patch_pipelinegateway.yaml
  scheduler/Dockerfile.dataflow
  scheduler/Dockerfile.modelgateway
  scheduler/Dockerfile.pipelinegateway
  scheduler/data-flow/build.gradle.kts
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/Cli.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/Main.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Configuration.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/KafkaAdmin.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/security/Protocols.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/security/Sasl.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/Config.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/K8sCertSecretsProvider.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/Provider.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/sasl/K8sPasswordSecretsProvider.kt
  scheduler/data-flow/src/main/resources/local.properties
  scheduler/data-flow/src/test/kotlin/io/seldon/dataflow/CliTest.kt
  scheduler/data-flow/src/test/kotlin/io/seldon/dataflow/kafka/PipelineStepTest.kt
  scheduler/pkg/kafka/config/tls.go
Labels: v2

#4845 feat(samples): change kernel shap explainer link function to identity
  samples/scripts/models/income/train.py
Labels: v2

#4835 Fix Alibi Explainer tests
  .github/workflows/alibiexplainer_tests.yml
Labels: v1

#4846 Minor typo: scrapping -> scraping
  docs/source/contents/getting-started/index.md
Labels: Documentation, v2

#4843 build(install): Generate plain YAML manifests from Helm templates
  k8s/Makefile
  k8s/yaml/certs.yaml
  k8s/yaml/components.yaml
  k8s/yaml/crds.yaml
  k8s/yaml/servers.yaml
Labels: v2

#4837 Add mermaid diagrams to pipeline docs page
  docs/requirements-docs.txt
  docs/source/conf.py
  docs/source/contents/pipelines/index.md
Labels: v2

#4833 Bump Envoy to 1.26.1 and Go Control Plane to 0.11.0
  scheduler/Dockerfile.envoy
  scheduler/go.mod
  scheduler/go.sum
Labels: needs-ok-to-test, v2

#4848 Fix typo in doc
  docs/source/contents/models/index.md
  samples/model-zoo.md
Labels: needs-ok-to-test, v2

#4838 Add a macOS m1 specific build target for seldon client
  docs/source/contents/cli/index.md
  docs/source/contents/getting-started/cli.md
  operator/Makefile
Labels: needs-ok-to-test, v2

#4853 documentation(Kafka): Add docs on Confluent Kafka integration
  Makefile
  ansible/README.md
  ansible/playbooks/setup-ecosystem.yaml
  ansible/roles/ecosystem/defaults/main.yaml
  ansible/roles/ecosystem/tasks/kafka.yaml
  docs/requirements-docs.txt
  docs/source/contents/getting-started/configuration/index.md
  docs/source/contents/getting-started/kubernetes-installation/ansible.md
  docs/source/contents/getting-started/kubernetes-installation/helm.md
  docs/source/contents/getting-started/kubernetes-installation/index.md
  docs/source/contents/getting-started/kubernetes-installation/kafka.md
  docs/source/contents/getting-started/kubernetes-installation/security/confluent-sasl.md
  docs/source/contents/getting-started/kubernetes-installation/security/index.md
  docs/source/contents/kubernetes/kafka/index.md
  k8s/samples/values-confluent-kafka-sasl.yaml.tmpl
  kafka/strimzi/README.md
Labels: v2

#4866 Add PITS Global Data Recovery Services to the list of adopters
  ADOPTERS.md
Labels: needs-ok-to-test

#4872 Update envoy and go-control-plane and fix deprecations
  scheduler/Dockerfile.envoy
  scheduler/go.mod
  scheduler/go.sum
  scheduler/pkg/envoy/resources/resource.go
Labels: v2

#4869 removing alpha messaging from FAQ
  docs/source/contents/faqs/index.md
Labels: v2

#4868 removing alpha messaging from index pages
  README.md
  doc/source/index.rst
Labels: v2

#4824 Surface errors during reconcilliation for Servers
  operator/apis/mlops/v1alpha1/server_types.go
  operator/controllers/mlops/server_controller.go
  samples/servers/mlserver-badname.yaml
Labels: v2
