Repository SeldonIO/seldon-core, pull requests merged in 2023-10, with the labels that each got.

#5143 fix(scheduler): Fix deleting models that are still progressing
  operator/scheduler/model.go
  scheduler/pkg/store/memory.go
Labels: v2

#5030 fix: Start triton server via bash -c tritonserver instead of just tritonserver
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/yaml/components.yaml
  operator/config/serverconfigs/triton.yaml
Labels: ok-to-test

#5141 fix(seldon operator): "Deployment differs"-logs will never show
  operator/controllers/seldondeployment_controller.go
Labels: needs-ok-to-test, v1
