Repository SeldonIO/seldon-core, pull requests merged in 2023-07, with the labels that each got.

#4967 fix(agent): Fix for agent leaking Rclone storage secrets via logs
  scheduler/pkg/agent/rclone/rclone.go
  scheduler/pkg/agent/rclone/rclone_config.go
Labels: v2

#4971 fix: rerun core v2 examples and generate markdown
  samples/examples/huggingface/huggingface.ipynb
  samples/examples/huggingface/huggingface.md
  samples/examples/huggingface/sentiment-input-transform/model.py
  samples/examples/huggingface/sentiment-output-transform/model.py
  samples/examples/huggingface/test-transforms.ipynb
  samples/examples/huggingface/test-transforms.md
  samples/examples/image_classifier/infer.ipynb
  samples/examples/image_classifier/infer.md
  samples/examples/income_classifier/infer.ipynb
  samples/examples/income_classifier/infer.md
  samples/examples/pandasquery/infer.ipynb
  samples/examples/pandasquery/infer.md
  samples/explainer-examples.ipynb
  samples/explainer-examples.md
  samples/k8s-batch-examples.ipynb
  samples/k8s-batch-examples.md
  samples/k8s-examples.ipynb
  samples/k8s-examples.md
  samples/local-examples.ipynb
  samples/local-examples.md
  samples/local-experiments.ipynb
  samples/local-experiments.md
  samples/models/hf-sentiment-input-transform.yaml
  samples/models/hf-sentiment-output-transform.yaml
  samples/pipeline-examples.ipynb
  samples/pipeline-examples.md
  samples/pipeline-ready-and-metadata.ipynb
  samples/pipeline-ready-and-metadata.md
  samples/pipeline-to-pipeline.ipynb
  samples/pipeline-to-pipeline.md
  samples/pipelines/sentiment-explain.yaml
Labels: v2

#4969 docs(rclone): Update storage secrets docs with expectations and details on usage
  docs/source/contents/kubernetes/cloud-storage/index.md
  docs/source/contents/kubernetes/index.md
  docs/source/contents/kubernetes/storage-secrets/index.md
  samples/auth/agent.yaml
Labels: v2

#4979 fix: use current user and group id in local (compose) deployment
  scheduler/Makefile
  scheduler/all-base.yaml
Labels: v2

#4941 feat: Allow disabling of reconciles when config CRDs change
  docs/source/contents/kubernetes/resources/seldonruntime/index.md
  k8s/helm-charts/seldon-core-v2-crds/templates/seldon-v2-crds.yaml
  k8s/helm-charts/seldon-core-v2-runtime/templates/seldon-runtime.yaml
  k8s/helm-charts/seldon-core-v2-runtime/values.yaml
  k8s/yaml/crds.yaml
  k8s/yaml/runtime.yaml
  operator/apis/mlops/v1alpha1/seldonruntime_types.go
  operator/apis/mlops/v1alpha1/server_types.go
  operator/config/crd/bases/mlops.seldon.io_seldonruntimes.yaml
  operator/config/crd/bases/mlops.seldon.io_servers.yaml
  operator/controllers/mlops/seldonruntime_controller.go
  operator/controllers/mlops/server_controller.go
Labels: v2

#4972 build(mlserver): bump MLServer to 1.3.5
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  samples/Makefile
  samples/README.md
  samples/examples/image_classifier/infer.ipynb
  samples/examples/image_classifier/infer.md
  samples/examples/income_classifier/infer.ipynb
  samples/examples/income_classifier/infer.md
  samples/examples/pandasquery/infer.ipynb
  samples/examples/pandasquery/infer.md
  samples/explainer-examples.ipynb
  samples/explainer-examples.md
  samples/k8s-batch-examples.ipynb
  samples/k8s-batch-examples.md
  samples/k8s-clusterwide.ipynb
  samples/k8s-clusterwide.md
  samples/k8s-examples.ipynb
  samples/k8s-examples.md
  samples/k8s-explainers.ipynb
  samples/k8s-explainers.md
  samples/k8s-multi-version.ipynb
  samples/k8s-multi-version.md
  samples/k8s-tritonclient-aio.ipynb
  samples/k8s-tritonclient-aio.md
  samples/k8s-tritonclient.ipynb
  samples/k8s-tritonclient.md
  samples/local-examples.ipynb
  samples/local-examples.md
  samples/local-experiments.ipynb
  samples/local-experiments.md
  samples/model-zoo.ipynb
  samples/model-zoo.md
  samples/models/add10.yaml
  samples/models/cifar10-drift-detect.yaml
  samples/models/cifar10-outlier-detect.yaml
  samples/models/conditional.yaml
  samples/models/income-drift.yaml
  samples/models/income-explainer-pipeline.yaml
  samples/models/income-explainer.yaml
  samples/models/income-lgb.yaml
  samples/models/income-outlier.yaml
  samples/models/income-preprocess.yaml
  samples/models/income-xgb.yaml
  samples/models/income.yaml
  samples/models/moviesentiment-explainer.yaml
  samples/models/moviesentiment.yaml
  samples/models/mul10.yaml
  samples/models/multi-version-1.yaml
  samples/models/multi-version-2.yaml
  samples/models/sklearn-iris-gs.yaml
  samples/models/wine-mlflow.yaml
  samples/pipeline-examples.ipynb
  samples/pipeline-examples.md
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4996 bump google.golang.org/grpc library version
  executor/go.mod
  executor/go.sum
  executor/licenses/dep.txt
Labels: v1

#4997 fix: Change tracing to disable rather than enable flag
  k8s/helm-charts/seldon-core-v2-crds/templates/seldon-v2-crds.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/kustomize/helm-components-sc/patch_tracingconfig.yaml
  k8s/yaml/components.yaml
  k8s/yaml/crds.yaml
  operator/apis/mlops/v1alpha1/seldonconfig_types.go
  operator/apis/mlops/v1alpha1/seldonconfig_types_test.go
  operator/config/crd/bases/mlops.seldon.io_seldonconfigs.yaml
  operator/config/crd/bases/mlops.seldon.io_seldonruntimes.yaml
  operator/controllers/reconcilers/seldon/configmap_reconciler.go
  scheduler/config/tracing-host.json
  scheduler/config/tracing-internal.json
  scheduler/pkg/tracing/provider.go
  scheduler/pkg/tracing/provider_test.go
Labels: v2

#4974 Bump MLServer to 1.3.5 (v1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4990 fix: Disable default logging for Kafka in Ansible Playbooks
  ansible/playbooks/templates/values-seldon-core-v2-components.yaml.j2
Labels: v2

#4910 upgrading to python 3.8
  servers/sklearnserver/Makefile
  servers/sklearnserver/sklearnserver/requirements.txt
  servers/tfserving_proxy/Makefile
  servers/xgboostserver/Makefile
  servers/xgboostserver/xgboostserver/requirements.txt
Labels: needs-ok-to-test, v1

#4928 fix(scheduler): Add >0 replica check for server filter scheduling
  scheduler/pkg/scheduler/filters/serverreplicas.go
  scheduler/pkg/scheduler/filters/serverreplicas_test.go
  scheduler/pkg/scheduler/scheduler.go
Labels: v2

#5009 fix: runtime tracing config value in helm chart should be disable
  k8s/helm-charts/seldon-core-v2-runtime/templates/seldon-runtime.yaml
  k8s/helm-charts/seldon-core-v2-runtime/values.yaml
Labels: needs-ok-to-test

#5010 fix: misc v2 release fixes: runtime enabe.disable, hodometer Makefile, mlserver tracing
  hodometer/Makefile
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/kustomize/helm-components-sc/patch_mlserver.yaml
  k8s/yaml/components.yaml
  k8s/yaml/runtime.yaml
Labels: v2

#5012 fix: misc fixes for copyright, licenses and integration tests
  components/tls/licenses/license.txt
  components/tls/licenses/license_info.csv
  hodometer/licenses/license.txt
  hodometer/licenses/license_info.csv
  operator/licenses/license.txt
  operator/licenses/license_info.csv
  scheduler/licenses/license.txt
  scheduler/licenses/license_info.csv
  scheduler/pkg/scheduler/filters/serverreplicas.go
  scheduler/pkg/scheduler/filters/serverreplicas_test.go
  tests/integration/licenses/license.txt
  tests/integration/licenses/license_info.csv
  tests/integration/pkg/tests/testdata/sklearn-iris-response.json
  tests/integration/pkg/tests/testdata/xgboost-income-response.json
Labels: v2

#5014 feat(helm): Make SeldonConfig configurable in SeldonRuntime Helm chart
  k8s/helm-charts/seldon-core-v2-runtime/templates/seldon-runtime.yaml
  k8s/helm-charts/seldon-core-v2-runtime/values.yaml
Labels: ok-to-test, v2

#5016 Updating Alibi Explain & Detect
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
Labels: v1

#5020 fix: typo in release 2.6 branch
  docs/source/contents/getting-started/kubernetes-installation/helm.md
Labels: v2

#5025 fix: hodometer enable flag and docs
  docs/source/contents/metrics/usage.md
  k8s/Makefile
  k8s/add-helm-toggle-hodometer.sed
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
Labels: v2

#5047 fix(docs): Fix various broken links in docs
  docs/source/conf.py
  docs/source/contents/apis/inference/v2.md
  docs/source/contents/getting-started/index.md
  docs/source/contents/getting-started/kubernetes-installation/helm.md
  docs/source/contents/metrics/usage.md
  docs/source/contents/models/inference-artifacts/index.md
  docs/source/contents/models/rclone/index.md
  docs/source/contents/pipelines/index.md
Labels: v2

#5051 fix: Allow digits in topic prefix
  scheduler/pkg/kafka/topics.go
  scheduler/pkg/kafka/topics_test.go
Labels: v2

#5034 fix: relax pyyaml version range to allow install with new Cython 3
  python/setup.py
Labels: needs-ok-to-test

#5044 docs: Add kafka producer compression example for configuration customization
  docs/source/contents/getting-started/configuration/index.md
  k8s/samples/values-runtime-kafka-compression.yaml
Labels: v2

#5053 fix: Allow number of replicas in k6 tests
  .github/workflows/lint.yml
  tests/k6/components/settings.js
  tests/k6/components/utils.js
Labels: v2

#5059 Allow init containers if modelUri provided
  notebooks/protocol_examples.ipynb
  operator/controllers/seldondeployment_controller.go
  operator/controllers/seldondeployment_prepackaged_servers.go
  operator/controllers/seldondeployment_prepackaged_servers_test.go
Labels: v1
