Repository SeldonIO/seldon-core, pull requests merged in 2023-06, with the labels that each got.

#4880 Bump MLServer to 1.3.3 (v2)
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4886 good first issue for knative readme
  doc/source/streaming/knative_eventing.md
  examples/streaming/knative-eventing/README.md
Labels: needs-ok-to-test, v1

#4891 ci: Add CI workflow ensuring PR titles conform to Conventional Commit format
  .github/workflows/pr-title.yaml
  CONTRIBUTING.md
Labels: v2

#4879 Bump MLServer to 1.3.3 (v1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4900 build(v2): Bump MLServer to 1.3.3
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4895 test: create initial Integration tests
  Makefile
  hack/boilerplate.sh
  licenses/3rd-party-summary.txt
  operator/cmd/seldon/cli/experiment_list.go
  operator/cmd/seldon/cli/experiment_start.go
  operator/cmd/seldon/cli/experiment_status.go
  operator/cmd/seldon/cli/experiment_stop.go
  operator/cmd/seldon/cli/flags.go
  operator/cmd/seldon/cli/infer.go
  operator/cmd/seldon/cli/load.go
  operator/cmd/seldon/cli/model_infer.go
  operator/cmd/seldon/cli/model_list.go
  operator/cmd/seldon/cli/model_load.go
  operator/cmd/seldon/cli/model_status.go
  operator/cmd/seldon/cli/model_unload.go
  operator/cmd/seldon/cli/pipeline_infer.go
  operator/cmd/seldon/cli/pipeline_inspect.go
  operator/cmd/seldon/cli/pipeline_list.go
  operator/cmd/seldon/cli/pipeline_load.go
  operator/cmd/seldon/cli/pipeline_status.go
  operator/cmd/seldon/cli/pipeline_unload.go
  operator/cmd/seldon/cli/server_list.go
  operator/cmd/seldon/cli/server_status.go
  operator/cmd/seldon/cli/status.go
  operator/cmd/seldon/cli/unload.go
  operator/pkg/cli/generic.go
  operator/pkg/cli/infer.go
  operator/pkg/cli/kafka.go
  operator/pkg/cli/scheduler.go
  operator/pkg/cli/utils.go
  tests/integration/.errcheck_excludes.txt
  tests/integration/.gitignore
  tests/integration/.golangci.yml
  tests/integration/Makefile
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/licenses/dep.txt
  tests/integration/licenses/license.txt
  tests/integration/licenses/license_info.csv
  tests/integration/licenses/repo.txt
  tests/integration/pkg/resources/auto_api.go
  tests/integration/pkg/resources/infer_api.go
  tests/integration/pkg/resources/seldon_api.go
  tests/integration/pkg/resources/seldon_k8s_api.go
  tests/integration/pkg/resources/util.go
  tests/integration/pkg/resources/util_test.go
  tests/integration/pkg/tests/model_test.go
  tests/integration/pkg/tests/testdata/sklearn-iris-request.json
  tests/integration/pkg/tests/testdata/sklearn-iris-response.json
  tests/integration/pkg/tests/testdata/sklearn-iris.yaml
  tests/integration/pkg/tests/testdata/tensorflow-tfsimple-request.json
  tests/integration/pkg/tests/testdata/tensorflow-tfsimple-response.json
  tests/integration/pkg/tests/testdata/tensorflow-tfsimple.yaml
  tests/integration/pkg/tests/testdata/xgboost-income-request.json
  tests/integration/pkg/tests/testdata/xgboost-income-response.json
  tests/integration/pkg/tests/testdata/xgboost-income.yaml
Labels: v2

#4924 Fix reconcile diffs found on hpa/keda updates
  operator/apis/machinelearning.seldon.io/v1/prepack.go
  operator/controllers/seldondeployment_controller.go
  operator/controllers/utils/patch_utils.go
  operator/controllers/utils/patch_utils_test.go
Labels: v1

#4919 Rename inference protocol
  docs/source/contents/apis/inference/v2.md
Labels: v2

#4921 fix: Update README.md for k6 tests
  tests/k6/README.md
Labels: v2

#4915 Make rclone config_secrets configurable in values.yaml
  k8s/helm-charts/seldon-core-v2-setup/templates/agent.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
Labels: needs-ok-to-test

#4934 fix: server can be return as nil when not found causing panics
  scheduler/pkg/envoy/processor/incremental.go
  scheduler/pkg/server/server.go
  scheduler/pkg/server/server_status.go
  scheduler/pkg/store/memory.go
  scheduler/pkg/store/memory_test.go
Labels: v2

#4926 build(v2): Bump MLServer to 1.3.4 (v2)
  k8s/helm-charts/seldon-core-v2-setup/values.yaml
  k8s/helm-charts/seldon-core-v2-setup/values.yaml.template
  k8s/yaml/components.yaml
  operator/Makefile
  operator/config/serverconfigs/kustomization.yaml
  scheduler/Makefile
  scheduler/env.all
Labels: v2

#4925 Bump MLServer to 1.3.4 (v1)
  helm-charts/seldon-core-operator/README.md
  helm-charts/seldon-core-operator/values.yaml
  operator/config/manager/configmap.yaml
Labels: v1

#4937 fix: Allow config CRD changes to cause a reconcilliation loop for dependent (but not owned) resources
  operator/controllers/mlops/seldonruntime_controller.go
  operator/controllers/mlops/server_controller.go
  samples/k8s-clusterwide-kafka-mtls-demo.ipynb
  samples/k8s-clusterwide-ssl-demo.ipynb
Labels: v2

#4938 fix: Fix dataflow disable bug and update notebooks for clusterwide
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/kustomize/helm-components-sc/patch_dataflow.yaml
  k8s/yaml/components.yaml
  operator/config/seldonconfigs/default.yaml
  operator/controllers/reconcilers/seldon/runtime_reconciler.go
  samples/k8s-clusterwide-kafka-mtls-demo.md
  samples/k8s-clusterwide-ssl-demo.md
  samples/k8s-clusterwide.ipynb
  samples/k8s-clusterwide.md
  samples/k8s-examples.md
Labels: v2

#4946 fix: use python3 in k6 builder image
  tests/k6/Dockerfile.k6
Labels: v2

#4940 fix: Only create kafka config once in model gateway
  scheduler/cmd/modelgateway/main.go
  scheduler/pkg/kafka/gateway/infer.go
  scheduler/pkg/kafka/gateway/manager.go
  scheduler/pkg/kafka/gateway/manager_test.go
  scheduler/pkg/kafka/gateway/worker_test.go
Labels: v2

#4912 Update Alibi and Alibi-Detect versions and bump servers to Python 3.8
  .github/workflows/alibidetect_tests.yml
  .github/workflows/alibiexplainer_tests.yml
  components/alibi-detect-server/Dockerfile
  components/alibi-detect-server/Makefile
  components/alibi-detect-server/adserver/tests/test_cd_model.py
  components/alibi-detect-server/poetry.lock
  components/alibi-detect-server/pyproject.toml
  components/alibi-explain-server/Dockerfile
  components/alibi-explain-server/Makefile
  components/alibi-explain-server/poetry.lock
  components/alibi-explain-server/pyproject.toml
  python/licenses/license.txt
  python/licenses/license_info.csv
  python/licenses/license_info.no_versions.csv
  python/setup.py
  testing/resources/adserver-cifar10-od-rclone.yaml
  testing/resources/adserver-cifar10-od.yaml
  testing/resources/iris_anchor_tabular_explainer.yaml
  wrappers/s2i/python/Dockerfile
  wrappers/s2i/python/Dockerfile.gpu
  wrappers/s2i/python/Makefile
Labels: v1

#4916 feat: One side TLS for Kafka
  components/tls/pkg/tls/util.go
  k8s/helm-charts/seldon-core-v2-setup/templates/seldon-v2-components.yaml
  k8s/kustomize/helm-components-sc/patch_modelgateway.yaml
  k8s/kustomize/helm-components-sc/patch_pipelinegateway.yaml
  k8s/yaml/components.yaml
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/kafka/Configuration.kt
  scheduler/data-flow/src/main/kotlin/io/seldon/dataflow/mtls/Provider.kt
  scheduler/pkg/kafka/config/tls.go
Labels: v2

#4958 fix: ansible for new helm charts
  ansible/playbooks/setup-seldon.yaml
  ansible/playbooks/templates/values-seldon-core-v2-servers.yaml.j2
  ansible/playbooks/vars/default.yaml
  ansible/roles/seldon/defaults/main.yaml
  ansible/roles/seldon/tasks/install_runtime.yaml
  ansible/roles/seldon/tasks/install_servers.yaml
  ansible/roles/seldon/tasks/main.yaml
Labels: v2

#4963 fix: remove last applied annotation in operator when adding annotations
  operator/pkg/utils/utils.go
Labels: v2

#4965 Fix typo
  docs/source/contents/pipelines/index.md
Labels: needs-ok-to-test

#4956 Update go-restful
  executor/go.mod
  executor/go.sum
  operator/go.mod
  operator/go.sum
Labels: v1

#4957 Bump MLflow to 2.4.1
  servers/mlflowserver/mlflowserver/requirements.txt
Labels: v1
